### ISSUE TITLE
Update the docs

### ISSUE THREAD

**Issue by orobert-ia** [Sitecore/jss#1116]
https://doc.sitecore.com/xp/en/developers/hd/190/sitecore-headless-development/walkthrough--creating-a-jss-next-js-application-with-the-jss-cli.html

https://doc.sitecore.com/xp/en/developers/hd/190/sitecore-headless-development/create-a-jss-project-for-the-latest-versions-of-jss-and-sitecore.html

Everything here is outdated and does not work. `jss create` returns a 400 error in version 19 of the CLI and gives a depreciation error in version 20 of the CLI.

There are other pages in the docs mentioning the `jss create` command and they should also be updated.

This documentation has been outdated for over a year now and it gives serious headaches to users trying to start with jss, please update it.

**Comment by ambrauer** [comment]
Hello! You need to specify the release branch for older versions e.g. `jss create my-jss-app react --branch release/19.0.0` as instructed in the depreciation error. 

Please refer to the [latest documentation for version 20](https://doc.sitecore.com/xp/en/developers/hd/200/sitecore-headless-development/create-a-jss-app-for-an-older-version-of-sitecore.html), and you will find proper instructions for creating using older versions. Unfortunately, the docs for previous versions were not updated to reflect this change (though you would have always needed to specify the `--branch`).

In the future, you can send feedback about the documentation to [docsite@sitecore.net](mailto:docsite@sitecore.net?Subject=Title%20:%20create-a-jss-app-for-an-older-version-of-sitecore&body=Url:%20https://doc.sitecore.com/xp/en/developers/hd/200/sitecore-headless-development/create-a-jss-app-for-an-older-version-of-sitecore.html).
