### ISSUE TITLE
Containerised SSR rendering for CM

### ISSUE THREAD

**Issue by piratebriggs** [Sitecore/jss#112]
## Is your feature request related to a problem? Please describe.
The "problem" is that I'm looking for a way to treat Sitecore as a service that other applications can consume via the JSS APIs (content service, dictionary & graphql).

The current JSS implementation gets close to this if you use a SSR proxy. You only need to import the media & items in to the sitecore instance (it is a CMS after all!) and the react application files can be deployed to a docker container for example.

Where this currently falls down is that to enable the Experience Editor, you need to deploy your react app files to the CM server (or App Service etc)

## Describe the solution you'd like
I'd like to replicate the SSR proxy model for rendering markup needed by the experience editor. I've had a poke around in the JSS.ViewEngine assemblies and can see that the rendered html is currently transmitted from the node process to Sitecore over HTTP but the managing of the pool of node processes is currently tightly coupled to the INodeServices implementation.

I think it would make sense to re-use the existing INodeInstance implementation but host it in a .Net Core application that can be containerised.

**Comment by kamsar** [comment]
We like this idea 👍

**Comment by richgo** [comment]
+1 for this.  It will make our lives a lot simpler with our intended use case: running a Sitecore service instance with many decoupled React Apps.

**Comment by piratebriggs** [comment]
Did this feature make the SC9.2/JSS12 release that dropped a few days ago? There doesn't seem to be any new documentation just yet

**Comment by kamsar** [comment]
The feature was not included in 9.2

**Comment by piratebriggs** [comment]
Any update on the ETA? Is it waiting on a JSS release or a SC release?

After it was demoed at SUGCON-EU we thought it was a done deal - was there technical issues or is the marketing team trying to come up with a good name for it? :)

**Comment by aweber1** [comment]
@piratebriggs with Sitecore 9.1.1 and 9.2, the Sitecore server-side bits for JSS rendering host are ready to be used but client side is missing (as you know). Until the JSS team has more time and is able to finalize the client-side bits, I created a gist to demonstrate a "basic" rendering host setup: 

https://gist.github.com/aweber1/39d1e9e07fb19aac9bc9b94feb87bb0f

**Comment by sc-dawidrutkowski** [comment]
HTTP Rendering Engine feature has been merged to the dev branch. It still requires some improvements and cleaning (+ additional testing) but the basic functionality is already working fine. 
We are planning to include this in next release of NPM packages but I can't give a date right now.
