### ISSUE TITLE
FR: Add option to transform layout service data in sitecore-jss-proxy

### ISSUE THREAD

**Issue by aweber1** [Sitecore/jss#113]
## Is your feature request related to a problem? Please describe.
Currently, you can't modify layout service data at the proxy level before it is returned to client-side requests or passed into the AppRenderer for SSR.

## Describe the solution you'd like
Add a config option that allows for custom layout service data transformation.

## Describe alternatives you've considered
1. Disable all host resolving on the Sitecore side when generating links/media, etc... Just emit relative URLs.
2. Technically, you could modify the LS output on the Sitecore side to replace host names. However, not really recommend because the host names would need to be "hard-coded" and changed via some sort of config and that config would need to be managed as you promote code through dev, staging, prod, etc...
3. Replace the host names via custom proxy fork.
4. Replace the host names in your app code.

## Additional information
How hard can it be? Come on guys, just do it, you know you want to.

**Comment by aweber1** [comment]
Note: we are working on this feature but it is part of a larger refactoring effort for the node SSR proxy that will expose more configuration options and extension points for the proxy.

**Comment by nickwesselman** [comment]
Should already be possible via `proxyOptions.onProxyRes`
