### ISSUE TITLE
mediaApi.updateImageUrl loses "extension" querystring

### ISSUE THREAD

**Issue by CatiaGomes82** [Sitecore/jss#1139]
## Description
The image url coming from the layout service is `/-/jssmedia/paris-office.ashx?w=800&h=auto&mw=800&rev=1c3417c44e6e4ac082b7208292b5ceeb&extension=webp` but `extension=webp` gets removed in the Image Component. We are using [Dianoga](https://github.com/kamsar/Dianoga) to convert images to webp but it needs `extension=webp` in the image url to return the correct extension to the user. 

## Expected behavior
Image url should keep the `extension` query string to allow the server to identify it's an image to be converted to webp.

## Possible Fix
The parameter `extension` should be whitelisted and not be removed from the url in `mediaApi.updateImageUrl`.

## Your Environment
* JSS Version: 16.0.0

**Comment by gmorgenne** [comment]
Adding this functionality would be huge. We upgraded to sitecore-jss-nextjs 20.1.3 hoping to improve performance with the <NextImage /> component. We didn't to write a bunch of logic to use the sitecore <Image /> component while editing and the next <Image /> compoennt while not editing and thought that the wrapper of the <NextImage /> component from sitecore would solve this problem. I like the priority and lazy loading functionality and think the improvements there are worth the time invested in switching to the <NextImage /> component, but the next gen format support would really take it over the edge!
