### ISSUE TITLE
Upgrade used JSS Angular Version to 14

### ISSUE THREAD

**Issue by monkey-ldb** [Sitecore/jss#1151]
## Is your feature request related to a problem? Please describe.
The currently used version 11 will not get any more security updates, because the security support is end of life (since 11.05.2022).
Also frameworks which may be dependent to the angular version, will now longer get updates for older versions.
Its also not possible to use newer framework features with the old version.

## Describe the solution you'd like
I would like to request an update of the used angular version to the newest version 14.x.

## Describe alternatives you've considered
its not an alternative to stay on the current version for that long.

## Additional information
Is there a roadmap for that?

**Comment by ambrauer** [comment]
Hi @monkey-ldb - Yes, we have this on our roadmap and are actively working on this effort, planned for an upcoming release (TBD).

**Comment by moh4sa** [comment]
Hi @ambrauer any update on this issue currently angular 11 is officially out of support and soon 12 will be out of support as well.

**Comment by ambrauer** [comment]
Hi @moh4sa - We are targeting to include this in a release of JSS before the end of the year.

**Comment by d3473r** [comment]
Hi @ambrauer, do you have an updated ETA on this issue?

**Comment by ambrauer** [comment]
Hi @d3473r - ETA is early 2023 (now targeting end of January / February)

**Comment by AlexandruPaun4Ness** [comment]
Hello guys, Is there any update on the angular upgrade for JSS?

**Comment by monkey-ldb** [comment]
> Hi @d3473r - ETA is early 2023 (now targeting end of January / February)

Hey, do you have an update for us?
Its march and there is no update from your side yet.

**Comment by ambrauer** [comment]
Hi @monkey-ldb - We are planning to release JSS 21.1.0 next week, which will include the [upgrade to Angular 14](https://github.com/Sitecore/jss/pull/1285).

Upgrade to 15/16 is in our backlog for consideration.

cc @AlexandruPaun4Ness @d3473r @moh4sa

**Comment by williamsk** [comment]
> We are planning to release JSS 21.1.0 next week, which will include the upgrade to Angular 14

@ambrauer will JSS 21.1.0 be compatible with 10.1.2 or will we need to update to 10.3?

**Comment by ambrauer** [comment]
> > We are planning to release JSS 21.1.0 next week, which will include the upgrade to Angular 14
> 
> @ambrauer will JSS 21.1.0 be compatible with 10.1.2 or will we need to update to 10.3?

@williamsk JSS 21.1.0 will only be compatible with Sitecore 10.3. Please see compatibility matrix [here](https://support.sitecore.com/kb?id=kb_article_view&sysparm_article=KB1000576) for reference.

**Comment by AlexandruPaun4Ness** [comment]
> Hi @monkey-ldb - We are planning to release JSS 21.1.0 next week, which will include the [upgrade to Angular 14](https://github.com/Sitecore/jss/pull/1285).
> 
> Upgrade to 15/16 is in our backlog for consideration.
> 
> cc @AlexandruPaun4Ness @d3473r @moh4sa

Hey @ambrauer again the release of this version did not happen. Is there anything blocking it atm ? I am asking this because there are teams wanting to start using angular + Sitecore + jss and they just need a newer version of Angular.
