### ISSUE TITLE
Contextualize component getStaticProps/getServerSideProps to use within Experience Editor

### ISSUE THREAD

**Issue by KKings** [Sitecore/jss#1188]
## Is your feature request related to a problem? Please describe.
Within experience editor or preview mode, if using component level getStaticProps or getServerSideProps to fetch data using GraphQL, the data returned from GraphQL is only the data that is published.  This means that the page level props would be set to the data in the master database used for editing, while the component props would only be the live data.

The recommendation for using Experience Edge is to not leverage the Layout Service for looking up data (such as query results), and instead leverage the GraphQL API or Solr, this is due to the fact Experience Edge does not always regenerate dependent listing page layout data, when query result items have been updated. The EDGE GraphQL endpoint would be favorable when using Vercel and ISR as it is more performant.

The use case is that when editing a page within Experience Editor, components that leverage getStaticProps or getServerSideProps should also be able to leverage the same context as the page level props.

## Describe the solution you'd like
A contextual GraphQL Client, where if Next.js has preview enabled, the GraphQL Client can target the Preview Edge APIs, in the correct database that the author is currently editing the page.

## Describe alternatives you've considered
If it doesn't make sense to have the GraphQL Client understand when the page is in experience editor, it would be good to have for future development teams a clear recommendation in the documentation that getStaticProps or getServerSideProps at the component level can lead to inconsistencies in experience editor.

## Additional information
Technologies used: Sitecore JSS, Next.js, and Experience Edge.

**Comment by illiakovalenko** [comment]
Hello @KKings 
Thanks for the provided information, I've added this to our backlog for discussion
