### ISSUE TITLE
package: The Sitecore.JavaScriptServices module requires a subscription license.

### ISSUE THREAD

**Issue by emp** [Sitecore/jss#12]
This is happening on a working brand new single instance installation trying to deploy the `samples-basic-react` option. 

When I run `yarn package` it goes all the way to 
```
Sending package sitecore\update-package\JssBasicApp.1513824981603.update to http://xp0.sc/ship/services/package/install/fileupload...
``` 

Then fails with the exception below.

The license I have seems to be a normal Sitecore 8 license valid until Sept 2018, is a different type of license required? Rather new to it and unsure how licensing works. Do note everything else seems to work.

```
[LicenseException: The Sitecore.JavaScriptServices module requires a subscription license.]
   Sitecore.Update.Installer.Items.CustomActionInstaller.Process(IProcessingContext entry, IProcessingContext context) +1374
   Sitecore.Update.Installer.DiffInstaller.ExecutePostInstallationInstructions(String packagePath, String historyPath, InstallMode mode, MetadataView view, ILog installationProcessLogger, List`1&amp; entries) +486
   Sitecore.Ship.Infrastructure.Update.UpdatePackageRunner.Execute(String packagePath, Boolean disableIndexing) +427
   Sitecore.Ship.AspNet.Package.InstallUploadPackageCommand.HandleRequest(HttpContextBase context) +309
   Sitecore.Ship.AspNet.Package.InstallPackageCommand.HandleRequest(HttpContextBase context) +287
   Sitecore.Ship.AspNet.AboutCommand.HandleRequest(HttpContextBase context) +396
   Sitecore.Ship.AspNet.BaseHttpHandler.ProcessRequest(HttpContext context) +276
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +798
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +91
```
[installation.fail.zip](https://github.com/Sitecore/jss/files/1577791/installation.fail.zip)

EDIT: Just tried using the update-package wizard and it analyses it fine and in the last step during installation throws the same error, attached the output zip log.

EDIT 2: I guess its answered in the docs at: 

```
Use of the Technical Preview requires a Sitecore license file which has been authorized for Sitecore.Visit, i.e. consumption licensing. Partners may utilize SPN to request a an updated partner license with this permission. Customers should contact their account representative.
```

I'll close it for now and see if I can get the different license.

**Comment by sitecorian** [comment]
For the future reference.  As the [docs indicate](https://jss.sitecore.net/#/requirements), JSS requires a subscription license:

**For partners:**

While your recent partner license should already have subscription key that enables JSS, you may need to request a fresh partner license on spn.sitecore.net or reach out to your Sitecore Account Manager.

**For customers:**

If you are not on subscription license, please reach out to your Sitecore Account Manager and request a temp license for short term needs and discuss migration to a subscription license. If you are not sure whom to reach out to, email us.

**How to check if your existing license enables JSS**:

1. Open your license.xml with a browser (IE works better for some reason). The browser is supposed to show the license details.
    > The browser will show a warning - ignore that.

1. Search for **Sitecore.Visit** key.

If it's present, you have a subscription license and JSS is enabled.
