### ISSUE TITLE
componentFactory is undefined resulting in Missing Components

### ISSUE THREAD

**Issue by KKings** [Sitecore/jss#1214]
## Description
When using Next.js **without** SSG and only ISR (fallback set to blocking), the component factory is undefined and results in all components missing. Note, if using SSG and ISR is triggered, the page is rendered fine - only when no paths are output in getStaticPaths and the page needs to be generated with next.js fallback set to blocking.

Things I've reviewed:
* All components output in componentFactory.ts
* componentFactory function is added to the SitecoreContext component props, in [[...path]].tsx
* If I import the component factory into each component that uses a placeholder and add it to the props manually for each placeholder, all components are working as expected

I did some rudimentary logging to trace when it stops being available:
1. [[...path]].tsx - Available and set as a prop to SitecoreContext.tsx
2. SitecoreContext.tsx - Available and set as the value for the Context Provider
3. withComponentFactory - Not available to the Context Consumer

## Expected behavior
Pages that are generated after build time should have access to the component factory.

## Steps To Reproduce
1. Set getStaticPaths to output an empty array 
`  return {
    paths: [],
    fallback: 'blocking',
  };
`
4. At the command line, run `npm run start:production`

## Your Environment

* Sitecore Version: 10.2.0
* JSS Version: 20.0.3
* Next.js Version: 12.2.0
* Browser Name and version: n/a
* Operating System and version (desktop or mobile): n/a
* Link to your project (if available): n/a

**Comment by KKings** [comment]
Upgrading to Sitecore JSS version 20.1.3 does resolve the issue as it does appear that between the two versions, the team updated to react's useContext instead

**Comment by illiakovalenko** [comment]
@KKings Thank you for your update, I close this issue, since it's resolved
