### ISSUE TITLE
embedded jss app in Angular

### ISSUE THREAD

**Issue by x1c0** [Sitecore/jss#122]
## Is your feature request related to a problem? Please describe.
No. I would like to know if is possible to have more documentation on `embedded jss app` topic
[https://github.com/Sitecore/jss/tree/dev/samples/sitecore-embedded-jss-app](url)

## Describe the solution you'd like
I would like to know if this is also possible to do using Angular, particulary:
 - What are the steps to do such an embedded-jss-app? Can I use the normal [https://jss.sitecore.com/docs/client-frameworks/angular/angular-overview](url) wiki to build that APP?
- After the app is ready, which considerations do I need to have in account? (e.g. updating package.json scripts, update some sitecore related files)

Thanks in advance!

**Comment by kamsar** [comment]
The embedded app is no different from including the HTML to run any SPA client-side. It should be entirely possible to do using Angular, using similar tactics to how the React embedded app did it. There are currently no plans to document the exact steps to do this for every language.

**Comment by x1c0** [comment]
Alright, I'll try to do it and hopefully it works. Thanks!

**Comment by x1c0** [comment]
I'm also trying this setup in disconnected mode, since I only have a sitecore instance running on the cloud.

After some trial & error, can you please guide me here, this is what I tried so far:

1.  scaffold an JSS app using jss-cli and clean all the unnecessary files (styleguide, graphql)stuff
2. on /data I only have one folder with 1 route data/routes/jss-embebed/en.yml with placeholder and its fields
3. on /sitecore/config/jss-embebed.config I only use this:
` <javaScriptServices>
    <apps>
        <app name="JssEmbebed"
             sitecorePath="/sitecore/content/Home/JssEmbebed"
             appDatasourcesPath="/sitecore/content/Home/$name/Components"
             inherits="defaults"
        />
      </apps>
    </javaScriptServices>`
3. on sitecore/rendering/jssEmbebed/jss-embebed.ascx I have my angular `<app-root></app-root>`

The actual /src folder I'm still not sure how to have it.. I guess for local testing I can use index.html and then, when deploying to sitecore, angular will be bootstrapped from that `jss-embebed.ascx` file with the respective bundles

Thanks in advance!

**Comment by sc-antonkulagin** [comment]
As Kam said we will not be documenting embedding of every framework. Since this evolved into a question, noncompliance with our support policy, please ask question on stack exchange.
