### ISSUE TITLE
Add types for specific fields types.

### ISSUE THREAD

**Issue by maslade** [Sitecore/jss#123]
## Is your feature request related to a problem? Please describe.
The `Text` component expects a field of type `{ value?: string, editable?: string}`, but it doesn't export a definition for this, making it difficult to work with.  If I use the base `Field` type provided in `PlaceholderProps`, the compiler reports the following:

```
[ts]
Type 'Field | Item[]' is not assignable to type '{ value?: string | undefined; editable?: string | undefined; }'.
  Type 'Field' is not assignable to type '{ value?: string | undefined; editable?: string | undefined; }'.
    Types of property 'value' are incompatible.
      Type 'string | number | boolean | { [key: string]: any; } | { [key: string]: any; }[]' is not assignable to type 'string | undefined'.
        Type 'number' is not assignable to type 'string | undefined'. [2322]
```

## Describe the solution you'd like
I would like Sitecore to provide strong types for each of the common field types defined in `sitecore-jss-manifest`, and I'd like the components defined in `sitecore-jss-react` to leverage those. For example, a `SingleLineText` field type that would match the signature that the `Text` component expects in its `field` prop.

Alternatively, if that cross-package dependency doesn't make sense for JSS, I'd like the React components to export their own version of these types so I can leverage those.

## Describe alternatives you've considered
My current solution is to extend the `Field` type from `sitecore-jss` as follows:
```
export interface ITextField extends Field {
  value: string;
  editable?: string;
}
```

**Comment by aweber1** [comment]
Would you be able to provide a code sample that illustrates how the current `TextProps` interface is difficult to work with in the context of the `Text` component? Not trying to be obtuse, just trying to better understand the issue.

**Comment by maslade** [comment]
I just did some digging and learned that I can reference the type of the `field` property using `TextProps['field']`, so the following works:

`
interface ComponentProps {
  fields: {
    heading: TextProps['field'];
  }
}
`

Closing.

**Comment by kamsar** [comment]
Semantically speaking you should not be extending `PlaceholderProps` because a component within a placeholder is not a `Placeholder` component. For example, the `missingComponentComponent` field on `PlaceholderProps` has no meaning on a component within said placeholder.

**Comment by maslade** [comment]
@kamsar I see.  Is there a better alternative available? I'd like to avoid having to define my own types that parallel Sitecore internals.
