### ISSUE TITLE
Embedded sample app requires React 16.3 but references 16.2

### ISSUE THREAD

**Issue by aweber1** [Sitecore/jss#124]
## Description
`sitecore-jss-react` uses the React Context API, which requires at least React 16.3. However, the embedded sample app dependency is `"react": "~16.2.0"`, which causes a runtime error in connected mode (and likely borks up integrated mode as well). 

## Expected behavior

Creating an app from the embedded sample template should run without error.

## Steps To Reproduce

1. Follow steps in JSS documentation for setting up embedded sample (i.e. `jss create my-embed sitecore-embedded-jss-app`; `jss setup`; `jss deploy config`; `jss deploy app -c -d`, `jss deploy-rendering` )
2. Run `jss start:connected`
3. Open browser console, see error similar to `default.createContext is not a function`

## Possible Fix
Update package.json dependencies:
```
"react": "~16.3.0",
"react-dom": "~16.3.0",
```

Can confirm this fixes the issue.

**Comment by kamsar** [comment]
This was fixed in #129
