### ISSUE TITLE
Value cannot be null. Parameter name: tokenProvider

### ISSUE THREAD

**Issue by hitman713** [Sitecore/jss#125]
## Description
After installation of  Sitecore JavaScript Services Server for Sitecore 9.0 11.0.0 rev. 181031 package on Sitecore.NET 9.0.0 (rev. 171002), I proceeded to verify the server components by visiting http://your-sitecore-instance/sitecore/api/layout/render/jss?item=/&sc_apikey=TEST. However it was not showing HTTP Error 400.0 - API key is not valid as specified in the documentation.

## Expected behavior
Verify server components install worked, by visiting http://your-sitecore-instance/sitecore/api/layout/render/jss?item=/&sc_apikey=TEST. The user should receive HTTP Error 400.0 - API key is not valid if it is working correctly.

## Steps To Reproduce
1. Install the JSS Server Components zip package using the Installation Wizard.
2. Modify web config to alter the binding redirect for Newtonsoft.Json.
3. Go to  http://your-sitecore-instance/sitecore/api/layout/render/jss?item=/&sc_apikey=TEST.
4. Displayed server error page.

Value cannot be null.
Parameter name: tokenProvider
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.ArgumentNullException: Value cannot be null.
Parameter name: tokenProvider

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--
[ArgumentNullException: Value cannot be null.
Parameter name: tokenProvider]
   Sitecore.Diagnostics.Assert.ArgumentNotNull(Object argument, String argumentName) +63
   Sitecore.LayoutService.Mvc.Security.ImpersonateJwtTokenUser..ctor(IUserService userService, ITokenProvider tokenProvider, BaseLog log) +90
   System.RuntimeTypeHandle.CreateCaInstance(RuntimeType type, IRuntimeMethodInfo ctor) +0
   System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent) +2074
   System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit) +311
   System.Web.Mvc.CachedDelegates`2.<.cctor>b__0(TMemberInfo memberInfo) +65
   System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory) +87
   System.Web.Mvc.Async.ReflectedAsyncControllerDescriptor.GetFilterAttributes(Boolean useCache) +88
   System.Web.Mvc.<GetFilters>d__0.MoveNext() +135
   System.Web.Mvc.FilterProviderCollection.GetFilters(ControllerContext controllerContext, ActionDescriptor actionDescriptor) +206
   System.Web.Mvc.ControllerActionInvoker.GetFilters(ControllerContext controllerContext, ActionDescriptor actionDescriptor) +55
   System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state) +248
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1c(AsyncCallback asyncCallback, Object asyncState, ExecuteCoreState innerState) +42
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +68
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +166
   System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state) +860
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +166
   System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state) +711
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__4(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState) +93
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState) +68
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout) +166
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state) +502
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +1122
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +213
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +131

## Your Environment
* Sitecore Version: Sitecore.NET 9.0.0 (rev. 171002)
* JSS Version: Sitecore JavaScript Services Server for Sitecore 9.0 11.0.0 rev. 181031
* Browser Name and version: Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

## Screenshots
![image](https://user-images.githubusercontent.com/5619030/51015381-f0c97600-15a6-11e9-9417-571e11b71e3d.png)

**Comment by aweber1** [comment]
JSS requires Sitecore 9.0 update 1 or later. You are using 9.0.0 initial release.

Same question was asked on Sitecore Stack Exchange and a valid answer was provided there:  https://sitecore.stackexchange.com/questions/15950/unable-to-fetch-from-sitecore-layout-service

**Comment by AkshanshDwivedi-V36107** [comment]
The link throws a 404. I am getting this on Sitecore 9.3

**Comment by akshansh1989** [comment]
The stackexchange link throws 404. I am getting this issue on  Sitecore 9.3. Please help

**Comment by nickwesselman** [comment]
@akshansh1989 The Stackexchange question was deleted by the original poster and was basically a repeat of the information here. I don't think that link or this issue is helpful for you on 9.3, this was an issue specific to 9.0. Please open a new issue here or on Stackexchange.
