### ISSUE TITLE
[NextJS] ContentBlock component and manifest live in separated templates

### ISSUE THREAD

**Issue by iamandrewluca** [Sitecore/jss#1257]
## Description

At the moment when creating a NextJS app without StyleGuide or SXA templates, will have a default component created `ContentBlock`, but no Sitecore manifest definition.

When creating a NextJS app with StyleGuide, we have both the `ContentBlock` component and Sitecore manifest definition.

```text
packages/create-sitecore-jss/src/templates/nextjs/src/components/ContentBlock.tsx
packages/create-sitecore-jss/src/templates/nextjs-styleguide/sitecore/definitions/components/ContentBlock.sitecore.ts
```

## Expected behaviour

When creating a NextJS app the `ContentBlock` component and definition should be located in the same template. `nextjs` or `nextjs-styleguide`.

## Steps To Reproduce

Create a NextJS app without any other templates, StyleGuide or SXA

## Possible Fix

Move both component and Sitecore manifest definition in the same template, `nextjs` or `nextjs-styleguide`.

> **Warning**
> If moving the Sitecore manifest definition to the `nextjs` template from `nextjs-styleguide` template, we need also to move there the file `sitecore/definitions/config.js`

> **Note**
> I would commit to making these changes. But don't know exactly in what direction the files should be moved.

**Comment by illiakovalenko** [comment]
@iamandrewluca I would say it's expected, base `nextjs` template doesn't have any items/configuration related to disconnected mode, but `nextjs-styleguide` includes that

**Comment by iamandrewluca** [comment]
@illiakovalenko in this case would make sense to move `ContentBlock.tsx` to `nextjs-styleguide`? 👀

**Comment by illiakovalenko** [comment]
@iamandrewluca It's only one example which we decided to leave in a base template

**Comment by iamandrewluca** [comment]
Ok. Then I can close this issue safely 🙂 Thanks.
