### ISSUE TITLE
JssReactWeb Dictionary Hard Coded into Headless SSR Proxy

### ISSUE THREAD

**Issue by coreyasmith** [Sitecore/jss#127]
## Description
The `JssReactWeb` dictionary is hard coded into the headless SSR proxy's `config.js`:

https://github.com/Sitecore/jss/blob/8d240494470a182754ac9d3870d5ba16465d85f1/samples/node-headless-ssr-proxy/config.js#L140

Any site that uses an app name other than `JssReactWeb` will get a `500` error when trying to browse their site through the proxy. On the server the following is logged:

> FetchError: invalid json response body at https://your.domain/sitecore/api/jss/dictionary/JssReactWeb/en?sc_apikey=%7Ba0fb68a8-ee61-4e2b-8d99-21249dc292c6
%7D reason: Unexpected token U in JSON at position 0

## Expected behavior
`config.js` should use the correct dictionary URL based on the app name in the resolved `serverBundle`.

## Possible Fix
If the server bundle exposes the app name, use that in place of `JssReactWeb` for the dictionary URL in `config.js`.

## Your Environment

* Sitecore Version: 9.1
* JSS Version: 11.0
* Browser Name and version: Google Chrome 71.0.3578.98
* Operating System and version (desktop or mobile): Docker container in Azure

**Comment by kamsar** [comment]
Closing as we'll handle it in the PR.
