### ISSUE TITLE
Sitecore JSS react Image incorrectly bundles react-dom/server

### ISSUE THREAD

**Issue by edqwerty1** [Sitecore/jss#1280]
## Description
When importing the Image component from sitecore-jss-react (in my case a Nextjs application using `import { NextImage } from '@sitecore-jss/sitecore-jss-nextjs';` the client framework bundle incorrectly includes react-dom/server.

This can be seen and proven using webpack analyser.
Before importing NextImage:
![image](https://user-images.githubusercontent.com/5159520/210750145-76d167fe-4fef-4781-850a-a1bf409234ae.png)

After importing NextImage
![image](https://user-images.githubusercontent.com/5159520/210750216-ac3269fc-63e4-4752-bacd-1c4b78a12cbd.png)

As you can see react-dom-server.browser.production.min.js is incorrectly being bundled into the client js.

A result of this bug is anyone using NextImage is getting 22kb of not needed js loaded on every page, which in my case is 15% of my total scripts.

I believe the issue is here: https://github.com/Sitecore/jss/blob/346311c8696ed816c5d067ca1b074785d70cb296/packages/sitecore-jss-react/src/components/Image.tsx#L4

## Expected behavior
Importing NextImage to not bundle react-dom/server

## Steps To Reproduce
1. Import NextImage from sitecore-jss-nextjs
2. Run webpack bundle analyser https://www.npmjs.com/package/@next/bundle-analyzer/v/12.3.4

## Your Environment
* JSS Version: 21.0.2

**Comment by illiakovalenko** [comment]
@edqwerty1 Thank you for your report, we created corresponding tickets in our inbox for the further discussion

**Comment by illiakovalenko** [comment]
@edqwerty1 I closed this issue, since the fix is merged
