### ISSUE TITLE
With multisite enabled in 21.1-canary, the GRAPH_QL_ENDPOINT is required

### ISSUE THREAD

**Issue by larserhardsen** [Sitecore/jss#1291]
## Description
In previous versions before adding the new multisite functionality, it was enough to provide the SITECORE_API_HOST and SITECORE_API_KEY environment variables, and with multisite enabled, the GRAPH_QL_ENDPOINT variable must be filled in, according to the file here:
https://github.com/Sitecore/jss/blob/dev/packages/create-sitecore-jss/src/templates/nextjs-multisite/scripts/config/plugins/multisite.ts

If omitted, the build fails, as the config.graphQLEndpoint is only containing a path.

## Expected behavior
It should be enough to provide SITECORE_API_HOST and SITECORE_API_KEY

**Comment by ambrauer** [comment]
@larserhardsen Thanks for reporting, I've added this to our backlog for further investigation. You are correct, we lost previous dynamic aspects of the config `graphQLEndpoint` prop.

**Comment by ambrauer** [comment]
@larserhardsen This issue is resolved with #1296. Please try with latest canary build.

**Comment by larserhardsen** [comment]
@ambrauer It works! Thanks!
