### ISSUE TITLE
scRichText does not clear text when change to empty string

### ISSUE THREAD

**Issue by rainlake** [Sitecore/jss#1295]
according to this line
https://github.com/Sitecore/jss/blob/27db6b3f982e9277f0b0c4947ea4ca638557e072/packages/sitecore-jss-angular/src/components/rich-text.directive.ts#L45

scRichText directive does not seem to clear text when changed from text to empty.

**Comment by eclipticrick** [comment]
```ts
import { OnInit } from '@angular/core';

@Component({
  selector: 'wl-goat-component',
  template: '<div *scRichText="{ value: richTextValue }"></div>',
})
export class GoatComponent implements OnInit {
  richTextValue = 'Goat';

  ngOnInit() {
    setTimeout(() => {
      this.richTextValue = '';
    }, 5000);
  }
}
```

**Comment by illiakovalenko** [comment]
@eclipticrick Thanks for the details! I will add it to our inbox for the further investigation
