### ISSUE TITLE
Invalid <Link> with <a> child

### ISSUE THREAD

**Issue by thany** [Sitecore/jss#1314]
## Description
In the [Link component source](https://github.com/Sitecore/jss/blob/dev/packages/sitecore-jss-nextjs/src/components/Link.tsx) it is hardcoded with a `<a>` inside the `<Link>` component. There appears to be no way to change/customise how link components are created.

Just to cover my bottom, please be adviced that this is a bug in the sitecore-jss-nextjs package, NOT in the nextjs boilerplate project that is installed as part of a JSS installation into Sitecore, despite using it as an example to illustrate the bug.

## Expected behavior
For Next.js 13, it should NOT include a `<a>` as a child of `<Link>`. 

## Steps To Reproduce

1. Install JSS using the nextjs and nextjs-styleguide boilerplates
2. [Upgrade to Next.js 13](https://nextjs.org/docs/upgrading)
3. Start it
4. Navigate to the styleguide
5. Kaboom

## Possible Fix
This could be done with a switch of some kind, a configuration option somewhere, or anything really that makes it possible to use Next.js as intended. The `<a>` should be removed, and its props and contents moved directly onto/into the `<Link>` component.

## Your Environment

* Sitecore Version: 9.3
* JSS Version: 21.0.5
* Browser Name and version: Firefox 109
* Operating System and version (desktop or mobile): Windows 10 (desktop)
* Link to your project (if available): N/A, still poccing it

## Screenshots
![image](https://user-images.githubusercontent.com/152227/215771081-4989452b-4344-4d0d-b969-7e21ce0a7544.png)

**Comment by thany** [comment]
Currently it goes:
```tsx
      // determine if a link is a route or not.
      if (internalLinkMatcher.test(href)) {
        return (
          <NextLink
            href={{ pathname: href, query: querystring, hash: anchor }}
            key="link"
            locale={false}
          >
            <a
              title={value.title}
              target={value.target}
              className={value.class}
              {...htmlLinkProps}
              ref={ref}
            >
              {text}
              {children}
            </a>
          </NextLink>
        );
      }
```

And it should be something like this:
```tsx
      // determine if a link is a route or not.
      if (internalLinkMatcher.test(href)) {
        return (
          <NextLink
            href={{ pathname: href, query: querystring, hash: anchor }}
            key="link"
            locale={false}
            title={value.title}
            target={value.target}
            className={value.class}
            {...htmlLinkProps}
            ref={ref}
          >
            {text}
            {children}
          </NextLink>
        );
      }
```

**Comment by ambrauer** [comment]
Hi @thany - We don't currently support Next 13, but have plans to in the near future. I've added this to our backlog to make sure it is addressed in the process. Thanks!

**Comment by thany** [comment]
The most obvious followup question thn is, of course: when? 🙂

**Comment by ambrauer** [comment]
@thany Very soon (https://github.com/Sitecore/jss/pull/1324) ☺ Planning to release by March.
