### ISSUE TITLE
Angular Sample App - Hashes in URL result in Page Not Found state in Experience Editor

### ISSUE THREAD

**Issue by AlexKasaku** [Sitecore/jss#132]
## Description

When using the left-hand Styleguide navigation links in the sample Angular app in Experience Editor, pages initially render fine but then switch to the Page Not Found state. This appears to happen with any URL that contains a hash, e.g. `/styleguide#anything`

Having a look at the related JavaScript, this appears to be related to the `activatedRoute` subscription in `layout.component.ts` triggering, but the `jssState` property is null, resulting in `LayoutState` being set to `NotFound`.

Behaviour is fine in Preview mode.

## Expected behavior

For the page to load correctly and navigate to the anchor (if applicable).

## Steps To Reproduce
1. Load styleguide page with an anchor, in experience editor - `/styleguide#ica95a7bb-8841-515c-a8eb-9093b2a31ceb` (ID will vary)
2. Page will initially render fine and then switch to show page not found state.

## Your Environment

* Sitecore Version: 9.1 Initial
* JSS Version:

`@sitecore-jss/sitecore-jss`: 11.0.1
`@sitecore-jss/sitecore-jss-angular`: 11.0.0

* Browser Name and version: Chrome 71.0.3578.98
* Operating System and version (desktop or mobile): Windows 10

## Screenshots

This shows what happens when the response comes back, as seen the initial render is correct but then it switches:

![jss_hash_error](https://user-images.githubusercontent.com/1439631/51245263-0a8c0400-197f-11e9-9254-104309562267.gif)

**Comment by kamsar** [comment]
Fixed in #133
