### ISSUE TITLE
JSS 21 doesn't work with Sitecore 9.3

### ISSUE THREAD

**Issue by thany** [Sitecore/jss#1326]
## Description
Can JSS 21 please be made compatible? Upgrading Sitecore is quite involved (to say the least...) and I don't want the frontend to get "stuck" on a very old version (13.0.0) just because of seemingly quite small issues connecting to Sitecore.

```
Sending package sitecore\package\Site.1675436575912.manifest.zip to https://site/sitecore/api/jss/import...
Unexpected response from import service:
Cannot calculate proper length in synchronous way.
```

## Expected behavior
Should not error out and just work.

## Steps To Reproduce

1. Have a Sitecore 9.3 instance
2. Have a JSS installation
3. Execute a `jss deploy` command

## Possible Fix
The only workaround that I know of, is to downgrade from JSS 21 all the way back to 13:
```
npm i -D @sitecore-jss/sitecore-jss-cli@^13.0.0
```
Which would obviously hinder us from installing any bugfixes or feature improvements that appear in later versions. I consider this a severe degradation of the health of the frontend part of the application.

## Your Environment

* Sitecore Version: 9.3
* JSS Version: 13
* Browser Name and version: Firefox 109
* Operating System and version (desktop or mobile): Windows 10 desktop
* Link to your project (if available): N/A

**Comment by illiakovalenko** [comment]
@thany You can read compatibility table: https://support.sitecore.com/kb?id=kb_article_view&sysparm_article=KB1000576
JSS doesn't support previous Sitecore versions (except of some cases when multiple JSS versions support the same Sitecore version).

**Comment by thany** [comment]
I tried version 21, like I said, and it doesn't work, like I said.

I know it's not compatible, but that's kind of why I'm requesting it to be made compatible, innit.

It boils down to this: can you please make JSS 21 backwards compatible with Sitecore 9.3?

**Comment by thany** [comment]
Sorry, but Sitecore at large is more than expensive enough to expect compatibility. "Available capacity" should be a non-issue.

**Comment by ambrauer** [comment]
Closing this one as it's less a JSS issue as it is a general Sitecore platform challenge - at least on Sitecore Experience Platform where the platform / modules (e.g. Headless Services) may introduce breaking changes that JSS versions are bound to. 

The good news is that this will be less of an issue going forward on Sitecore XM Cloud where the platform is not introducing breaking changes.
