### ISSUE TITLE
NextImage component doesn't compress images

### ISSUE THREAD

**Issue by HighProteinFlapjack** [Sitecore/jss#1355]
## Description
I used the NextImage component to display an image but saw no compression in the image size, while the native NextJs image component produced a dramatic decrease in image size and also returned images in webp format 

## Expected behavior
I would have expected NextImage to produce identical results to the native nextjs Image component e.g. image size / type as I understand it is a wrapper around this component that sets its src property . 

## Steps To Reproduce
```
<NextImage
      field={props.fields.sample2}
      height="105"
      width="200"          
    /> 

<Image src={props.fields.sample2.value?.src} height="105"
      width="200"/>
```

## Your Environment

* Sitecore Version: 10.2
* JSS Version: 20.0.2
* Browser Name and version: Chrome / Edge
* Operating System and version (desktop or mobile): Windows 10 Enterprise

## Screenshots
![image](https://user-images.githubusercontent.com/126251558/221173356-e9f3e88f-d842-4264-bc48-5c25afc294c9.png)

**Comment by illiakovalenko** [comment]
@HighProteinFlapjack  Thank you for your ticket. As far as I can see you are using JSS 20.
We started to use NextImage internally starting from JSS 20.1, see [related PR](https://github.com/Sitecore/jss/pull/978/files#diff-94787a2491b63b1167cab2caf9afa18626d4ca37c062884aa705fc8e7ded343e). Since JSS 20.1 there are also more changes added.
Can you try to test it using JSS 20.1 (or even the latest JSS 21.1)? Please, provide feedback on your results, if you have the same issue - we will investigate that

**Comment by achievecreative** [comment]
I think I have the same issue, I'm trying the following example on my local:

# Your environments:
Sitecore Version: Sitecore XMCloud 1.4.254
JSS Version: 21.1.1
Browser Name and version: Chrome 
https://github.com/Sitecore/XM-Cloud-Introduction

## Hero component:
![image](https://github.com/Sitecore/jss/assets/1118166/3a1320c5-d506-4813-9f78-1b506c45d015)

## Output
![image](https://github.com/Sitecore/jss/assets/1118166/b99c60ab-df29-4542-ba81-23409320d6d8)

**Comment by art-alexeyenko** [comment]
@achievecreative do you see a difference in size between two images too?

**Comment by achievecreative** [comment]
@art-alexeyenko Yes, webP format has smaller size than original one.

![image](https://github.com/Sitecore/jss/assets/1118166/bbc7a1c1-6873-4d50-a7ac-7f75c30f21fb)

**Comment by illiakovalenko** [comment]
@HighProteinFlapjack @achievecreativeI I've added a ticket to our internal backlog, we will investigate this issue

**Comment by mg-aceik** [comment]
@HighProteinFlapjack per the docs you need to [white-list the parameter sets on the server](https://doc.sitecore.com/xmc/en/developers/xm-cloud/media-handler.html). Or you can temporarily disable Media.RequestProtection. 

    <setting name="Media.RequestProtection.Enabled">
      <patch:attribute name="value">false</patch:attribute>
    </setting>
