### ISSUE TITLE
301 is not valid response

### ISSUE THREAD

**Issue by akuryan** [Sitecore/jss#138]
## Description
Sitecore JSS SSR package, when executed on standalone mode at Linux under nginx do not allow backend IIS to respond with 301 status code.

Whenever I send a response which is expected to return 301 I see the following:
```
curl https://webapp/projecT -IL
HTTP/1.1 500 Moved Permanently
Server: nginx
Date: Mon, 21 Jan 2019 11:43:51 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
location: https://webapp/project
feature-policy: accelerometer 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; payment 'none'; usb 'none'
Vary: Accept-Encoding
```

in Node app logs on Linux server I see:
```
Error: Received invalid response 301 Moved Permanently
/node_modules/@sitecore-jss/sitecore-jss-proxy/dist/index.js:264:39
/node_modules/@sitecore-jss/sitecore-jss-proxy/dist/index.js:43:23)
/node_modules/@sitecore-jss/sitecore-jss-proxy/dist/index.js:24:53)
/node_modules/@sitecore-jss/sitecore-jss-proxy/dist/index.js:15:58)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:189:7)
```

## Expected behavior
curl request shall receive correct status (301 instead of 500) and browser shall follow this redirect

## Steps To Reproduce
Make IIS to respond with 301 status code. Example rewrite rule:
```
                <rule name="RedirectToLowercase" stopProcessing="true">
                    <match url="(.*)" />
                    <conditions logicalGrouping="MatchAll" trackAllCaptures="true">
                        <add input="{HTTP_X_Forwarded_Host}" pattern="(.*)" />
                        <add input="{HTTP_X_Forwarded_Path}" pattern="(.*[A-Z].*)" ignoreCase="false" />
                        <!-- do not lowercase requests, which begin with sitecore -->
                        <add input="{HTTP_X_Forwarded_Path}" pattern="^/sitecore" ignoreCase="true" negate="true" />
                    </conditions>
                    <action type="Redirect" url="https://{C:0}{ToLower:{C:2}}" appendQueryString="false" redirectType="Permanent" />
                </rule>
```
Nginx must forward headers to backend; example config:
```
server {
        listen       443 ssl http2;
        listen       [::]:443 ssl http2;
        root         /usr/share/nginx/html;
        ssl_protocols TLSv1.2;
        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
        ssl_prefer_server_ciphers on;
        ssl_dhparam /etc/nginx/ssl/dhparam.pem;
        ssl_certificate /etc/nginx/ssl/crt;
        ssl_certificate_key /etc/nginx/ssl/key;

        location / {
                proxy_pass http://127.0.0.1:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
                proxy_set_header        X-Real-IP          $remote_addr;
                proxy_set_header        X-Forwarded-For    $proxy_add_x_forwarded_for;
                proxy_set_header        X-Forwarded-Host   $host;
                proxy_set_header        X-Forwarded-Server $host;
                proxy_set_header        X-Forwarded-Port   443;
                proxy_set_header        X-Forwarded-Proto  $scheme;
      }
}
```

## Your Environment

* Sitecore Version: 9.0.2
* JSS Version: 11.0.2
* Browser Name and version: Chrome (latest)
* Operating System and version (desktop or mobile): test client: Win 10; Node proxy: CentOS 7; Sitecore host: Windows 2016
* Link to your project (if available): https://p.weareyou.com/

**Comment by akuryan** [comment]
Same issue comes up with 302 response

**Comment by akuryan** [comment]
1. Yes, that  could be treated as a route.
2. In previous sitecore-jss (pre v.11) middleware it was responding to the browser/client with 301/302 redirect - so, that's preferred solution to me.

I tried to make proxy follow redirects, but this fails with following stacktrace:
```
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ClientRequest.setHeader (_http_outgoing.js:498:3)
    at RedirectableRequest.setHeader (/node_modules/follow-redirects/index.js:141:24)
    at ProxyServer.config.proxyOptions.onProxyReq (/index.js:35:12)
    at ProxyServer.emit (/node_modules/eventemitter3/index.js:184:35)
    at RedirectableRequest.<anonymous> (/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:132:27)
    at emitOne (events.js:116:13)
    at RedirectableRequest.emit (events.js:211:7)
    at ClientRequest.eventHandlers.(anonymous function) (/node_modules/follow-redirects/index.js:17:24)
    at emitOne (events.js:121:20)
```

**Comment by Eugenio161288** [comment]
Hello everyone! Faced the same issue with redirects 301/302 status codes. 
The followingRedirects option throws the same exception.

Is there any option/approach to resolve that?

**Comment by Eugenio161288** [comment]
A small update. Looks like the error with **followRedirects** depends on own code in proxy. 

I applied that on exactly the same source code as it was in examples folder for Node proxy(no additional headers, logic etc.). So with enabled **followRedirects option the nginx throws timeout error**. 

Are there any restrictions using that option?

**Comment by aweber1** [comment]
As was discovered earlier in this thread, it seems that using `followRedirects` doesn't work with the current version of the proxy library. We're looking at fixing that in an upcoming release.

**Comment by brianboyko** [comment]
Hello. It is nearly a year later, and I am running into the exact same issue (including the Cant Set Headers After They Are Set message when followRedirects is set to true). Has there been any update to this issue?

**Comment by kvde** [comment]
@aweber1 Hello, is there any progress on this issue?
