### ISSUE TITLE
BUG: Cannot add components to placeholder without saving first

### ISSUE THREAD

**Issue by jeppeskovsen** [Sitecore/jss#141]
## Description
In the Experience Editor when I add a component containing a placeholder, and I try to add a component to that, I get this error:
![image](https://user-images.githubusercontent.com/25830173/51677792-02fdd800-1fdb-11e9-8ebc-f0d2d55b5a55.png)

To make it work, I have to add the component and save. Then I can add components to it's placeholder. It's like it doesn't register that the component I added contains a placeholder until I save.
Will also mention that my list of allowed controls does not work either, when this error occurs.

## Your Environment

* Sitecore Version: 9.1
* JSS Version: 11.0.2

**Comment by sc-illiakovalenko** [comment]
@jeppeskovsen Fixed in #343
