### ISSUE TITLE
Adding display name to component with rendering parameters creates naming conflict

### ISSUE THREAD

**Issue by wrolloff** [Sitecore/jss#148]
### Environment:
Sitecore version: 9.1 (001564)
JSS Version: 11.0.2

### Description of Problem:
If you add a display name to a component with rendering parameters the name generated in JSS code first deployment creates a naming conflict.

Here is a specific example using the JSS React quick start application.

By default, the component "Styleguide-ComponentParams" will generate two templates. The templates are "Styleguide-ComponentParams" for the data template and "Styleguide-ComponentParams Rendering Parameters” for the rendering parameters template. The information looks like this:
* Data Template
    * name: "Styleguide-ComponentParams"
* Rendering Parameters Template
    * name: "Styleguide-ComponentParams Rendering Parameters"
![image](https://user-images.githubusercontent.com/9087210/52168533-0ab33000-26f1-11e9-907b-4a95da9c7cf4.png)

Steps to Reproduce:
1. Add a display name to a component definition (e.g. add display name “Style Guide Component Parameters” to component "Styleguide-ComponentParams”)
2. Deploy the app or items (i.e. jss deploy app —wipe or jss deploy items —wipe)
```
export default function(manifest) {
  manifest.addComponent({
    name: 'Styleguide-ComponentParams',
    displayName: 'Style Guide Component Parameters',
    icon: SitecoreIcon.WindowDialog,
    params: ['cssClass', 'columns', 'useCallToAction'],
    // inherit fields from another template (../templates/Styleguide-Explanatory-Component)
    // inheritance adds fields defined on the base template(s) implicitly to this component
    inherits: ['styleguide-explanatory-component-template'],
  });
```

Results:
* Date Template
    * name: "Styleguide-ComponentParams"
    * displayName: “Style Guide Component Parameters”
* Rendering Parameters Template
    * name: "Styleguide-ComponentParams Rendering Parameters"
    * displayName: "Style Guide Component Parameters"
![image](https://user-images.githubusercontent.com/9087210/52168538-1dc60000-26f1-11e9-91f5-a7098c2e9750.png)

### Expected Results:
The data template and rendering parameters template have different display names.

* Date Template
    * name: "Styleguide-ComponentParams"
    * displayName: “Style Guide Component Parameters”
* Rendering Parameters Template
    * name: "Styleguide-ComponentParams Rendering Parameters"
    * displayName: "Style Guide Component Parameters Rendering Parameters"

**Comment by aweber1** [comment]
This will be addressed in the Sitecore 9.2 release.

In the meantime, you can patch the `ExpandRenderingParametersTemplates` processor of the JSS `import` pipeline.

Patched processor: 
```
using Sitecore.JavaScriptServices.AppServices.Models;
using Sitecore.JavaScriptServices.AppServices.Pipelines.Import;

namespace MyNamespace
{
    public class CustomExpandRenderingParametersTemplates : ExpandRenderingParametersTemplates
    {
        protected override TemplateDef CreateTemplateDefFromRenderingParametersDefs(RenderingDef rendering)
        {
            // If a displayName is defined, add the parameters template suffix so that the displayName
            // doesn't "collide" with the displayName of the rendering dataSource template.
            var displayName = string.IsNullOrWhiteSpace(rendering.DisplayName)
                ? string.Empty
                : $"{rendering.DisplayName}{ParametersTemplateSuffix}";

            var templateDef = base.CreateTemplateDefFromRenderingParametersDefs(rendering);
            templateDef.DisplayName = displayName;
            return templateDef;
        }
    }
}
```

Patch config:
```
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/">
  <sitecore>
    <pipelines>
      <group groupName="javaScriptServices">
        <pipelines>
          <import>
            <processor
              type="MyNamespace.CustomExpandRenderingParametersTemplates, MyLib"
              patch:instead="processor[@type='Sitecore.JavaScriptServices.AppServices.Pipelines.Import.ExpandRenderingParametersTemplates, Sitecore.JavaScriptServices.AppServices']"
            />
          </import>
        </pipelines>
      </group>
    </pipelines>
  </sitecore>
</configuration>
```
