### ISSUE TITLE
JSS GraphQL Impersonation User Access

### ISSUE THREAD

**Issue by piratebriggs** [Sitecore/jss#149]
## Description
I've created a sitecore user (sitecore\JiraAPI) and through the security editor unchecked inheritance from the root of my website node (\sitecore/content/nobbys)

I've check allowed read, write & create on an item underneath this (e.g. /sitecore/content/nobbys/Global/Jira)

Using powershell, I've verified that the user cannot see items under the website root e.g.
```
// Context set to /sitecore/content/nobbys in ISE
Write-Host "extranet\Anonymous"
$anonymous = Get-User -Identity "extranet\Anonymous"
New-UsingBlock (New-Object Sitecore.Security.Accounts.UserSwitcher $anonymous) {
	Get-ChildItem | Format-Table -Property Name, Languages, Children, ID -AutoSize | Out-Default
}

Write-Host "sitecore\JiraAPI"
$anonymous = Get-User -Identity "sitecore\JiraAPI"
New-UsingBlock (New-Object Sitecore.Security.Accounts.UserSwitcher $anonymous) {
	Get-ChildItem | Format-Table -Property Name, Languages, Children, ID -AutoSize | Out-Default
}
```
I then created a JSS API Key that has the impersonation user set to "sitecore\JiraAPI"

I then ran the following GraphQL query using the key created above
```
query ListDatThing {
  item(path: "/sitecore/content/nobbys") {
    id
    name
    children {
      id
      name
    }
  }
}
```
This happily returned the items under /sitecore/content/nobbys

Similarly the following mutation successfully creates items
```
mutation CreateDatThing {
createItem(parent: "/sitecore/content/nobbys",name:"1234", template:"/sitecore/templates/System/Dictionary/Dictionary entry", fields: { name:"Phrase", value:"Find Me!"}) {
    id
    name
  }
}
```

## Expected behavior
I expect the graphql query to be run in the context of the impersonation user and respect Sitecore RBAC

## Your Environment

* Sitecore Version:  9.1.0 (rev. 001564)
* JSS Version: Sitecore 9.1 XM 11.0.0 rev. 181031
* Browser Name and version: Chrome 71
* Operating System and version (desktop or mobile): Win10 Desktop
* Link to your project (if available):

**Comment by piratebriggs** [comment]
Update following revisiting this issue the next morning: It appears that the behaviour is due to there being sitecore authentication cookies in the session as I was logged into the admin in another tab. Running the query incognito works as expected.

My expectation was that the provided keys would be used to impersonate the given user (UserSwitcher style). Maybe some additional documentation could clear this up in future.

**Comment by kamsar** [comment]
This is correct; cookie-based authentication always overrides any impersonation user on an API key. The impersonation user is a default if no authentication is otherwise provided.

**Comment by sc-dawidrutkowski** [comment]
@kamsar Correct me if I'm wrong but base on your and @piratebriggs comments looks like it is default behaviour and it's nothing to be done here. I'm I, right?

**Comment by kamsar** [comment]
Right
