### ISSUE TITLE
useComponentProps returns an error object instead of data

### ISSUE THREAD

**Issue by thany** [Sitecore/jss#1495]
### Describe the Bug

The return value of `useComponentProps` may be the actual data, or an error object. This is bad for typescript, since the generics parameter of useComponentProps dictates a specific return type. This return type is no longer respected when an error is thrown during fetching. Then, the return type is a `{ error: string }` type.

The only way to deal with this right now, is to use ugly ducktyping. Ugly because I am forced to disrepect my own typings there momentarily.

### To Reproduce

Use `useComponentProps` and throw an error in fetching data.

### Expected Behavior

The common way to solve this is for a hook to return two values: the data (if available), and an error object. Like so:

```typescript
const [ data, error ] = useComponentProps<TData>( ... );
```

The signature of `useComponentProps` then being something like:

```typescript
function useComponentProps<ComponentData>(componentUid: string | undefined): [ComponentData | undefined, { error: string }];
```

That way both the data and an error, should one occur, are kept separate and strongly typed.

### Provide environment information

* Sitecore Version: 9
* JSS Version: 21
* Browser Name and version: Firefox 113
* Operating System and version (desktop or mobile): Windows 10

**Comment by thany** [comment]
You could also take a look at [swr](https://github.com/vercel/swr/) for one of numerous React hooks examples that return two different values. Heck, even `useState` is a perfectly good example of this.

**Comment by thany** [comment]
Here's full a workaround:

```typescript
import { useComponentProps as useComponentPropsSitecore } from '@sitecore-jss/sitecore-jss-nextjs';

export const useComponentProps = <TData>(componentUid: string | undefined): [TData | undefined, string | undefined] => {
  const data = useComponentPropsSitecore<TData | { error: string }>(componentUid);
  if (data && typeof data === 'object' && 'error' in data && typeof data.error === 'string') {
    return [undefined, data.error];
  }

  return [data as TData, undefined];
};
```

This is a horrible solution (hence I call it a workaround) and the proper solution is if JSS would blatantly put the wrong data type into the rendering in the first place. So DO NOT copy this over to the actual JSS code, but instead make it so that an error and data are always kept separate while passing data around.

**Comment by art-alexeyenko** [comment]
Thanks for the report @thany . I've put this in our backlog.

**Comment by illiakovalenko** [comment]
@thany We have our internal backlog where we collect GitHub issues/features and prioritize that accordingly
