### ISSUE TITLE
Azure deployment instructions are not up to date

### ISSUE THREAD

**Issue by adoprog** [Sitecore/jss#152]
## Description
Azure deployment instruction at https://jss.sitecore.com/docs/techniques/azure-deployment mentions do not work for deploying JSS on top of Sitecore 9.1

## Steps To Reproduce
1. Deploy Sitecore 9.1
2. Deploy JSS using instructions from the link above

Exception occurs:

New-AzureRmResourceGroupDeployment : 1:12:00 PM - Error: Code=InvalidTemplate; Message=Deployment template validation failed: 'The template parameters '**licenseXml**' in the parameters file are not valid; 
they are not present in the original template and can therefore not be provided at deployment time. The only supported parameters for this template are 'standard, extension, templateLinkBase, 
deploymentId, location, sqlServerFqdn, sqlServerLogin, sqlServerPassword, coreSqlDatabaseName, masterSqlDatabaseName, singleWebAppName, jssMsDeployPackageUrl'. Please see 
https://aka.ms/arm-deploy/#parameter-file for usage details.'.

**Comment by wtamimi** [comment]
Any updates? i'm facing the same issue. Are there any workarounds found? Thanks

**Comment by sc-dawidrutkowski** [comment]
Azure deployment guide has been updated. There should be no issues with deploying the latest Sitecore JavaScript Services 12.0.0 or 11.1.0 to Azure.

**Comment by epetrashen** [comment]
@sc-dawidrutkowski we are still getting the same error deploying Sitecore JavaScript Services 11.1.0 to Azure on top of existing Sitecore 9.1.1 installation. Using Sitecore Azure Toolkit 2.2.0 rev. 190305. Could you please advise?

**Comment by nickwesselman** [comment]
@epetrashen I would recommend submitting a ticket to Sitecore PSS on this.
