### ISSUE TITLE
Recursive Component Factory

### ISSUE THREAD

**Issue by TheFlyingCodeChimp** [Sitecore/jss#153]
Feel free to close, I know this is left basic on purpose and there's even the comment about it! :)

I thought i'd share the component generator change I just tinkered with that fits most of the JS projects I work on, where components are grouped with Major/Minor components and then sub-components that make up those Major/Minor components.

**The Issue** 
Recursive generation of components in the Component Factory

**The limitations** 
Knowing which components are meant to be pushed and which are just component partials.

**The Solution**
Recursively trawl the components, files with matching Folder/File names, or index files in any folder get pushed, otherwise they are ignored.

**The Code**

![image](https://user-images.githubusercontent.com/40811437/52548781-4baaf300-2e1b-11e9-85b9-e2e33fb32e20.png)

**Comment by kamsar** [comment]
I don't think we'd want to add the additional complexity out of the box but this could certainly serve as an example for those wanting to customize the parse behavior - that's why this code is customizable in the first place, to fit team opinions :)
