### ISSUE TITLE
Error: Cannot find module 'fork-ts-checker-webpack-plugin'

### ISSUE THREAD

**Issue by aalibaabaa** [Sitecore/jss#154]
## Description
We installed a demo project for jss react as described in the quickstart:
https://jss.sitecore.com/docs/getting-started/quick-start

```
npm install -g @sitecore-jss/sitecore-jss-cli
jss create my-first-jss-app react
cd my-first-jss-app
jss start
```

This works without problems.
But then we deleted the node_modules and re-installed it (as we always do e.g. for code reviews)

After doing that, starting the app again with `npm start` ends in this error:

```
path or pattern './sitecore/pipelines/**/*.patch.js' did not match any files.
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'fork-ts-checker-webpack-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```

## Expected behavior
App should start by running `npm start` as it did after initial installation

## Steps To Reproduce

1. Install quick start project (see description above)
2. Start project `npm start` -> app starts
3. Stopp app
4. Remove packages `rm -rf node_modules package-lock.json`
5. Re-install packages `npm install`
6. Start app `npm start` => error occurs

## Possible Fix
Update `react-scripts` package to `v2.1.4` (currently the latest stable version)

## Your Environment
* Sitecore Version: 9.1
* JSS Version: 11.0.2
* Node.js: 10.7.0

**Comment by sc-dawidrutkowski** [comment]
I'm closing this one as described behaviour is no longer reproducible.
