### ISSUE TITLE
Multisite only works with 10 sites

### ISSUE THREAD

**Issue by jaredarnofsky** [Sitecore/jss#1565]
### Describe the Bug

The Multisite plugin only returns 10 sites max from the query to build the Sites array in the config.js at build time.

### To Reproduce

To reproduce create 11 sites for a multi site implementation and you will see the 11th is not there.

### Expected Behavior

Expected behavior is the query should return all sites and not just 10.

### Provide environment information

* Sitecore Version: XM Cloud
* JSS Version: 21.1.2
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows 10
* Link to your project (if available):

**Comment by ambrauer** [comment]
@jaredarnofsky Thanks for the information, I've added this to our backlog to fix in a future release.

**Comment by art-alexeyenko** [comment]
@jaredarnofsky I've been testing this with our default implementation and fetching sites from XM Cloud, it appears to work as expected (I tested up to 21 sites so far).
Just as a very basic check - could you double check that you have all the sites published and then rebuild search index to ensure the data is in there?
Could you also describe your setup more (which add-ons do you use, is there any customization to site resolver logic?). It would be best if you can share your JSS project for us to take a look.
