### ISSUE TITLE
[nextjs-sxa] Image component always wraps <img> tag in an <a> tag, even when TargetUrl field is empty

### ISSUE THREAD

**Issue by Elyseum** [Sitecore/jss#1593]
### Describe the Bug

When rendering an _/sitecore/templates/Feature/JSS Experience Accelerator/Media/Image_ with _packages\create-sitecore-jss\src\templates\nextjs-sxa\src\components\Image.tsx_, the <img> is always wrapped in an <a>, even when the TargetUrl field (display name URL) is not configured.
This gives users the assumption the image is clickable, which is not the case.

![image](https://github.com/Sitecore/jss/assets/2812386/a8e95471-3f57-4ef6-87dd-2f43b86a1858)
![image](https://github.com/Sitecore/jss/assets/2812386/12e6ccb8-588a-4e80-bca9-fe4b7a5a8b2b)

### To Reproduce

Render an _/sitecore/templates/Feature/JSS Experience Accelerator/Media/Image_ with _packages\create-sitecore-jss\src\templates\nextjs-sxa\src\components\Image.tsx_ with _TargetURL_ field left empty.

### Expected Behavior

When TargetUrl is empty, the <img> tag should not be wrapped inside an <a> tag.

### Provide environment information

* Sitecore Version: /
* JSS Version: dev
* Browser Name and version: Edge
* Operating System and version (desktop or mobile): /
* Link to your project (if available): /

**Comment by illiakovalenko** [comment]
Close this issue, since PR was merged and fix is provided
