### ISSUE TITLE
Node Proxy: CURL URL -IL returns 500 OK

### ISSUE THREAD

**Issue by Eugenio161288** [Sitecore/jss#160]
## Description
Headless mode, using node jss proxy. Doing requests to the application via browser it returns response with 200 code(as expected).
Doing that request via curl with -IL, it returns 500 OK

`curl URL -IL`

## Expected behavior
The code should be 200 if coming message is OK, not 500

## Steps To Reproduce
1. Use the headless SSR via sitecore-jss-proxy
2. Try to make the following request via curl:
`curl URL -IL`

## Your Environment
* Sitecore Version: 9.0.2
* JSS Version: 11.0.2
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): client: WIn10, Node proxy: Win 10, CentOS 7, Sitecore host: Win 10, Windows 2016

**Comment by sc-illiakovalenko** [comment]
Fixed in [#273](https://github.com/Sitecore/jss/commit/6b4ea5fecc857aa23a2a669a46eaa31fc07b1571)
