### ISSUE TITLE
Sitecore NextJS JSS implementation: Redundant call to CD server on when rendering host receive HEAD request

### ISSUE THREAD

**Issue by mychien1995** [Sitecore/jss#1606]
### Describe the Bug

Hi Team.

We have a Sitecore NextJS JSS + Sitecore XM Solution hosted on Azure App Service.

We recently noticed this behaviour that when our Rendering Host (NextJS) receive a HEAD request (we noticed this since our setup enable Azure Front Door Health Probe), it will still make a GraphQL Request to Sitecore CD Server.

The reason is that in RedirectsPlugin, on every requests received, Rendering Host will still call CD Server to get the Redirect map via the RedirectQuery

This caused unecessary load to the CD server, since the RedirectQuery will trigger Sitecore.XA.JSS.Foundation.Redirects.EdgeSchema.Processors.GetRedirectDataProcessor. This will then trigger a call to item.Axes.GetDescendants, which is a very expensive operation.

Just wondering if anyone else have the same issue as we did, and does Sitecore team have a plan to fix this

### To Reproduce

Setup a NextJS JSS + Sitecore XM implementation. Make a HEAD request via postman to the Rendering Host, you can see that it will make a GraphQL request to Sitecore CD server

### Expected Behavior

The HEAD request should return a 200 response without triggering the CD server

### Provide environment information

* Sitecore Version: 10.3
* JSS Version:
* Browser Name and version:
* Operating System and version (desktop or mobile):
* Link to your project (if available):

**Comment by illiakovalenko** [comment]
@mychien1995 Thanks for the detailed information. We have a ticket in our internal backlog and will work on this issue
