### ISSUE TITLE
Can't search by exact field value (fieldEqual) in GraphQL search-query

### ISSUE THREAD

**Issue by BonNil** [Sitecore/jss#161]
## Description
If one searches by the fieldEqual parameter of the search-query, it will return nothing if you search by exact value. For instance:

search(rootItem: "/sitecore/content/Travel/Data/Ferries" fieldsEqual: {name: "_name" value: "Example"})

would return no results. If however I search by:

search(rootItem: "/sitecore/content/Travel/Data/Ferries" fieldsEqual: {name: "_name" value: "*"})

I will get results, among others my item that has its "_name" value set to "Example".

## Expected behavior
Expected behavour would be that the first query returns the item with the exact "_name" value "Example".

## Steps To Reproduce
1. Create a template with a field, for example "_name".
2. Create an item instance of this template.
3. Add some value to it, for example "Example".
4. Go to your GraphQL-ui and try below query:

{
	search(rootItem: "/sitecore/content/Travel/Data/Ferries" fieldsEqual: {name: "_name" value: "Example"}) {
    results {
      items {
        item {        
          field(name: "_name"){
            name
            value
          }
        }
      }
    }
  }
}

## Your Environment

* Sitecore Version:
* JSS Version: 11.0.2
* Browser Name and version: Chrome 72.0.3626.109
* Operating System and version (desktop or mobile): Windows 10
* Link to your project (if available):

## Screenshots
![wildcard-query](https://user-images.githubusercontent.com/8841428/53305172-5f744180-387e-11e9-927d-979a9fefdb11.PNG)
![exact-query](https://user-images.githubusercontent.com/8841428/53305175-626f3200-387e-11e9-8321-e42543d5b0dc.PNG)

**Comment by sc-dawidrutkowski** [comment]
I'm closing this one as it is no longer reproducible.
