### ISSUE TITLE
Additional hooks/entry points in the Sitecore-Jss-Proxy code to facilitate custom <site> resolution

### ISSUE THREAD

**Issue by boro2g** [Sitecore/jss#163]
## Is your feature request related to a problem? Please describe.
We need to do some extra logic when resolving the <site> entry from the SSR proxy. Currently we can't manipulate the url as freely as we'd like. In our build the 2 scenarios we need to consider are:
- we don't want the url to include the `?sc_lang` param
- we do want to tag on the `?sc_site` param based off some custom rules around host/url (allowing us to mimic the settings we can put into <sites> config in our CD)

## Describe the solution you'd like
The `ProxyConfig.ts` interface has some extra hooks:
```
disableScLangQuerystring?: boolean;
buildUrl?: (request: ClientRequest, url: string, lang: string) => string;
```
which would be implemented in the method `rewriteRequestPath` via:
```
...
let path = `${config.layoutServiceRoute}?item=${encodeURIComponent(
    finalReqPath
  )}&sc_apikey=${config.apiKey}`;

  let disableScLangQuerystring = config.disableScLangQuerystring || false;

  if (lang && !disableScLangQuerystring) {
    path = `${path}&sc_lang=${lang}`;
  }

  if (qs) {
    path = `${path}&${qs}`;
  }

  if (config.buildUrl) {
    path = config.buildUrl(req, path, lang || "");
  }

  return path;
```
## Describe alternatives you've considered
Currently we are doing this via taking a copy of the Sitecore-jss-proxy lib in our own solution. Ideally we could reference the one from NPM and just tweak our implementation of `config.js`

## Additional information
If you are adding extra hooks, another neat one would be to setup logging so it could be delegated (rather than direct to console). If no implementation, do write to console, but otherwise allow plugging into things like appInsights/winston/ANother:
```
//ProxyConfig.ts:
log?: (message: string, key?: string) => void;
```

**Comment by aweber1** [comment]
Closing as there is a larger ongoing refactoring effort for the proxy that will provide more customization options #113 

Related #116
