### ISSUE TITLE
Check props.params for defined by default

### ISSUE THREAD

**Issue by DeathAngelDaemon** [Sitecore/jss#169]
## Is your feature request related to a problem? Please describe.
The initial problem occurs when I changed my JSS app to fit the Sitecore-first workflow. After that I created a Rendering Parameter in Sitecore and wanted to use it in the corresponding JSS component. It led to the error stating that the `props.params` are undefined. I asked in Slack and @kamsar pointed me out that the Layout Service won't return my params until I set a value. That worked but initially there is no value wanted.

## Describe the solution you'd like
I would like to have `props.params` checked for defined by default, so the JSS component works even if there is no value set.

## Additional information
I use JSS version 11.0.2 (with React) and a Sitecore 9.0.1 instance.

**Comment by sc-dawidrutkowski** [comment]
Starting from JSS 13 the params object will be present in the JSON response even if rendering doesn't have parameters assigned yet:

![image](https://user-images.githubusercontent.com/33089653/64604514-99440a00-d3c2-11e9-80b2-ed07cc84cab5.png)
