### ISSUE TITLE
Double digit Dynamic Placeholders are not rendered

### ISSUE THREAD

**Issue by vishalthitegmail** [Sitecore/jss#1736]
### Describe the Bug

Hello team,
We are facing the challenge of generating a dynamic placeholder.
When the dynamic ID generates in double-digit we face an issue that no placeholder is recognized on the page.
The below code is generating a dynamic placeholder for me correctly with Next jS
` <Placeholder name={`accordioncolumn-${index + 1}-{*}`}
                          rendering={_rendering as ComponentRendering}
                        />`

However when index values get to double-digit placeholder does not get generated,

Below is the response from the layout service have the required placeholder.
![image](https://github.com/Sitecore/jss/assets/121997941/0e64c619-7f86-41ce-a6ff-b48833cbeb45)

### To Reproduce

Create the placeholder in loop and pass the dynamic value of index more than 9

` <Placeholder name={`accordioncolumn-${index + 1}-{*}`}
                          rendering={_rendering as ComponentRendering}
                        />`

### Expected Behavior

Placeholder with double-digit should also work and render the added renderings in placeholder
For example
<Placeholder name=`accordioncolumn-10-{*}`  rendering={_rendering as ComponentRendering}  />
<Placeholder name=`accordioncolumn-11-{*}`  rendering={_rendering as ComponentRendering}  />

### Possible Fix

in this file https://github.com/Sitecore/jss/blob/dev/packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx
Excluded params to handle double digits as well
![image](https://github.com/Sitecore/jss/assets/121997941/6daed3fc-d0f7-4052-9777-60effe563111)

### Provide environment information

* Sitecore Version: XM cloud
* JSS Version: 21.5.0
* Browser Name and version: Any browser
* Operating System and version (desktop or mobile): NA
* Link to your project (if available): NA

**Comment by SaintSkeeta** [comment]
Proposed Regex to allow for double digit numbers:-

const EXCLUDE_PLACEHOLDERS_RENDER = [
  new RegExp(/column-(\d{1,2})-\{\*\}/i),
  new RegExp(/row-(\d{1,2})-\{\*\}/i),
];

**Comment by illiakovalenko** [comment]
@vishalthitegmail Thanks for registering this issue! We are exploring this issue

**Comment by illiakovalenko** [comment]
This issue is fixed in #1745
