### ISSUE TITLE
Deploy Command Issue

### ISSUE THREAD

**Issue by vbebins** [Sitecore/jss#176]
## Description
jss deploy app --includeContent --includeDictionary

Getting the following error after I run the deploy command,

Unexpected response from import service:
Status message: Bad Request
Body: Could not find JSS app configuration for 'myfirstjssapp'. Ensure you have included or previously installed a configuration patch file for the JSS app. Running 'jss deploy config' may resolve this.

**My local environment**

![image](https://user-images.githubusercontent.com/49632107/56729245-52dd6e00-6787-11e9-8ffd-893b0db42b25.png)

**Comment by kamsar** [comment]
The error message gives a pretty reasonable course of action. Have you deployed your config?

**Comment by vbebins** [comment]
Hi @kamsar,

Yes, I followed all the steps, but no luck. 

Am I missing any other steps?

But I checked all the steps, it seems no issue. Only the last step has this issue.

**Comment by aweber1** [comment]
As the error message suggests, you need to ensure that your app configuration has been deployed, i.e. `jss deploy config`.

https://jss.sitecore.com/docs/getting-started/app-deployment#step-2-config-deployment

**Comment by vbebins** [comment]
Yes, I deployed already, But it is not working

![image](https://user-images.githubusercontent.com/49632107/56877334-d5b04280-6a7f-11e9-9460-3b283d0741ec.png)

I verified in the include folder, config is already there

**Comment by vbebins** [comment]
> As the error message suggests, you need to ensure that your app configuration has been deployed, i.e. `jss deploy config`.
> 
> https://jss.sitecore.com/docs/getting-started/app-deployment#step-2-config-deployment

I followed all the steps, but no luck. 

![image](https://user-images.githubusercontent.com/49632107/56879922-5aee2400-6a8d-11e9-895f-f51f2117c990.png)

Config is already deployed into include folder.

**Comment by kamsar** [comment]
Ensure the config contains your expected app name within, i.e. `<app name="myfirstjssapp" ...`

**Comment by xiaoyanzheng** [comment]
@

> > As the error message suggests, you need to ensure that your app configuration has been deployed, i.e. `jss deploy config`.
> > https://jss.sitecore.com/docs/getting-started/app-deployment#step-2-config-deployment
> 
> I followed all the steps, but no luck.
> 
> ![image](https://user-images.githubusercontent.com/49632107/56879922-5aee2400-6a8d-11e9-895f-f51f2117c990.png)
> 
> Config is already deployed into include folder.

I also followed the documentation to report this error. Has this problem been solved?

**Comment by xiaoyanzheng** [comment]
> > As the error message suggests, you need to ensure that your app configuration has been deployed, i.e. `jss deploy config`.
> > https://jss.sitecore.com/docs/getting-started/app-deployment#step-2-config-deployment
> 
> I followed all the steps, but no luck.
> 
> ![image](https://user-images.githubusercontent.com/49632107/56879922-5aee2400-6a8d-11e9-895f-f51f2117c990.png)
> 
> Config is already deployed into include folder.

I also followed the documentation to report this error. Has this problem been solved?
