### ISSUE TITLE
Allow config of templating util settings from app directly

### ISSUE THREAD

**Issue by philipbushnell-valtech** [Sitecore/jss#1775]
### What is the improvement or update you wish to see?

In [sitecore-jss-dev-tools/src/templating/utils.ts](https://github.com/Sitecore/jss/blob/dev/packages/sitecore-jss-dev-tools/src/templating/utils.ts#L42) there are settings for finer control over how items are retrieved yet these settings are not configurable beyond their internal usages (e.g. in [sitecore-jss-dev-tools/src/templating/components.ts](https://github.com/Sitecore/jss/blob/dev/packages/sitecore-jss-dev-tools/src/templating/components.ts#L34)). It would be massively helpful if these could be configured from the application directly (e.g. via [generateComponentBuilder](https://github.com/Sitecore/jss/blob/dev/packages/sitecore-jss-dev-tools/src/templating/nextjs/generate-component-builder.ts#L20)).

### Is there any context that might help us understand?

In our app, we have additional co-located files alongside our components (e.g. for testing) but without being able to change the `fileFormat` setting, it fails our build due to it outputting irrelevant files in the generated `componentBuilder` file (and things such as test globals like `describe` are not being explicitly imported so fail).

I've had to `patch-package` a regex setting change to work around this issue but it would be much better to just configure the settings directly in the app (i.e. in `scripts/generate-component-builder/plugins/component-builder.ts`) but I can't.

**Comment by sc-addypathania** [comment]
@philipbushnell-valtech would you like us to provide appropriate documentation for this?

**Comment by philipbushnell-valtech** [comment]
@sc-addypathania what documentation would you provide? Would this just be highlighting the limitation?

**Comment by philipbushnell-valtech** [comment]
@sc-addypathania actually I can see that it needs to be a discussion - I'll close and move it over to there. :)

**Comment by philipbushnell-valtech** [comment]
Moved to https://github.com/Sitecore/jss/discussions/1782
