### ISSUE TITLE
Outdated version of handlebars susceptible to prototype pollution

### ISSUE THREAD

**Issue by nucleausllc** [Sitecore/jss#179]
**Overview**
Versions of handlebars prior to 4.0.14 are vulnerable to Prototype Pollution. Templates may alter an Objects' prototype, thus allowing an attacker to execute arbitrary code on the server.

**Remediation**
For handlebars 4.1.x upgrade to 4.1.2 or later. For handlebars 4.0.x upgrade to 4.0.14 or later.

Detected via [Nucleaus](https://nucleaus.com/?ref=githubsitecore) code scan
![prototype pollution](https://s3.us-east-2.amazonaws.com/nucleaus-east-public/nucleaus/screengrab/sitecore-jss-prototype-pollution.png)

**Comment by sc-illiakovalenko** [comment]
Package is upgraded
