### ISSUE TITLE
Outdated version of just-extend susceptible to prototype pollution

### ISSUE THREAD

**Issue by nucleausllc** [Sitecore/jss#181]
**Overview**
Versions of just-extend before 4.0.0 are vulnerable to prototype pollution. Provided certain input just-extend can add or modify properties of the Object prototype. These properties will be present on all objects.

**Remediation**
Update to version 4.0.0 or later.

Detected via [Nucleaus](https://nucleaus.com/?ref=githubsitecore) code scan
![just-extend prototype pollution](https://s3.us-east-2.amazonaws.com/nucleaus-east-public/nucleaus/screengrab/sitecore-jss-just-extend-pp.png)

**Comment by sc-illiakovalenko** [comment]
Package is upgraded
