### ISSUE TITLE
Outdated version of tar susceptible to Arbitrary File Overwrite

### ISSUE THREAD

**Issue by nucleausllc** [Sitecore/jss#182]
**Overview**
Versions of tar prior to 4.4.2 are vulnerable to Arbitrary File Overwrite. Extracting tarballs containing a hardlink to a file that already exists in the system, and a file that matches the hardlink will overwrite the system's file with the contents of the extracted file.

**Remediation**
Upgrade to version 4.4.2 or later.

Detected via [Nucleaus](https://nucleaus.com/?ref=githubsitecore) code scan
![arbitrary file overwrite](https://s3.us-east-2.amazonaws.com/nucleaus-east-public/nucleaus/screengrab/sitecore-jss-arbitrary-file-overwrite.png)

**Comment by sc-illiakovalenko** [comment]
Package is upgraded
