### ISSUE TITLE
Outdated version of webpack-bundle-analyzer susceptible to cross-site scripting

### ISSUE THREAD

**Issue by nucleausllc** [Sitecore/jss#183]
**Overview**
Versions of webpack-bundle-analyzer prior to 3.3.2 are vulnerable to Cross-Site Scripting. The package uses JSON.stringify() without properly escaping input which may lead to Cross-Site Scripting.

**Remediation**
Upgrade to version 3.3.2 or later.

Detected via [Nucleaus](https://nucleaus.com/?ref=githubsitecore) code scan
![cross site scripting](https://s3.us-east-2.amazonaws.com/nucleaus-east-public/nucleaus/screengrab/sitecore-jss-webpack-css.png)

**Comment by sc-illiakovalenko** [comment]
Packaged is updated
