### ISSUE TITLE
Outdated version of braces susceptible to regex DOS

### ISSUE THREAD

**Issue by nucleausllc** [Sitecore/jss#184]
**Overview**
Versions of braces prior to 2.3.1 are vulnerable to Regular Expression Denial of Service (ReDoS). Untrusted input may cause catastrophic backtracking while matching regular expressions. This can cause the application to be unresponsive leading to Denial of Service.

**Remediation**
Upgrade to version 2.3.1 or higher.

Detected via [Nucleaus](https://nucleaus.com/?ref=githubsitecore) code scan
![regex DOS](https://s3.us-east-2.amazonaws.com/nucleaus-east-public/nucleaus/screengrab/sitecore-jss-regular-dos.png)

**Comment by sc-illiakovalenko** [comment]
Resolved in JSS 15
