### ISSUE TITLE
Change port number cause project crash

### ISSUE THREAD

**Issue by hamed-farag** [Sitecore/jss#185]
## Description
Trying to change application port by adding a key called **port** at .env file and run the JSS app in disconnected mode, the site launched in the browser with the new port but with an errors 

## Expected behavior
JSS App should run normally with the new port.

## Steps To Reproduce
1. create new jss by **jss create app_name react**
2. create env file **.env**
3. Add key **PORT=3025**
4. jss start

## My Environment
* Sitecore Version: Sitecore Server Not available, working in disconnected mode
* JSS Version: 11.0.2
* Browser Name and version: Chrome v. 73
* Operating System and version (desktop or mobile): Windows 10 desktop

## Screenshots
![image](https://user-images.githubusercontent.com/5382471/57185281-9bec9b00-6ec8-11e9-8a37-0b8e09d647ea.png)

**Comment by aweber1** [comment]
The JSS sample React app doesn't use `.env` files for environment variable configuration. You'll need to adjust your `start` script in `package.json` like so:

```
"start": "cross-env-shell PORT=3025 \"npm-run-all --serial bootstrap:disconnected --parallel start:react start:proxy start:watch-components\"",
``` 

This will ensure that the disconnected mode bootstrap script (`scripts/bootstrap.js`) uses the desired PORT and that the create-react-app startup scripts use the desired port.
