### ISSUE TITLE
Getting Started docs don't mention import service URL question

### ISSUE THREAD

**Issue by nickwesselman** [Sitecore/jss#186]
## Description
The Getting Started documentation doesn't mention the Import Service URL question.
https://jss.sitecore.com/docs/getting-started/app-deployment

## Expected behavior
The question should be mentioned, along with an indication that it should probably just be left blank. Or perhaps the question should be removed altogether, and require manual editing to change the import service URL?

## Screenshots

![image](https://user-images.githubusercontent.com/27013789/57226777-bcf2e000-6fdd-11e9-98ff-644656f726aa.png)

**Comment by sc-illiakovalenko** [comment]
Added in #359
