### ISSUE TITLE
"jss setup" command arguments validation for CI

### ISSUE THREAD

**Issue by vitaliitylyk** [Sitecore/jss#187]
## Description

The `jss setup` command allows to specify the `apiKey` parameter. This parameter is validated to be a valid Guid, which is fine for local setups, but for CI builds one might want to specify a tokenized value, e.g. `#{ApiKey}`, which would later be replaced during deployment process.

So the intent is to produce an environment-agnostic package with tokenized parameters.

## Suggested solution
Please consider transorming a validation to cause a warning, instead of an error or add a flag to be able to surpress the parameters validation.

## Alternatives
As discussed in Slack, an alternative to running the `jss setup` command during the build process would be to create a specific version of the _scjssconfig.json_ file with tokenized values and use it during CI builds. This is also a perfectly valid option, although requires some extra work and maintainance of the file.

**Comment by aweber1** [comment]
Agreed that the GUID validation should be removed, as API Keys may not always be GUIDs, e.g. if a custom API Key resolver is used.

**Comment by aweber1** [comment]
Implementation notes:

Remove the `validation` and `validationMessage` arguments, also update the `examplePrompt` argument text to something like: `(Usually the ID of an API key item)`
https://github.com/Sitecore/jss/blob/d84494b14dce4bd0a6bec40e6efc189b3cc13538/packages/sitecore-jss-dev-tools/src/setup/setup.ts#L177

Change the CLI help verbiage to something like: 
`Sitecore API Key (usually the GUID of an item under /sitecore/system/Settings/Services/API Keys/ in master db, or core db for Sitecore 9.0. However, may also be a custom API key or tokenized value for replacement during CI)`

https://github.com/Sitecore/jss/blob/d84494b14dce4bd0a6bec40e6efc189b3cc13538/packages/sitecore-jss-cli/src/scripts/setup.ts#L29

**Comment by adoprog** [comment]
@aweber1 Another option is to allow **skipValidationIfNonInteractive** parameter for **apiKey**. I assume for CI we would pass just pass command line parameters anyway, and it's good to have validation for those who use it interactively.

**Comment by adoprog** [comment]
Or even add another parameter **skipValidation** as tokenization might be useful for hostname and Sitecore import params, etc..

**Comment by sc-illiakovalenko** [comment]
@vitaliitylyk ,@aweber1 , @adoprog  Added in https://github.com/Sitecore/jss/commit/749d836291ffaaff9631596e3e2dd37361918bd6
Now not released
