### ISSUE TITLE
Unable to configure url prefix ( Non-alignment with sitecore)

### ISSUE THREAD

**Issue by RashmiSrinivas1** [Sitecore/jss#193]
## Is your feature request related to a problem? Please describe.

Currently from (jss/packages/sitecore-jss/src/mediaApi.ts) we have a regex:
```sh
// finds the Sitecore media URL prefix
const mediaUrlPrefixRegex = //([-~]{1})/media//i;
```

This Url prefix is configurable in Sitecore but not from jss as it is hardcoded in the regex pattern. Would it be possible to make these Url prefix configurable?

## Describe the solution you'd like
I should be able to configure the urls and handle the request appropriately as we handle in Sitecore.

Ex: We should be handle /-assets/

## Describe alternatives you've considered
We are currently looking at the options to resolve this issue: 
1. Fork and amend the existing code ? 
2. Rewrite the url to handle the requests? 

## Additional information
N/A

**Comment by sc-illiakovalenko** [comment]
@RashmiSrinivas1 Feature added in #419 
You will have ability to use `mediaUrlPrefix` in the `Image` component, in all frameworks.
```
  /**
   * Custom regexp that finds media URL prefix that will be replaced by `/-/jssmedia` or `/~/jssmedia`.
   * @example
   * /\/([-~]{1})assets\//i
   * /-assets/website -> /-/jssmedia/website
   * /~assets/website -> /~/jssmedia/website
   */
```
