### ISSUE TITLE
ComponentQuery field (on JsonRendering) is not shared

### ISSUE THREAD

**Issue by alexshyba** [Sitecore/jss#196]
## Description

The `ComponentQuery ` field on JsonRendering that is used to store the integrated graphql query is not shared as majority of other rendering configuration related fields. It is a problem on multi-lingual systems requiring creation of the rendering definition item for each language. Without it the integrated query doesn't execute.

## Expected behavior

This field has to be shared :)

## Possible Fix

Make the "ComponentQuery" field shared.

## Your Environment

* Sitecore Version: 9.1.1
* JSS Version: 11
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows 10
* Link to your project (if available):

## Screenshots

![image](https://user-images.githubusercontent.com/900910/58655457-f5c96080-82ce-11e9-8f7b-3a385debf748.png)

**Comment by sc-dawidrutkowski** [comment]
The ComponentQuery field will now be shared (the change was done in Sitecore.JSS.Server project).
