### ISSUE TITLE
Angular lazy loading with slow connection shows empty page

### ISSUE THREAD

**Issue by spike1292** [Sitecore/jss#197]
## Description

When navigating to a route with lazy loaded components the `sc-placeholder` will show a empty block.

## Expected behavior

Ability to provide a loading/placeholder component during lazy loading 

## Steps To Reproduce

1. create route with lazy loaded components
2. set chrome dev tools to ![chrome dev tools](https://user-images.githubusercontent.com/288597/58892224-20ac1e00-86ee-11e9-88e2-84bd8393798f.png)
3. route to page with lazy loaded components

## Your Environment

* Sitecore Version: 9.0.1
* JSS Version: 11.0.2
* Browser Name and version: every browser with slow connection
* Operating System and version (desktop or mobile): n.a.

## Screenshots

![Sitecore JSS angular lazy load bug](https://user-images.githubusercontent.com/288597/58891771-687e7580-86ed-11e9-9dd9-bede584d2923.gif)

**Comment by sc-dawidrutkowski** [comment]
Fix has been merged.
