### ISSUE TITLE
Checkbox field defined as param field doesn't import into sitecore correctly

### ISSUE THREAD

**Issue by chaturangar** [Sitecore/jss#202]
## Description
I have defined a Param fields for JSS component as below and set its value to "true" on the route file.

But when imported into Sitecore, in the presentation details of the component doesn't show this "greyBackground" checkbox as checked.

params: [
      { name: 'greyBackground', displayName: "Grey Background", type: CommonFieldTypes.Checkbox }
]
route file :-

componentName: MyComponent
        params:
          greyBackground: true

## Expected behavior
When imported, Sitecore item's presentation details should show Parameter checkbox Checked

## Steps To Reproduce
1. Create a component with Checkbox field as a param
2. set param value to 'true' in route/yml file
3. Import it to sitecore by running jss deploy app -c -d
4. Open content editor of the item and see Parameters for this component

## Possible Fix
When we use 0/1 (instead of true/false) for the param fields in routes/yml definition, it works correct

## Your Environment
* Sitecore Version: 9.0.2 (rev. 180604)
* JSS Version: 11.0.1
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows 10

**Comment by sc-dawidrutkowski** [comment]
Import of checkbox fields is working fine on Sitecore JavaScript Services 12.0.0. `true` and `false` values are properly reflected in the checkbox fields after import. I'm closing this issue.
