### ISSUE TITLE
Sitecore JSS :: Presentation Layer (with personalized content) of related items/child items

### ISSUE THREAD

**Issue by AmitKumar-AK** [Sitecore/jss#205]
## Is your feature request related to a problem? Please describe.

The Use case details mentioned in the file Sitecore JSS-Personalized Child Content.pdf and created the Sitecore Support Ticket#**533250** for this request also and tried the suggested steps but not able to achieve the use case.

**Use case details:** [Sitecore JSS-Personalized Child Content.pdf](https://github.com/Sitecore/jss/files/3308924/Sitecore.JSS-Personalized.Child.Content.pdf)

The details of suggested steps with ERROR details mentioned at [SitecoreSupportTicket-533250-CustomContentResolver-Update.pdf](https://github.com/Sitecore/jss/files/3308926/SitecoreSupportTicket-533250-CustomContentResolver-Update.pdf)

## Describe the solution you'd like

I required Listing of related items/child items on Product Item page with personalized content of Hero image/Promo component added on the respective related/child items.
## Describe alternatives you've considered

I tried to use the classes Sitecore.JavaScriptServices.ViewEngine.Presentation.JsLayoutRenderer (ResolveFunctionArgs() and RenderItem() methods) Sitecore.LayoutService.ItemRendering.LayoutService (Render() method) from my side but getting Elements of Child/Related Items Placeholder as zero and **also only one Placeholde**r is coming.
## Additional information

While accessing the Render method for child item (Related Doctors > Selected Multi list > item1), I am passing RenderOptions as null to get the actual item layout details (child item layout details) otherwise if I will pass child item in the GetLayoutServiceRenderOptions method then it will return current item’s RenderingContext.Current.Rendering.

**One more error** I encountered during the debugging while using Layout related code
IList<RenderedPlaceholder> placeholders = renderedItem.Placeholders = PlaceholderService.RenderPlaceholders(placeholderDefinitions, renderingConfiguration);
Error details mentioned at [SitecoreSupportTicket-533250-CustomContentResolver-Update.pdf](https://github.com/Sitecore/jss/files/3308926/SitecoreSupportTicket-533250-CustomContentResolver-Update.pdf)

**Comment by AmitKumar-AK** [comment]
Wrongly closed.

**Comment by kamsar** [comment]
Personalization is a feature of rendering an item's layout. If you want the personalized layout of a child item, you would need to make layout service requests for those child items in addition to the parent. The act of rendering the personalized layout is tied together with the request pipeline, so it is not possible to render more than one layout per request to layout service.

**Comment by sc-dawidrutkowski** [comment]
@AmitKumar-AK Base on above I'm closing this issue.
