### ISSUE TITLE
"fetcher is not a function" - React

### ISSUE THREAD

**Issue by MikyStar** [Sitecore/jss#212]
## Description
After having wired up my React JSS to my Sitecore instance, I tried fetching data from it like [the documentation](https://jss.sitecore.com/docs/fundamentals/services/layout-service) said but I encountered an error "TypeError: fetcher is not a function" within **node_modules/@sitecore-jss/sitecore-jss/dist/dataApi.js:90**.

## Expected behavior
Feteching datas from my Sitecore instance.

## Steps To Reproduce
Nothing more than a default HelloWorld React app made with 
```sh
jss create my-first-jss-app react
```
Then I added a basic React class component and added the very same lines (different token though) as the documentation within a componentDidMount function.

## Your Environment
* Sitecore Version: 9.0.1
* JSS Version: 11.0.2
* Browser Name and version: Chrome 75.0.3770.100 (Build officiel) (64 bits)
* Operating System and version (desktop or mobile): MS Windows Server 2016 (10.0.14393)

**Comment by kamsar** [comment]
The React default fetcher is defined [here](https://github.com/Sitecore/jss/blob/dev/samples/react/src/dataFetcher.js) and then passed into the layout data api [here](https://github.com/Sitecore/jss/blob/b41311b2aa8ed885a4d6d1d3d030da6e3496515b/samples/react/src/RouteHandler.js#L204). The fetcher allows you to customize the library used to make HTTP calls to Sitecore.

It sounds like your fetcher is null or not a function in the `RouteHandler.js`.

**Comment by MikyStar** [comment]
Am I supposed to implement it on my side?

**Comment by kamsar** [comment]
No, it should be wired up out of the box and work fine. But that is the mechanism you seem to be having trouble with so I'm trying to point you to the right places to be troubleshooting the problem.

**Comment by MikyStar** [comment]
I checked that my setup provides the same code as you pointed me to and it does 
I tried reinstalling my node_modules but the error is still there

**Comment by MikyStar** [comment]
It seems like the dataApi.js file is expecting me to provide a fetcher attribute inside the fetchOptions object described in the documentation page linked above, however it doesn't speaks about it

**Comment by sc-antonkulagin** [comment]
@MikyStar  This issue was described by merging #306. If you feel that additional information is needed, feel free to reopen this issue or create a new one.
