### ISSUE TITLE
Logged-in User Personalization including Virtual user and Sitecore Contact using Sitecore JSS

### ISSUE THREAD

**Issue by AmitKumar-AK** [Sitecore/jss#217]
## Description

I am having requirement to show personalized content for Logged-in user (external system) which have default persona attached to user profile and after logged-in need to show personalized content on the basis of default mapped user persona.

For example, 2 persona presents like A and B in Sitecore, and user mapped to persona A in CRM side, so content related to Persona A needs to be shown always after logged-in, not Persona B (persona needs not be changed while user active on site).

Sitecore persona's already created and Content also mapped. For annonymous user I already verified both the personas in Sitecore JSS app and it's working fine.

After authenticating with external IAM system created the virtual user for authenticated user

## Expected behavior

I am expecting that, if i will use OOTB Personalization rule  “where the user profile includes a valid email address” on any component then it should show Personalized content.

## Steps To Reproduce

1. Create a Login button in JSS app, which call custom controller.
2. In custom controller create virtual user.
3. Now setup OOTB Personalization rule  “where the user profile includes a valid email address” on any component.
4. After login, traverse to page where personalization rule added and verify that content changing or not.

## Possible Fix

1. Create virtual user with Sitecore contact (includes email address).
2. Set the default presona coming from the CRM into custom facets of Sitecore contact.
3. Create custom personalization rule, which will check that value present in the Custom facet or not, if present then user logged-in other wise not.
4. In other custom personalization rule, check persona value coming from CRM and on the basis of that conditional rendering of content for personalization.

## Your Environment

* Sitecore Version: Sitecore.NET 9.1.0 (rev. 001564)
* JSS Version: Sitecore JavaScript Services Server for Sitecore 9.1 XP 11.0.0 rev. 181031
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows 10 (Desktop)
* Link to your project (if available):

## Additional information

**Sitecore Stack Exchange url for issue:** https://sitecore.stackexchange.com/questions/18616/logged-in-user-personalization-including-virtual-user-and-sitecore-contact-using

**Comment by sc-dawidrutkowski** [comment]
@AmitKumar-AK This is quite an old issue and it might be hard reproducing it on our site because you are mentioning "custom code". If you are still facing this problem please try debugging custom controller resolver in order to inspect the user context and somehow correlate it with the "user has an email address" rule.
If this won't help then please create a new refreshed ticket with update information and steps to reproduce which do not require us to know your custom code.
