### ISSUE TITLE
[Angular] use Object.entries instead of Object.keys().foreach()

### ISSUE THREAD

**Issue by jlast** [Sitecore/jss#220]
In the angular link directives:
`*scLink`
`*scRouterLink`
`*scGenericLink`

Instead of `Object.keys().foreach() `we would rather use Object.entries, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries

tslib is set on es2017 so entries should be available , https://github.com/Sitecore/jss/blob/dev/packages/sitecore-jss-angular/tsconfig.json

The reason to change is this is because `Entries` are way more flexibel than `keys`.

**Comment by sc-dawidrutkowski** [comment]
Done in #274
