### ISSUE TITLE
search by GraphQL API  use language warn

### ISSUE THREAD

**Issue by huanyuxiaoxiao** [Sitecore/jss#227]
Query conditions include language, but the returned information is contained in English
search shell:
{
  item(path: "{AA982584-7F5D-4B44-A27F-1F06141CD6F1}", language: "zh-CN") {
    name
    language {
      name
    }
    ... on AboutHotelOverview {
      pageTitle {
        editable
      }
      aboutHotelContentList {
        targetItems {
          ... on AboutHotelContentItem {
            language {
              name
            }
            title {
              editable
            }
          }
        }
      }
    }
  }
}
result:
{
  "data": {
    "item": {
      "name": "Your Shangri-La Story",
      "language": {
        "name": "zh-CN"
      },
      "pageTitle": {
        "editable": "chinese"
      },
      "aboutHotelContentList": {
        "targetItems": [
          {
            "language": {
              "name": "en"
            },
            "title": {
              "editable": ""
            }
          },
          {
            "language": {
              "name": "en"
            },
            "title": {
              "editable": "english"
            }
          }
        ]
      }
    }
  }
}
pageTile is Chinese content, but "aboutHotelCountentList->title" is English Content

The installed version:
Sitecore JavaScript Services Server for Sitecore 9.0 11.0.0 rev. 181031
Sitecore.NET 9.0.2 (rev. 180604)
June 04, 2018
.NET Framework 4.0.30319.42000

How to solve this problem?
thank you

**Comment by kamsar** [comment]
This issue is directly related to the JSS server components that are supported by Sitecore Support. Please submit a support ticket (support.sitecore.net) to track this issue; I have also passed the information along internally for review.
