### ISSUE TITLE
Components with Data Fields + GraphQL Query only returns GraphQL

### ISSUE THREAD

**Issue by kars-springbok** [Sitecore/jss#228]
## Description

I have a component with Data Fields and a linked GraphQL Query (GraphQL Query added trough Sitecore).

However in my front end only the result of my graphql query is passed and my data fields are nowhere to be found.

## Expected behavior

The fields props should pass my graphql results + data fields result.

## Steps To Reproduce

1. Create a component with a text data field
2. Add a graphql query to the rendering
3. Check the props that are passed to the component
4. Now you see fields: { data: {}}, only containing the results of the graphql query. The data fields (in this case the text data field) are not passed.

## Your Environment

* Sitecore Version: 9.1
* JSS Version: 11.0.2
* Browser Name and version: Chrome 76.9.3809.87
* Operating System and version (desktop or mobile): Mac OS Mojave Desktop
* Link to your project (if available): Can't publicly give it

**Comment by kamsar** [comment]
Using a GraphQL query overrides the standard datasource, so both will not be returned.

Selecting the `jss` property on fields in the GraphQL query will result in the identical field values as would be returned by the standard item serialiser, which can be used directly by field components.

**Comment by kars-springbok** [comment]
Aah that explains a lot! Thanks for the input. I can continue now.
