### ISSUE TITLE
Change default Project URL?

### ISSUE THREAD

**Issue by hamed-farag** [Sitecore/jss#229]
Is it available using configuration or option into CLI command to change URL http://localhost:3000 to for example http://localhost:3000/app/home ? I want to change the default page

**Comment by sc-illiakovalenko** [comment]
@hamed-farag Can you specify sample app, in which you want to do it?

**Comment by hamed-farag** [comment]
@sc-illiakovalenko, after some investigation and read create-react-app documentation well, to change the default app's URL (`http://localhost:3000`) to whatever URL, for example (`http://localhost:3000/app/home`), you need to set `homepage` element at package.json as following 
```
{
  "name": "project",
  "version": "0.1.0",
  "homepage": "/app/home/",
  ....
```
That was my problem 😄
