### ISSUE TITLE
Version docs

### ISSUE THREAD

**Issue by anastasiya29** [Sitecore/jss#238]
## Description of issue
As we update the docs to reflect the current, most recent JSS version, anyone who is on an older version could be looking at incorrect information. 

## Proposed solution
I like the way Angular docs handles this. They have a toggle in their docs site which lets you switch between versions, and as you switch versions, the entire domain changes. They are using the Netlify feature that lets you deploy different branches independently.

Could we do the same thing with Heroku? Since we have tags for every release, we could deploy the docs from each release tag, and thereby have a "living version" of the doc site for every release.

**Comment by kamsar** [comment]
Bonus points for prerendering the whole thing and actually using Netlify ;)
