### ISSUE TITLE
Installing JSS CLI over existing React Project

### ISSUE THREAD

**Issue by sowhatdoido** [Sitecore/jss#24]
I took a look at your basic example package.json, and it looks like you have prettier and eslint pre-configured, which might conflict with the rules we've already set up.

I figure I could do it manually by hand picking the packages and files needed to run React + JSS, but I'm not entirely sure the bare minimum that I should import.

What is the simplest and opinionated set up that you can get going with jss-cli? Do you support adding to an existing project, or would we have to generate a new project via the CLI tool and port our code over?

Thanks for your help!

**Comment by sitecorian** [comment]
Hello, thanks for reporting this. Good point, I agree we should provide more guidance if you don't want to start with either of the samples. Added a doc request for that.

Since there are hundreds of ways to configure your JS project, our initial thinking was to show how you _can_ configure it and leave it to the front-end dev to re-configure as they see fit.

I think the choice would depend on this factor.
Are you planning on having alternative build tool chain setup to what is provided in `basic-sample-react`?

If what `basic-sample-react` provides in terms of the project setup matches your expectation, then adding your react components into that sample is the easiest way to get started.

**Comment by sowhatdoido** [comment]
The use case I was thinking of here was that I'm maintaining my own fork of create-react-app with the various lints and plugins that our team was going to use across all our projects - including non-sitecore ones. We wanted to use this approach to standardize all of our projects so that we could avoid having developers eject and manually updating things as we roll out version bumps or standard changes.

So essentially, my ideal situation would be creating a CRA app through that command line tool first, then adding JSS on top. I figure it could be something like adding a package or running the jss-cli to add an even more stripped down template that only provides the build and deploy logic, none of extra lint rules or other opinionated items that might be in the basic template. 

A more manual approach would be identifying what scripts and packages I would be able to add to my existing project. For example, you could say I need to add the following the my package json:
```
    "@sitecore-jss/sitecore-jss-cli": "^7.0.2",
    "@sitecore-jss/sitecore-jss-dev-tools": "^7.0.0",
    "@sitecore-jss/sitecore-jss-manifest": "^7.0.0",
```
as well as the so and so files and folders from the sample project.

Please let me know what you think.  Thanks again for your help - we're in the early planning phases of adopting JSS in our workflow and we're really excited about your work.

**Comment by kamsar** [comment]
The scenario you want is not currently supported as CRA doesn't ship with some of the core needs of JSS (specifically SSR, without which no experience editor). We're investigating options to make JSS more friendly towards CRA in the future.

**Comment by sowhatdoido** [comment]
What if you started a project out of CRA and ejected - what would you have to add to the project to get it connected to JSS?

**Comment by kamsar** [comment]
The short version is "a lot, enough that I wouldn't recommend starting with a CRA app."

The core reason why is that CRA's build process is designed around a client-rendered app. JSS requires server-side rendering support. While that [is possible](https://medium.com/bucharestjs/upgrading-a-create-react-app-project-to-a-ssr-code-splitting-setup-9da57df2040a) you'd have to restructure the app and maintain a parallel Babel build process to build a server bundle (so half ejected already). JSS SSR also relies on a structure where an exported function is invoked, as opposed to most SSR examples where they start an Express server to perform the SSR.

Then the JSS disconnected infrastructure depends on adding middlewares to `webpack-dev-server` (`/build/start.js`) to make disconnected services work. CRA can handle proxying - and we may consider using this in the future - but that also means standing up a separate `express` instance on a second port for WDS to proxy to, and more build infrastructure to support that.

The final aspect to work through is the need to inject configuration. JSS is using `DefinePlugin` to inject global JS variables (`/build/webpack/webpack.shared.js::getGlobalVariables()`). To support CRA, either a pre-build task would need to generate a .js file to import (JSS angular does this), or something like [rewire](https://www.npmjs.com/package/react-app-rewire-define-plugin) would need to be used.

It would be nice to support CRA or other custom apps as a starting point, but especially short term your best bet is going to be to merge webpack configurations and use the JSS build infrastructure.

**Comment by kamsar** [comment]
For what it's worth, we will have a story using create-react-app, but it will be a sample boilerplate as opposed to being designed to bolt-on to any CRA implementation. With some automation, it could probably be turned into a bolt-on, but we are not planning to ship that.
