### ISSUE TITLE
Select Box

### ISSUE THREAD

**Issue by kars-springbok** [Sitecore/jss#245]
## Is your feature request related to a problem? Please describe.

Currently we have components already in Sitecore, that we want to switch to JSS components. However they have selection fields, in this case, Theme selection, light or dark.

## Describe the solution you'd like

We would like to see the functionality to add a selection field to JSS components. This way it's easier for webmasters to select options for components. A component for instance can have multiple styles/button styles. With a simple select field they can easily modify this without the need of a developer. Or that we have to make almost duplicate components for a slight difference. 

## Describe alternatives you've considered

Checkboxes and single line text fields (allowing the user to type 0, 1, 2 and we parse the number in the component to render the output. However both with checkboxes and single line text fields, we cannot enforce the user the select one item. Or we need to add a lot of description to it, to make clear to the webmaster what the 0, 1 and 2 do etc.

## Additional information

![Screenshot 2019-09-02 at 09 53 58](https://user-images.githubusercontent.com/42574769/64098603-9b292000-cd67-11e9-9b71-efc7f7cc2cfd.png)

I would like to able to create options as seen on the screenshot. This would allow us to create really robust components that give some power and control to the webmasters to alter small things. Such as padding medium, large etc. Theme style, text color etc.

**Comment by sc-dawidrutkowski** [comment]
@kars-springbok Correct me if I'm wrong - you want to extend standard Json Rendering template with custom fields?

**Comment by kars-springbok** [comment]
Well Custom Fields might a bit to much for now. But I noticed that in a lot of cases a simple Select Field option would come in handy.

**Comment by sc-dawidrutkowski** [comment]
@kars-springbok We can't extend Json Rendering template to have project-specific fields. You should locate this field in either data source item or rendering parameters for your rendering.
I need to close this one, sorry...
