### ISSUE TITLE
JSS Application Custom Icons

### ISSUE THREAD

**Issue by kars-springbok** [Sitecore/jss#247]
## Is your feature request related to a problem? Please describe.

Currently I have to go trough sitecore in order to adjust the JSS App icon.

## Describe the solution you'd like

In the package.json or somewhere else a option to select the path to the custom App Icon. So when I deploy the app it has its own Icon.

This would help increasing the view of the site three in Sitecore if you have multiple JSS applications.

## Describe alternatives you've considered

Doing it custom/manual trough sitecore.

## Additional information

Tiny improvement, but it would, for our case, be a real benefit. We currently have a Sitecore installation with 5 JSS applications.

**Comment by sc-dawidrutkowski** [comment]
@kars-springbok There is no such option so far and we are not planning to implement such a feature.
