### ISSUE TITLE
JSS Dictionary to work with Habitat Dictionaries 

### ISSUE THREAD

**Issue by kars-springbok** [Sitecore/jss#248]
## Is your feature request related to a problem? Please describe.

The Sitecore installation uses the Habitat Dictionary setup. We are looking into making a big switch to JSS. However this means, if we want to use the build-in Dictionary format in VueJS with JSS, we have to re-do the entire Dictionary in a normal dictionary. The Habitat Dictionary doesn't work with the Dictionary Service from JSS.

## Describe the solution you'd like

The Dictionary Service from JSS to work with Habitat Dictionaries.

## Describe alternatives you've considered

Doing GraphQL queries per Habitat Dictionary Item.

**Comment by sc-dawidrutkowski** [comment]
Habitat Dictionaries are not supported. This is a custom implementation which allows dictionary entries to be edited in Experience Editor.
I suggest writing a script to convert that data to a built-in dictionary.
