### ISSUE TITLE
JSS Component Definition Custom Icons

### ISSUE THREAD

**Issue by kars-springbok** [Sitecore/jss#249]
## Is your feature request related to a problem? Please describe.

When defining a component you have the option to define the icon. However there is no easy way to create a custom Icon library trough JSS.

## Describe the solution you'd like

Would be great to have the same setup for Dictionary/Media/Content. Just a folder for Icons, you upload them in that folder. Once you deploy the JSS application, the icons are also pushed to Sitecore and usable by JSS trough the Component Definitions. 

(Could also help with making: https://github.com/Sitecore/jss/issues/247 work)

## Describe alternatives you've considered

Doing it manual trough Sitecore. Which can be a bit annoying considering we have 3 servers, dev, staging and production. So I have to do it 3 times.

## Additional information

Small improvement, but could really bring the personalisation of JSS applications to higher levels.

**Comment by sc-dawidrutkowski** [comment]
@kars-springbok There is no such option so far and we are not planning to implement such a feature.
