### ISSUE TITLE
When Deleting an JSS component from the Site Three automatically deleted the Final Layout Control

### ISSUE THREAD

**Issue by kars-springbok** [Sitecore/jss#250]
## Is your feature request related to a problem? Please describe.

A lot of times our webmasters see a blank page because JSS gets an error. This is because they delete the component trough the Site Three and forget that they also have to delete it trough the Final Layout Controls list.

## Describe the solution you'd like

If you delete a component trough the Site Three, it automatically deletes the corresponding Final Layout control of that component. This way the webmaster doesn't have to delete twice. Saving time, and is less prone to errors.

## Describe alternatives you've considered

Better training for webmasters so they don't forget to also delete the Final Layout Control. Or changing the delete flow to Delete from Final Layout > Then delete from site three.

## Additional information

The webmasters told me that with regular Sitecore, they could delete components from the Site Three without the webpage going blank. Which is the case with Sitecore JSS. If there is a component in the Final Layout without a corresponding Component/Data Source. The entire page won't load. This is very dangerous, since it can easily be overlooked by a webmaster.

**Comment by sc-dawidrutkowski** [comment]
This sounds like your project-wide helper script rather than a JSS framework feature.
