### ISSUE TITLE
Invoke a Web api from sitecore JSS react application

### ISSUE THREAD

**Issue by navancommits** [Sitecore/jss#251]
Hi,  I had a react js application (http://localhost:3000) that invoked a web api (http://xyz) POST method. The way i accomplished that is - through the "proxy":"http://xyz" setting in the package.json of the http://localhost:3000 react js application. When i moved the react js application to sitecore jss, the call isn't successful - xhr.js:155 GET http://new-jss-app.dev.local/sitecore/service/notfound.aspx?item=%2fapilist%2fsignin&user=extranet%5cAnonymous&site=new-jss-app

Any pointers to help accomplish the call? Thanks.....

**Comment by nickwesselman** [comment]
Not enough info here to provide a solution and the issue is a year old, please feel free to re-open if you still need assistance.
