### ISSUE TITLE
JSS Tracking API docs missing configuration of fetcher

### ISSUE THREAD

**Issue by nickwesselman** [Sitecore/jss#253]
## Description
The JSS Tracking API docs do not document the configuration of the `fetcher`.

## Expected behavior
Docs should demonstrate a complete example of configuring the `trackingApiOptions`.

## Steps To Reproduce
Attempt to follow code in existing Usage docs:
https://jss.sitecore.com/docs/fundamentals/services/tracking

Assigning a `fetcher` is not documented but is required, and that fetcher needs to be configured to use a `POST` by default if provided any data.

## Possible Fix
Update docs following tracker code samples that do work:
https://github.com/Sitecore/jss/blob/b41311b2aa8ed885a4d6d1d3d030da6e3496515b/samples/react/src/components/Styleguide-Tracking/index.js

Possibly reference `dataFetcher` sample if needed:
https://github.com/Sitecore/jss/blob/b41311b2aa8ed885a4d6d1d3d030da6e3496515b/samples/react/src/dataFetcher.js

**Comment by nickwesselman** [comment]
Thanks to @joostmeijles for reporting on Slack.

**Comment by Strandol** [comment]
There are another issue [#212 ](https://github.com/Sitecore/jss/issues/212)
Below the article - `Invoking the Layout Service from JSS`, we need to update `fetchOptions`, also by adding property `fetcher`, because it's required in `fetchRouteData` but is missed in documentation

**Comment by sc-illiakovalenko** [comment]
There are another issue #212
Below the article - Invoking the Layout Service from JSS, we need to update fetchOptions, also by adding property fetcher, because it's required in fetchRouteData but is missed in documentation

**Comment by sc-antonkulagin** [comment]
@nickwesselman This doc request was done by merging #306. If you feel that additional information is needed, feel free to reopen this issue or create a new one.
