### ISSUE TITLE
Angular 8 upgrade note: Lazy loading via string is deprecated

### ISSUE THREAD

**Issue by kamsar** [Sitecore/jss#260]
## Description
See https://angular.io/guide/deprecations#loadchildren-string-syntax

This string syntax is used by the JSS lazy component loading code generator here:
https://github.com/Sitecore/jss/blob/08c380610ef92fa4dab9d6c941f49750fd677a6a/samples/angular/scripts/generate-component-factory.ts#L98

And in the documentation around JSS Angular lazy loading. When #241 occurs, this updated function syntax needs to be tested and verified working, and the docs updated so they do not recommend deprecated syntax.

**Comment by sc-dawidrutkowski** [comment]
Angular has been updated in #271.
