### ISSUE TITLE
--acceptCertificate can accept fingerprints in a variety of formats

### ISSUE THREAD

**Issue by adamconn** [Sitecore/jss#261]
When using the `--acceptCertificate` parameter, the JSS CLI requires the fingerprint that is specified to be in a hex string format. The value must meet the following criteria:
1. be 60 characters long
2. all characters must be upper-case
3. semicolon is used to separate bytes

The following is an example of an acceptable value: 

`5E:D1:5E:D4:D4:42:71:CC:30:A5:B6:A2:DA:A4:79:06:67:CB:F6:36`

Depending on the approach used to read the fingerprint from the certificate, the fingerprint value may not conform to these requirements. For example, the fingerprint above may be returned in the following formats:
* `5ED15ED4D44271CC30A5B6A2DAA4790667CBF636`
* `5e:d1:5e:d4:d4:42:71:cc:30:a5:b6:a2:da:a4:79:06:67:cb:f6:36`
* `5ed15ed4d44271cc30a5b6a2daa4790667cbf636`

This feature ensures that fingerprints in a variety of formats can be matched correctly.

**Comment by sc-dawidrutkowski** [comment]
The related pull request has been merged.

**Comment by mohanrangaswamaiah** [comment]
Yes. this works.` jss deploy app --acceptCertificate 89:17:0D:35:FB:F6:FC:3E:8E:E5:9A:22:CE:6C:83:81:8C:DE:76:DD -c -d` Thank you!
