### ISSUE TITLE
Error in description of one of methods of Manifest interface

### ISSUE THREAD

**Issue by mvasin** [Sitecore/jss#267]
`setDefaultRouteType` description in `Manifest` interface is mistakenly copied and pasted (without changes) from `addRouteType` just above it: https://github.com/Sitecore/jss/blame/dev/packages/sitecore-jss-manifest/src/generator/manifest.types.ts#L35-L42

Sure, it's not critical, but it should be corrected.

**Comment by sc-dawidrutkowski** [comment]
@mvasin Comment has been updated.
