### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by dbismut** [Sitecore/jss#28]
Hi, I've been trying to run `jss start:connected` after the project setup and got the following error:

```
env: node\r: No such file or directory
```

I'm running Mac OS X.

The culprit is `scjss-verify-setup` and more specifically the file `/node_modules/@sitecore-jss/sitecore-jss-dev-tools/dist/bin/verify-setup.js` which had CRLF line endings.

This is to be a common issue on numerous NPM modules. I would suggest normalizing all line endings of @sitecore packages to LF.

**Comment by nickwesselman** [comment]
FYI, we're working on a fix and plan to push an update for this soon. Thanks for reporting!

**Comment by nickwesselman** [comment]
@dbismut @sowhatdoido Line endings should no longer be an issue on mac, let us know if you see otherwise.

**Comment by dbismut** [comment]
I confirm it's now all good!
