### ISSUE TITLE
Retrieving language from ssrInitialState is incorrect for React

### ISSUE THREAD

**Issue by mcsdwarken** [Sitecore/jss#280]
## Description
When retrieving a default language for a website from SSR app, it always defaults to "EN" (default app language)

## Expected behavior
Retrieves language from SSR state.

## Steps To Reproduce
Create a site in Sitecore which has language set to e.g. nl, mapped to a certain domain name, e.g. my-site-nl.sc . The default website (my-site.sc) should have default language set to en.
When accessing my-site-nl.sc, the dictionary loads EN version.

## Possible Fix
in RouteHandler.js
```
 if (
      ssrInitialState &&
      ssrInitialState.sitecore &&
      ssrInitialState.sitecore.context &&
      ssrInitialState.sitecore.context.language
    ) {
      this.state.defaultLanguage = ssrInitialState.sitecore.context.language;
    }
```
(added `.sitecore ` after the `ssrInitialState`

## Your Environment
JSS 11.0.0 / React

**Comment by sc-illiakovalenko** [comment]
@mcsdwarken Fixed in #395
