### ISSUE TITLE
Placeholder not visible in Experience Editor

### ISSUE THREAD

**Issue by sreddy1240** [Sitecore/jss#288]
## Description

I am using sitecore 9.0 update-1 on our production site (using Web Forms - sub layouts(.ascx files)). And started using Sitecore JSS with Angular (JSS application template). 

I developed my own placeholder on freshly installed Sitecore-9.0.1 without web forms and I am able to see the placeholder position on the page(localsitecore9_working.PNG). But if I move same placeholder to one of our lower environment(QAT - we are using Web Forms), and it's not showing the position of the placeholder (QAT_ExpEditor.PNG). I am unable to add components to the new placeholder.

## Code
**fifty-fifty.sitecore.ts:**
export default function(manifest: Manifest) {
  manifest.addComponent({
    name: 'FiftyFifty',
    icon: SitecoreIcon.DocumentTag,
    placeholders: ['L50', 'R50'],
  });
}
**fifty-fifty.component.html (used bootstrap .col-md-6 for both)**
` <sc-placeholder name="L50" [rendering]="rendering"></sc-placeholder>`
`<sc-placeholder name="R50" [rendering]="rendering"></sc-placeholder>`
## Environment

* Sitecore Version: 9.0 update-1
* JSS Version: 11.0
* Browser Name and version: Chrome and Version 77.0.3865.120
* Operating System and version (desktop or mobile): Desktop Windows-10
* Link to your project (if available):

## Screenshots

localsitecore9_working.PNG
![localsitecore9_working](https://user-images.githubusercontent.com/57369307/68150058-fa90e100-ff0c-11e9-9069-185b946ee68b.PNG)

QAT_ExpEditor.PNG
![QAT_ExpEditor](https://user-images.githubusercontent.com/57369307/68150317-72f7a200-ff0d-11e9-8a01-fce2fe9eb47b.PNG)

**Comment by erzr** [comment]
@sreddy1240 are your placeholder settings deployed for this JSS application? i tried deleting the `jss-main` placeholder for one of my applications locally and once i did that, i could no longer see the placeholder in Experience Editor. you should be able to locate these settings in here: `/sitecore/layout/Placeholder Settings/Project/<jssappname>`.

**Comment by sunil2940** [comment]
@erzr Yes, I deployed new/custom placeholder settings to our QA environment. We do have Main(jaa-main) placeholder on the server.

This screenshot is from our issue environment.
![image](https://user-images.githubusercontent.com/19287829/68860576-c8734200-06b7-11ea-8d43-b26b32ba887c.png)

And in my previous "**QAT_ExpEditor.PNG**", the sample text on the page is added to **jss-main placeholder**.

**Comment by erzr** [comment]
@sunil2940 are your `L50` and `R50` placeholder settings set up properly? `Allowed Controls` and marked `Editable` by the checkbox on the placeholder settings? Any errors in the browser console when loading EE?

**Comment by sunil2940** [comment]
@erzr Yes, I do have `Allowed Controls` set up and marked `Editable` on the placeholder settings. And no sign of any errors in the browser console.

**From Chrome:** there is nothing under **insertRendering**
![image](https://user-images.githubusercontent.com/19287829/68951461-18233d80-078c-11ea-8ed7-4ba6490d3a97.png)

In the log file it's showing like this:
```
INFO  fifty-fifty component initialized with component data { uid: '5fe1ab32-c24a-47ed-b3d3-90a58b2f123b',
  componentName: 'FiftyFifty',
  dataSource: '',
  placeholders: { L50: [ [Object], [Object] ], R50: [ [Object], [Object] ] } }
```

**Comment by nickwesselman** [comment]
@sunil2940 @sreddy1240 Were you ever able to resolve this issue?

**Comment by sreddy1240** [comment]
Yes, I resolved it on my own after a long debugging period.


Thnaks,
Sunil

**Comment by richardhauer** [comment]
@sreddy1240  I'm facing this problem now - can you please advise what steps you used to resolve your issue. I can't seem to see my error.
