### ISSUE TITLE
Implement Sitecore JSS in existing Angular App

### ISSUE THREAD

**Issue by reinvanleirsberghe** [Sitecore/jss#293]
Starting from an existing Angular project, is it possible to implement Sitecore JSS?
What are the steps that should be taken to accomplish this?

**Comment by anastasiya29** [comment]
Hello,
This issue tracker is for reporting bugs and feature requests.

For help with individual projects, you best bet is to reach out to the JSS community, either in the [JSS channel on Sitecore Slack](slack://channel?team=T09SHRBNU&id=C7JT0NRQW), or post a question on [Sitecore Stack Exchange](https://sitecore.stackexchange.com/tags/jss).
