### ISSUE TITLE
How can you get the current authenticated user?

### ISSUE THREAD

**Issue by reinvanleirsberghe** [Sitecore/jss#298]
Using the docs on https://jss.sitecore.com/docs/techniques/authentication/sitecore-auth I have managed to login on my angular app.

Now I want to get my profile settings.
How can you get the current authenticated userId?
The only thing that is set is the cookie with a value, but I can't do anything with this value...

Thanks in advance!

**Comment by alexshyba** [comment]
Hi @reinvanleirsberghe 

You can bring profile settings from the server by extending LayoutService context, here is the doc that provides an example. This would require some .NET coding :)
https://jss.sitecore.com/docs/techniques/extending-layout-service/layoutservice-extending-context#extending-context-data-returned-by-the-layout-service

**Comment by erzr** [comment]
Here's an example of using GraphQL to accomplish this as well: https://github.com/erzr/JssAuthenticationSSC

**Comment by anastasiya29** [comment]
Creating a JS function for components to optionally use that would wrap the layout service response with user data would be a nice enhancement to the current behavior. I've added the appropriate label.

**Comment by nickwesselman** [comment]
When the current user is logged in, the domain and user are included in the LS Context. Can this be closed?
