### ISSUE TITLE
SitecoreContextReactContext.Provider is not working properly, because value never changes as it is always same class instance

### ISSUE THREAD

**Issue by M1r1k** [Sitecore/jss#299]
## Description
`SitecoreContext` class provide sitecore context via `<SitecoreContextReactContext.Provider value={this.contextFactory}>` but as suggested in samples implementation  is Singleton, default React's Object.is() comparison is not working when `SitecoreContextFactory.setSitecoreContext` is called and Provider's children are not rerendered.

## Expected behavior
All consumers be updated if context value is modified

## Steps To Reproduce

1. Start `./samples/react` and go to http://localhost:3000/styleguide/custom-route-type for example.
2. Add this line to `./src/AppRoot.js` - `window.debug1 = SitecoreContextFactory;` - for debugging purpose later
3. Now on "Custom route type" page we can trigger setSitecoreContext from the console
4. Run this code
```
debug1.context.route.fields.headline.value = "Reproduced"
debug1.setSitecoreContext(debug1.context)
```
This has to update `headline` property's value that should effect our page's tittle. But it does not.
However if you change `<SitecoreContextReactContext.Provider value={this.contextFactory}>` to 
`<SitecoreContextReactContext.Provider value={Object.assign( Object.create( Object.getPrototypeOf(this.contextFactory)), this.contextFactory)}>` it will work fine.

## Possible Fix
We have to use React best practice and pass simple objects to Provider value, like this.contextFactory.context

## Your Environment
* JSS Version: 13.0.0

**Comment by sc-illiakovalenko** [comment]
Fixed in #354
