### ISSUE TITLE
 jss deploy:watch is not generating the bundle file

### ISSUE THREAD

**Issue by PriyaShan16** [Sitecore/jss#308]
Hi,
 I followed the documentation https://jss.sitecore.com/docs/techniques/mvc-integration/javascript-rendering and created Javasrcipt rendering.

As per the documentation, jss deploy:watch should generate a bundle file which is not happening.

Please guide to identify and fix the issue.

Thanks,
Priya

**Comment by sc-illiakovalenko** [comment]
@PriyaShan16 Hi. Did you check files in  sitecore webroot `dist/JssComponentsReactWeb`?
It should generate bundles there. If you want to generate build in your project, not in sitecore instance, you can run `jss build`. Try to change any file and after that look into the `dist/JssComponentsReactWeb`. Please, notify about results

**Comment by sc-illiakovalenko** [comment]
@PriyaShan16 In case if you will have same problem in latest version, please, fell
free to open issue.
