### ISSUE TITLE
Vue lazy loading modules

### ISSUE THREAD

**Issue by karsvaniersel** [Sitecore/jss#309]
## Is your feature request related to a problem? Please describe.

Currently we noticed that a lot of our pages have low load times. This is only happening to the pages using VueJS + JSS. If we could have the components lazy load (or dynamically load) it would be a great benefit to the load timings.

## Describe the solution you'd like

So far I have not figured out in what file the components are imported, still trying to find the correct place, but the file that is importing the components per Route should have dynamic/lazy loading of each component. That way the initial first components load before all others. Making sure the load times stay minimal.

## Describe alternatives you've considered

Dynamically loading components, or setting custom timeouts.

**Comment by sc-illiakovalenko** [comment]
@kars-springbok in #366 I provided usage of lazy loading in local import of (Text, RichText...), but it's not related to Styleguide-* components. Some chunks appeared in `network` panel, but for now i don't found a way how to dynamically import Styleguide components

**Comment by aweber1** [comment]
It is important to be very selective with dynamic imports. It is far too easy to get carried away and think that you should dynamically import _all_ components. Remember that each component you dynamically import will likely represent a separate network request in order to load and then render. This can negatively impact your time-to-interactive speed as well as increase the amount of data being sent to clients. I would recommend taking the time to try to find a good balance between dynamic imports and static imports.

**Comment by sc-illiakovalenko** [comment]
@karsvaniersel You can edit `generateComponentFactory` function in `scripts/generate-component-factory.js`,
these components will be loaded in separate chunks. Start application and check `src/temp/componentFactory.js` - here is registration of your components.

```js
function generateComponentFactory() {
  // by convention, we expect to find Vue components
  // * under /src/components
  // * with a .vue extension to define a component file
  // If you'd like to use your own convention, encode it below.
  // NOTE: generating the component factory is also totally optional,
  // and it can be maintained manually if preferred.

  const imports = [];
  const registrations = [];

  // Define components that you want to lazy load
  const LAZY_LOADED_COMPONENTS = [
    'Styleguide-FieldUsage-Text',
    'Styleguide-Multilingual',
    'GraphQL-IntegratedDemo',
    'GraphQL-SSRDemo',
    'GraphQL-ConnectedDemo'
  ]

  const componentFiles = extractVueFiles(componentRootPath);
  componentFiles.forEach((componentFile) => {
    if (!fs.existsSync(componentFile)) return;

    console.debug(`Registering JSS component ${componentFile}`);
    const componentName = path.basename(componentFile, '.vue');
    const importVarName = componentName.replace(/[^\w]+/g, '');

    const importFullPath = componentFile
      .replace(path.join(componentRootPath, '/'), '')
      .replace(/\\/g, '/')
      .replace('.vue', '')
    // If it's component which should be lazy loaded -> generate dynamic import
    if (LAZY_LOADED_COMPONENTS.includes(componentName)) {
      registrations.push(`components.set('${componentName}', () => import('../components/${importFullPath}'));`);
      return;
    }

    imports.push(
      `import ${importVarName} from '../components/${importFullPath}';`
    );

    registrations.push(`components.set('${componentName}', ${importVarName});`);
  });

  return `/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.js to modify the generation of this file.
${imports.join('\n')}

const components = new Map();
${registrations.join('\n')}

export default function componentFactory(componentName) {
  return components.get(componentName);
};
`;
}
```
