### ISSUE TITLE
Ejecting... `scripts` already exists in your app folder. We cannot continue as you would lose all the changes in that file or directory. Please move or delete it (maybe make a copy for backup) and run this command again.

### ISSUE THREAD

**Issue by manu1222** [Sitecore/jss#311]
## Description

JSS react has scripts folder already, now `npm run eject` needs to create scripts folder too, so this is conflicting. Hence the error: 

`Ejecting... `scripts` already exists in your app folder. We cannot continue as you would lose all the changes in that file or directory. Please move or delete it (maybe make a copy for backup) and run this command again.`

## Steps followed to resolve:
1. Rename existing scripts folder to some other name.
2. Execute `npm run eject` again.
3. Merge the contents of newly created folder with the renamed folder.
4. Execute `jss start` but it is throwing errors.

## Errors

`index.js:1749 Fetch API cannot load file:///D:/Vipul/jss-react-ejected-app/node_modules/eslint-loader/dist/Linter.js. URL scheme must be "http" or "https" for CORS request.`

`index.js:1749 Fetch API cannot load file:///D:/Vipul/jss-react-ejected-app/node_modules/eslint-loader/dist/cacheLoader.js. URL scheme must be "http" or "https" for CORS request.`

`index.js:1749 Fetch API cannot load file:///D:/Vipul/jss-react-ejected-app/node_modules/loader-fs-cache/index.js. URL scheme must be "http" or "https" for CORS request.`

`Fetch API cannot load file:///D:/Vipul/jss-react-ejected-app/node_modules/graceful-fs/graceful-fs.js. URL scheme must be "http" or "https" for CORS request.`

`main.chunk.js:10 Uncaught Error: Module build failed (from ./node_modules/eslint-loader/dist/cjs.js):
TypeError: Cannot read property 'forEach' of undefined
    at Linter.parseResults (D:\Vipul\jss-react-ejected-app\node_modules\eslint-loader\dist\Linter.js:121:13)
    at Linter.printOutput (D:\Vipul\jss-react-ejected-app\node_modules\eslint-loader\dist\Linter.js:85:26)
    at cache (D:\Vipul\jss-react-ejected-app\node_modules\eslint-loader\dist\cacheLoader.js:46:14)
    at D:\Vipul\jss-react-ejected-app\node_modules\loader-fs-cache\index.js:139:9
    at D:\Vipul\jss-react-ejected-app\node_modules\graceful-fs\graceful-fs.js:57:14
    at FSReqWrap.oncomplete (fs.js:135:15)
    at Object../src/index.js (http://localhost:3000/static/js/main.chunk.js:10:7)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:786:30)
    at fn (http://localhost:3000/static/js/bundle.js:151:20)
    at Object.0 (http://localhost:3000/static/js/main.chunk.js:22:18)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:786:30)
    at checkDeferredModules (http://localhost:3000/static/js/bundle.js:46:23)
    at Array.webpackJsonpCallback [as push] (http://localhost:3000/static/js/bundle.js:33:19)
    at http://localhost:3000/static/js/main.chunk.js:1:99`

`./src/index.js
TypeError: Cannot read property 'forEach' of undefined`

**Comment by sc-illiakovalenko** [comment]
@manu1222 Fixed in #323. You can run `npm run eject:script` that will automatically eject react application and save `scripts` folder. If you will have any problems, feel free to reopen issue

**Comment by manu1222** [comment]
@sc-illiakovalenko I'm getting below message:

Ejecting...
`scripts` already exists in your app folder. We cannot continue as you would lose all the changes in that file or directory. Please move or delete it (maybe make a copy for backup) and run this command again.
npm ERR! code 1
npm ERR! path E:\manu\eject-jss
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c react-scripts eject

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\AppData\Local\npm-cache\_logs\2021-04-02T14_57_31_604Z-debug.log

**Comment by manu1222** [comment]
@sc-illiakovalenko Just saw previous message, `npm run eject:script` and it worked, but I thought `jss eject` would also work.
