### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by alexshyba** [Sitecore/jss#312]
With open 14 PRs and and 36 open issues and last commit 22 days ago related to documentation fixes, there doesn't seem to be much active contribution in past months.

What is the status of JSS?
Is this project going to be maintained by Sitecore?
If not, are you looking for code contributors?

Would be great if somebody clarifies the status of the project.

**Comment by AdamNaj** [comment]
JSS is very much alive and is at the core of our future development. Not all development is happening in GitHub as a lot of changes are introduced in the back-end.

It is true that we were not able to devote as many resources as we should to it in the past. We are in the process of restructuring the team to mitigate that problem.
