### ISSUE TITLE
Angular scaffolding has error in polyfill.ts

### ISSUE THREAD

**Issue by bic742** [Sitecore/jss#314]
## Description
When executing the jss create command for angular, the resulting scaffolded site will not immediately start. This is caused by a bad module reference in the polyfill.ts file.

## Expected behavior
After executing the jss create command with angular as the chose framework, the site should start.

## Steps To Reproduce
1. Execute command `jss create the-app angular`
2. cd into new app directory
3. Execute command `jss start`
4. Site will not start due to bad reference in polyfill.ts

## Possible Fix
On line 41-42 of https://github.com/Sitecore/jss/blob/dev/samples/angular/src/polyfills.ts, replace 'es6' with just 'es'.

**Comment by sc-illiakovalenko** [comment]
@bic742 Thank you, for your request.
Fixed in #320
