### ISSUE TITLE
Scaffold a component and deploy datasource template and datasource location

### ISSUE THREAD

**Issue by iamandycohen** [Sitecore/jss#316]
## Is your feature request related to a problem? Please describe.
When you scaffold a new component, deploy the component and you try to add the component via experience editor, you get a generic non-descript javascript alert because there is no datasource location or datasource template.

## Describe the solution you'd like
Because the default scaffolding includes fields, it needs a datasource template and datasource location.  When deploying the template, it would be nice if there was --datasource-location and a --datasource-template arguments.  Additionally, I'm wondering why the EE errors at all.  This feels like the situation where the controller action is returning null.  Instead of returning null, it should probably return an empty result.

## Describe alternatives you've considered
Better yet, it would be great if you could scaffold and deploy templates directly from JSS and they were auto generated when you scaffold a component.

**Comment by sc-dawidrutkowski** [comment]
This feature would probably also require some changes in the back-end (Sitecore.JavaScript.Services module).

**Comment by sc-antonkulagin** [comment]
we do not plan to implement it at this moment in the deployment back-end. This shouldn`t be a blocker since you can set this value in Sitecore post deployment.
