### ISSUE TITLE
Advanced sample react notes

### ISSUE THREAD

**Issue by dbismut** [Sitecore/jss#32]
Hi - I'm playing with the `advanced-sample-react` JSS sample and here are a few notes that I'm curious to hear your thoughts about:

## Package updates
It looks like the sample uses outdated packages such as i18n or redux. I've forced them to update to the latest version without any trouble, so I was wondering if there was a specific reason why they aren't set to the latest major version.

## Component names
Redux logger shows cryptic **undefined/COMPONENT_MOUNTED/UNMOUNTED** messages. I've submitted a PR https://github.com/Sitecore/jss/pull/30 here that should solve this.

## Routing with React Router
I'm not a big fan of React Router so I might be wrong here, but it looks like you're hacking the route changes to first fetch the Sitecore data and then manually push the url in `app/actions.js`. This looks a bit weird to me (again no expert speaking).

I've managed to set up a middleware that listens to react-router-redux location changes, and only then fetches Sitecore data. It looks like this:

```js
// SitecoreContentService.js
import { LOCATION_CHANGE } from 'react-router-redux';
import { changeRoute } from 'app/actions';
import { NOT_FOUND_ROUTE, SERVER_ERROR_ROUTE } from 'app/constants';

const noDataRoutes = [NOT_FOUND_ROUTE, SERVER_ERROR_ROUTE];
export default store => next => action => {
  if (action.type === LOCATION_CHANGE) {
    const pathname = action.payload.pathname;
    if (noDataRoutes.indexOf(pathname) < 0) {
      store.dispatch(changeRoute(pathname));
    }
  } else {
    next(action);
  }
};
```

I've removed all url pushes in `actions.js` and the `MainNav.js` file is also a lot cleaner:

```js
// MainNav.js
import { LinkContainer } from 'react-router-bootstrap'; // <-- new package

// NavItems look like this, no more onClick hack
    <LinkContainer
      key={index}
      to={getRouteUrl(currentLang, navItem.path)}
    >
      <NavItem className="page-scroll">{navItem.name}</NavItem>
    </LinkContainer>
// etc.
```

**Comment by aweber1** [comment]
Hi @dbismut,

Thanks for the great feedback!

I'll preface my response by saying the sample apps are meant to primarily demonstrate how you _might_ implement an application using JSS. The apps are not intended to demonstrate how you _must_ implement them. The key takeaways from the sample apps should be how to fetch data from Sitecore, use that data within your app, and how to use the helper components.

* Package updates - this is certainly something we can explore and ensure dependencies are updated. Time and resource constraints would be the only reason they aren't updated.

* Component names - your PR has been noted and is much appreciated! We maintain the source for these apps internally at the moment, so will merge the changes there and deploy when ready.

* Router - I'll defer to my earlier comments about the intent of the sample apps. They are intended to demonstrate how to integrate the JSS libraries within applications, but are not the only way to do so. I'll add a backlog item to explore the changes you suggest.

cheers,
adam

**Comment by dbismut** [comment]
Hi Adam, thanks for your answer!

I understand samples are just one option, but since the `jss` cli uses them as a starter app I think it would be nice to implement things as naturally as possible.

To come back to the router issue, it really felt like a hack to me, and my initial reaction was: wow, Sitecore breaks how fetching external data is normally done.

Another example: in `i18n.js`, there's `wait: false` with the comment *// setting to true breaks SSR and Experience Editor, would be nice to conditionally set to "true"*. I've tried setting `wait` to `true` and everything seems to work ok, even in the Experience Editor (maybe because of the way I implemented fetching data).

I'm also not sure of the need to wrap all components in `CommonComponent` for example, as even if this might prove useful for some devs, it's completely unrelated to JSS (or I missed something).

What I'm trying to say is that I'd be careful in showcasing Sitecore headless functionalities in the most seamless way for non-Sitecore users ;)

Anyway, keep up the great work, I have major interest in this project.

**Comment by kamsar** [comment]
Totally agree with your feedback. We're going to consolidate and simplify the React samples in the next release, with some nice enhancements to developer experience and a focus on being readable for learners.

As part of that, we're going to stop using Redux in the sample entirely. The routing will also be using plain react-router in a configuration [more like this](https://github.com/Sitecore/jss/blob/master/samples/basic-sample-react/src/boot/Root.js) but naturally improved and easier to read.

Redux will of course still be usable; the sample apps are boilerplates to take and customize.
