### ISSUE TITLE
Local issuer certificate + graphQL

### ISSUE THREAD

**Issue by alex-kisimov** [Sitecore/jss#325]
## Description
During a page rendering action using Sitecore JSS Integrated mode, a GraphQL query is executed to get additional data. This throws the following error: 

`Network error: request to https://site.local/api/site?sc_apikey={1B2D6CB9-BFCC-40FC-9020-F5B54EABD970} failed, 
reason: unable to get local issuer certificateat new ApolloError (D:\WebApplications\site.local\Website\dist\site\server.bundle.js:3330:28)
at D:\WebApplications\site.local\Website\dist\site\server.bundle.js:4508:40
at D:\WebApplications\site.local\Website\dist\site\server.bundle.js:4819:25
at Set.forEach (<anonymous>)at D:\WebApplications\site.local\Website\dist\site\server.bundle.js:4817:32
at Map.forEach (<anonymous>)at QueryManager.broadcastQueries (D:\WebApplications\site.local\Website\dist\site\server.bundle.js:4815:22)
at D:\WebApplications\site.local\Website\dist\site\server.bundle.js:4422:47at process._tickCallback (internal/process/next_tick.js:68:7)]`

We do have a valid certificate which has been generated by a Certificate Authority, so this is not a self-signed certificate issue.

## Expected behavior
Successful graphQL query

## Steps To Reproduce
1. Create a React Component 
2. Execute a graphQL query
3. See error

## Your Environment
* Sitecore Version: 9.2
* JSS Version: 13.0.0
* Browser Name and version: any
* Operating System and version (desktop or mobile): Windows 10 - desktop

**Comment by sc-illiakovalenko** [comment]
@alex-kisimov Can you provide additional detailed steps to reproduce this issue? Because I couldn't reproduce it

**Comment by alex-kisimov** [comment]
[client-app.zip](https://github.com/Sitecore/jss/files/4236896/client-app.zip)

@sc-illiakovalenko Attached should be an example of our JSS app with a component (Breadcrumb). This component does a graphQL call to get rendering data.

**Comment by anastasiya29** [comment]
In the future, you'd be better off getting help with project-specific errors if you post on [Sitecore Stack Exchange](https://sitecore.stackexchange.com/tags/jss). 

Anyway, I suspect the problem is that you renamed your app and now something is out of sync with your config. The GraphQL API endpoint in your package.json does not match the GraphQL endpoint in sitecore/config/JssReactWeb.config
