### ISSUE TITLE
Item Links failing to find reference with disconnected mode

### ISSUE THREAD

**Issue by bouncehead13** [Sitecore/jss#328]
## Description
There is a bug with disconnected mode when unpacking referenced items compared to the same setup in SiteCore itself (connected-mode) and correctly returning/unpacking all referenced items.

## Expected behavior
All references as `{ "id": "referenced_id" }` to be located and unpacked

## Steps To Reproduce
Our setup is as such
```
Route file is referencing component (id: default-footer)
  |
  Default Footer has Content List, w/ 1 item, referencing template (id: home-link)
    |
    Home Link has an Item Link to component (id: check-image)
      |
      Check Image has an Item Link to template (id: check-sm)
```

All parts of the references are resolved except the last `check-sm`. Instead of the reference, it is outputting `{value: {id: "check-sm" } }`. Exploring the JSS Manifest code, it seems to be caused by the `Component -> Template -> Component -> Template` and the order of operations when finding the referenced objects fails to fully unpack everything.

## Example Output Broken
```
{
    "uid": "{2650EBCB-7975-5CEB-B753-6FDF61A6729D}",
    "componentName": "FooterComponent",
    "dataSource": "available-in-connected-mode",
    "params": {},
    "fields": {
        "links": [
            {
                "fields": {
                    "name": {
                        "value": "click here"
                    },
                    "url": {
                        "value": "https://link.com"
                    },
                    "icon": {
                        "id": "available-in-connected-mode",
                        "fields": {
                            "small": {
                                "value": {
                                    "id": "check-sm"
                                }
                            }
                        }
                    }
                },
                "id": "available-in-connected-mode"
            }
        ]
    }
}
```

## Possible Fix
Items that were previously unpacked and had `id` replaced with `resolvedFromItemId` should be searched a second time. With this change, the traversal code will correctly find all remaining, non-unpacked ids.

https://github.com/Sitecore/jss/blob/dev/packages/sitecore-jss-manifest/src/generator/traversal.ts#L63
```
// checking for resolvedFromItemId in case referenced objects were not fully built the first run through
if (currentField.value && (currentField.value.id || currentField.value.resolvedFromItemId)) {
    processCandidateFieldValue(currentField.value);
}
```

## Your Environment
* Sitecore Version: 9.2
* JSS Version: 13.0.0
* Operating System and version (desktop or mobile): MacOS 10.15.3

**Comment by sc-illiakovalenko** [comment]
@bouncehead13 Thank you for provided fix, i tried to reproduce it - now it's working fine.
Fixed in #362
