### ISSUE TITLE
docs: Reference

### ISSUE THREAD

**Issue by thany** [Sitecore/jss#329]
Can we please have a full reference of all available components & props? 😘

Currently the documentation is like a mishmash of practices, tutorials, and examples. I'm really missing a comprehensive reference. I have no way of knowing what I can import from the package, or what props might be supported on each component, without diving into its (minified!) sourcecode. Never mind what everything does 😱

**Comment by anastasiya29** [comment]
This is the plan:
- Utilize TypeScript typing and inline comments to generate API reference 
- Automate generation on build
- Normalize the format of the API reference with the look and feel of the rest of the docs
- Publish to docs site

**Comment by thany** [comment]
Can you please give this some prioity?
I'm trying to use the `Link` component, of which there's not a single mention that it even exists, so that was a good guess, I suppose. But I have no way of knowing what I can/should pass to it.

Can I make it render as a different component like, say
```jsx
<Link as={FancyLink} />
```
I bet your jsdoc doesn't cover this.

**Comment by kamsar** [comment]
The sample apps' styleguide page is intended to be a live reference of usage examples that you can actually run. See the link example:
https://github.com/Sitecore/jss/blob/dev/samples/react/src/components/Styleguide-FieldUsage-Link/index.js

**Comment by thany** [comment]
I don't need examples. I know how to write code. I need a reference because I don't (or rather, *can't*) know what props I can throw at JSS.

**Comment by anastasiya29** [comment]
I agree that an API reference will be helpful.
However, I think the following can help you in the meantime. 

> I have no way of knowing what I can import from the package, or what props might be supported on each component, without diving into its (minified!) sourcecode. Never mind what everything does 😱

You don’t have to try to decipher minified code. The JSS modules are written in TypeScript and are heavily commented. Just clone this repo locally and all the typed function signatures and props models will be available for you to reference.

**Comment by ambrauer** [comment]
We now provide API reference documentation as part of each release (starting with JSS version 18.0). You can find these on the release branch in the Github repository under `/ref-docs`.  Here are the latest, for example: https://github.com/Sitecore/jss/tree/master/ref-docs
