### ISSUE TITLE
CLI deploy options do not trigger build step (Vue sample app)

### ISSUE THREAD

**Issue by kbauer-hhog** [Sitecore/jss#336]
## Description
Build step is not being run before `jss deploy app` or `jss deploy files` CLI commands.

I had to manually build using `jss build`, and then running `jss deploy files`. 

This was found using the Vue sample app. Unsure if other sample apps are having this issue.

## Expected behavior
I expect the build step to be run by default. 
Documentation and `--help` say that option `--skipBuild` is `false` by default.

## Steps To Reproduce
1. Run `jss deploy app` or `jss deploy files` via command line.
2. Build step will not run. It will only attempt to copy the `./dist/` folder to the instance.

## Possible Fix
A debug of `argv.skipBuild` variable in `@sitecore-jss/sitecore-jss-cli/dist/scripts/deploy.files.js` on the latest CLI version shows "false" as a string.  The same debug of this same line in version 11.0.2 shows the value as false as a Boolean. 

The conditional around the build step is expecting argv.skipBuild to be a Boolean value. This is why it does not build by default.

## Your Environment

* Sitecore Version: 9.3
* JSS Version: 13.0.3

**Comment by kbauer-hhog** [comment]
Possibly related: #308

**Comment by sc-illiakovalenko** [comment]
Fixed In #345
