### ISSUE TITLE
Rendering host sample setup issues

### ISSUE THREAD

**Issue by vitaliitylyk** [Sitecore/jss#339]
## Description

The React sample app implementation has 2 issues in rendering host setup:

1. There is a missing "@sitecore-jss/sitecore-jss-rendering-host": "^13.0.2" dependency in packages.json
2. /scripts/http-renderer.js is pointing to /build-rendering-host/ folder, while build scripts are copying output to the /build/ folder

I can submit a PR with a fix, however not sure about the second issue. It seems there is no out-of-the box way to specify output directory for react-scripts build command: https://github.com/facebook/create-react-app/issues/1354
What are your thoughts on this?

**Comment by anastasiya29** [comment]
Regarding issue 1 - isn't the use of the new rendering host optional? Users can continue using the old-school http method. Or does the missing reference cause errors even when using the old render method?

**Comment by vitaliitylyk** [comment]
Good point, it is optional and it does not cause any errors when using the old render method. However since this is a sample app I would expect everything to work without extra modifications (e.g if `start:rendering-host` npm script is defined - it should just work)

**Comment by sc-illiakovalenko** [comment]
@vitaliitylyk I provided my fixes in #394 , and merged your changes #355. Good job!
