### ISSUE TITLE
Context extension caching

### ISSUE THREAD

**Issue by boro2g** [Sitecore/jss#342]
Using JSON renderings, and contents resolvers, you get OTB control over how each component can be cached. 

In our solution we make heavy use of Context Extensions for e.g. header / footer content which is common to each page. The content which is used within these extensions tends to be consistent per page, so would benefit hugely from similar caching options to renderings (vary by url, vary by data etc.).

Could these options be available via the config to patch in Context Extensions? Or via [attributes] you set on each custom extension implementation?

**Comment by kamsar** [comment]
For common content consider making separate API calls (i.e. to GraphQL) to fetch the shared content. This shared content can then be cached between route changes on the browser side, reducing the amount of bandwidth used for route changes.

If that is not desirable then you can implement caching in the context extension itself, either using a custom Sitecore cache or some other cache mechanism and eviction method of your choosing. Given the generic nature of context extensions and where they fetch their data from, we do not plan to provide built in caching.

**Comment by boro2g** [comment]
Fair enough - could I suggest the jss docs site is updated to reflect this? I.e. caching isn't available otb on context extensions?

**Comment by kamsar** [comment]
If you'd like to do a PR that sounds fine to me. The relevant doc [is here](https://github.com/Sitecore/jss/blob/dev/docs/data/routes/docs/techniques/extending-layout-service/layoutservice-extending-context/en.md)
