### ISSUE TITLE
Publishing configuration for sitecore-jss-angular gives errors for Angular 9 ngcc

### ISSUE THREAD

**Issue by EvtK** [Sitecore/jss#348]
## Description
When using the latest @sitecore-jss/sitecore-jss-angular package with Angular 9, the ngcc compatiblity provider runs on an error. The issue here is that the sitecore-jss-angular package contains 2 package.json files.

I have opened up an [issue](https://github.com/angular/angular/issues/36164) on the Angular issue tracker, receiving quick response over there, with straightforward solutions.

## Expected behavior
The ngcc should not error out on this package.

## Possible Fix
The options to have this fixed (taken from the Angular issue thread):

1. Adjust the publishing to only publish dist. You are using Lerna where this was not possible in the past, but their should be support for now.
2. Include an ngcc configuration file in the repo next to package.json:

`module.exports = {
  entryPoints: {
    './dist': {
      ignore: true,
    },
  },
};`

**Comment by sc-antonkulagin** [comment]
Added ngcc.config in  #370

**Comment by EvtK** [comment]
I believe the added commit with config is incorrect, it should be:

```
module.exports = {
  packages: {
    entryPoints: {
      './dist': {
        ignore: true,
      },
    },
  },
};
```

**Comment by EvtK** [comment]
@sc-antonkulagin can this be re-opened? thanks!

**Comment by EvtK** [comment]
I believe this error (with angular differential loading enabled) is related:

```
/node_modules/@sitecore-jss/sitecore-jss-angular/__ivy_ngcc__/dist/esm2015/public_api.js depends on '@sitecore-jss/sitecore-jss'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

```
