### ISSUE TITLE
My components re-order randomly if they are more than 10

### ISSUE THREAD

**Issue by tomagladiator** [Sitecore/jss#35]
In localhost, with Vue JS basic sample.

In my homepage, I have 11 components with simple data like : Yo 1, Yo 2, Yo 3,... Yo 11

If I add 10 components, it's fine, but when I add one more, each time I refresh the page, the order changed!
REFRESH 1:
Yo 2, Yo 6, Yo 3, Yo 4, Yo 5, Yo 1, Yo 7, Yo 8, Yo 9, Yo 10, Yo 11

REFRESH 3 (good order):
Yo 1, Yo 2, Yo 3, Yo 4, Yo 5, Yo 6, Yo 7, Yo 8, Yo 9, Yo 10, Yo 11

REFRESH 2:
Yo 6, Yo 1, Yo 3, Yo 4, Yo 5, Yo 2, Yo 7, Yo 8, Yo 9, Yo 10, Yo 11

I tested with different components, the result is the same.
Thanks

**Comment by aweber1** [comment]
Can you provide a repo or codepen or gist with code that we can try to reproduce with? At the very least we'll need component code and the data being used.

**Comment by kamsar** [comment]
Also, is it connected or disconnected mode

**Comment by tomagladiator** [comment]
@aweber1 I will do it tomorrow! 
@kamsar I've connected my headless app to Sitecore nevertheless, this issue is in my headless app (localhost:3030), I didn't test it in Sitecore yet.

**Comment by tomagladiator** [comment]
Well, the steps to reproduce this issue is quit simple : 
1 - `jss create myapp basic-sample-vue-web`
2 - `cd myapp/`
3 - `jss start`
4 - in **data/routes/en.json**
5 - duplicate the components **11** times
6 - Add for each text.value a number `"<p> 1 </p>"`,` "<p> 2 </p>"`(...)"`<p> 11 </p>`"
7 - Delete everything inside assets/css/default.css (for visibility)
7 - reload the page several times

I did it with a fresh install in disconnected mode this morning.
My colleague also reproduced this issue.

**Comment by kamsar** [comment]
This will be fixed in the next release. FWIW, connected mode and integrated modes are not affected by this issue.

**Comment by tomagladiator** [comment]
Suggested by @kamsar 

Comment line:193 from **node_modules\@sitecore-jss\sitecore-jss-dev-tools\dist\disconnected-server\layout-service.js**

`// .sort(function (a, b) { return a.placeholderKey.length - b.placeholderKey.length; })`
