### ISSUE TITLE
vue-loader recent issue - need update from 14.x to 15.x

### ISSUE THREAD

**Issue by tomagladiator** [Sitecore/jss#36]
This morning, I tried a clean install of the sample vueJs
An error occured about vue-loader...

To fix it , I updated this module with `npm install vue-loader@15.2.1 --save-dev `

Then, I added in webpack.shared.js line:30
`const VueLoaderPlugin = require('vue-loader/lib/plugin');`

And line:126, in plugins:
`new VueLoaderPlugin(),`

**Comment by aweber1** [comment]
This is resolved in the latest sample app, which uses the latest release candidate of @vue/cli, which is responsible for webpack dependencies.
