### ISSUE TITLE
'deploy template' does not accept --acceptCertificate

### ISSUE THREAD

**Issue by bakgaard** [Sitecore/jss#367]
## Is your feature request related to a problem? Please describe.
I can't use ``jss deploy template <templateName> --acceptCertificate``, because the option is not implemented for that command. I would like that.

## Describe the solution you'd like
Add it, perhaps like #194.

**Comment by sc-illiakovalenko** [comment]
@bakgaard It seems that you have this problem only inside the `react sample app`?
Resolved by - https://github.com/Sitecore/jss/commit/a1f323768506ccf1ec92d7c6bb6f2990c2de0ae7
Will be released later

**Comment by bakgaard** [comment]
> @bakgaard It seems that you have this problem only inside the `react sample app`?

Yes, that is correct. 

> Resolved by - [a1f3237](https://github.com/Sitecore/jss/commit/a1f323768506ccf1ec92d7c6bb6f2990c2de0ae7)
> Will be released later.

Splendid! Thank you.
