### ISSUE TITLE
Sitecore JSS Integration with Next.JS

### ISSUE THREAD

**Issue by shilpasjoshi2** [Sitecore/jss#371]
Hi Team,

I have an existing Next.js application. I want to integrate sitecore jss with it and deploy it to sitecore.

Can you please suggest me the steps for the same.

**Comment by aweber1** [comment]
Feel free to use the Uniform + Next.js + JSS starter kit available here for ideas on how to integrate JSS with your Next app:
https://github.com/uniformdev/sitecore-jss-nextjs-starterkit

There are things you have to do differently with Next than in the traditional JSS samples, but using Next provides an overall better development experience.

**Comment by shilpasjoshi2** [comment]
Hi Adam,

Thanks for a quick reply.

Is this a free one please. If not please share the pricing plan details.

Thanks,
Shilpa

**Comment by aweber1** [comment]
Yes, the starter kit is free to use. The Uniform integration is optional.

**Comment by shilpasjoshi2** [comment]
Hi Adam,

When I try to run "npm install" in src folder as suggested in steps, it
gives error saying "Error: Failed to replace env in config: ${NPM_TOKEN}"

Can you please let me know what can be done here.

Thanks & Regards,
Shilpa

**Comment by alexshyba** [comment]
@shilpasjoshi2 responded via email. suggest we close this issue here, please feel free to open an issue related to the next.js starter kit in the corresponding repo.

**Comment by sc-illiakovalenko** [comment]
@aweber1 , @alexshyba Thank you guys for response
