### ISSUE TITLE
Usage of Error Component

### ISSUE THREAD

**Issue by anzhelikakovalchuk** [Sitecore/jss#372]
## Description
Hi, I am trying to use errorComponent props to create a custom error handler.
![image](https://user-images.githubusercontent.com/48444172/81798953-4b673f00-9519-11ea-9c7b-87e5ecfcfa51.png)
But it doesn't seem to work

## Expected behavior
Expected to pass error component by props errorComponent

## Steps To Reproduce
```
What I am trying to do:
<template>
  <placeholder
      name="main"
      :rendering="rendering"
      :errorComponent="errorComponent"
    />
</template>
<script>
import { Placeholder} from '@sitecore-jss/sitecore-jss-vue'

const errorComponent= {
  render (createElement) {
    return createElement('div', {}, 'this is a custom error component')
  }
}

export default {
  name: 'index',

  layout: 'jss-default',

  components: {
    Placeholder,  
    errorComponent
  },  

  props: {
    fields: {
      type: Object,
      default: () => ({})
    }
  } 
}
</script>
```

## Your Environment

"@sitecore-jss/sitecore-jss": "^11.0.2",
 "@sitecore-jss/sitecore-jss-vue": "^11.0.2"

**Comment by aweber1** [comment]
In order to bind your component to the `errorComponent` prop on the `Placeholder` component in Vue, you need to expose it as a bindable property on the `index` Vue component instance, i.e. via `props`, `computed`, `data`, `methods`. 

```

export default { 
  ...
  // accept errorComponent as a prop
  props: {
    errorComponent
  },
  // or create a computed property
  computed: {
    errorComponent
  },
  // or get the component via local method
  methods: {
    getErrorComponent() {
      return errorComponent;
    }
  }
  ...
}
```

**Comment by anzhelikakovalchuk** [comment]
Thank you! that works.

**Comment by anzhelikakovalchuk** [comment]
@sc-antonkulagin @aweber1 great, thank you s o much!
I am just looking for the solution to that, if one component has an error then the whole placeholder falls with all other components that were quite good. I wonder if you can advise me something so that other components would render, and only the broken one would not be rendered.
