### ISSUE TITLE
Section field in Sitecore Forms throws error after 13.0.5 upgrade

### ISSUE THREAD

**Issue by CatiaGomes82** [Sitecore/jss#377]
## Description
While upgrading from JSS 13.0.0 to 13.0.5, I noticed that the section component for sitecore forms throws an error and does not output child fields. 

**Error details**
"Cannot read property 'map' of undefined"
`
<fieldset>	  
    {field.fields.map(fieldFactory)}	    
</fieldset>
`
This happens because "fields" property no longer exists in the props for the section component.

I believe this issue was introduced in this [PR#338](https://github.com/Sitecore/jss/pull/338) when the section field's view model was updated. In version 13.0.0, the props passed to the component included the fields array with all of the child fields for the section component:
`{
   "fields":[...],
   "model": {...}
}`
After the 13.0.5 upgrade:
`{
   "model": {...}
}`

## Expected behavior
I would expect the section element to render its child fields and not throw an error.

## Steps To Reproduce
1. Open Sitecore Forms and create a form
2. Add a section field and another field (can be any) inside it
3. Add form to a page
4. Open the page and see error "Cannot read property 'map' of undefined"

## Possible Fix
Revert the FormFieldSection class to inherit the **ViewModel** instead of **FieldViewModel**. The cssClass should still come from the model object as part of props so the issue in [PR#338](https://github.com/Sitecore/jss/pull/338) should remain fixed.

## Your Environment
* Sitecore Version: 9.2
* JSS Version: 13.0.5
* Browser Name and version: Chrome, Firefox and Edge

**Comment by sc-illiakovalenko** [comment]
@CatiaGomes82 That happened only after upgrading to 13.0.5? Did you upgrade Sitecore?
I just created a new form on the latest versions of jss and sitecore.
And have a structure:

![image](https://user-images.githubusercontent.com/55081915/82453218-ec756d00-9ab8-11ea-93d6-aa52c6b32f09.png)

As I know, backend stuff is responsible for data structure of forms.

Can you check response of endpoint?
http://jssreactweb/sitecore/api/layout/render/jss?item

**Comment by sc-illiakovalenko** [comment]
@CatiaGomes82 `FieldViewModel` just extends `ViewModel`

**Comment by CatiaGomes82** [comment]
Hi @sc-illiakovalenko, I did not upgrade Sitecore. I can see that I am not receiving the data from the layout service as you suggested so it seems that it's not related with the client app so I will be closing this issue.

Thanks for the quick response! :)

**Comment by sc-illiakovalenko** [comment]
@CatiaGomes82 No problem. Feel free to ask a questions.
