### ISSUE TITLE
CSS classes are wiped when using the Angular scLink directive for internal links

### ISSUE THREAD

**Issue by callmeaponte** [Sitecore/jss#378]
## Description

When using the scLink directive in an Angular JSS project - CSS classes are being wiped for internal links.

Even if an internal link has no classes added (in Sitecore) - it still wipes out any CSS classes that were added to the HTML element.

## Expected behavior
The classes should be preserved, similar to how external links behave.

## Steps To Reproduce
1. Add scLink to an anchor element.
2. Add some CSS classes to the aforementioned element.
3. Pass an **external** link to the scLink directive - notice the classes remain intact.
4. Pass an **internal** link to the scLink directive - notice the classes are wiped.

## Possible Fix
The bug seems to occur because there is a "class" field for internal links in Sitecore, and instead of appending them to existing CSS classes - it is replacing them. I'll open up a PR that will append to the existing CSS classes instead.

## Your Environment
* Sitecore Version: 9.3
* JSS Version: 13.0.2
* Browser Name and version: All browsers
* Operating System and version (desktop or mobile): All operating systems

**Comment by sc-illiakovalenko** [comment]
@callmeaponte I tried to reproduce this issue, using `styleguide-field-usage-link.component`.
I have:
```
  External link:&nbsp;
  <a class="super-puper-external-link" *scLink="rendering.fields.externalLink"></a>
  <br />
  Internal link:&nbsp;
  <a class="super-puper-internal-link" *scLink="rendering.fields.internalLink">
```

And rendering result:

![image](https://user-images.githubusercontent.com/55081915/82526652-29834300-9b3d-11ea-9663-469467900226.png)

Did I reproduce this issue correctly? In my case it's working as expected.

**Comment by callmeaponte** [comment]
@sc-illiakovalenko the issue occurs because there is also a `class` property on internal links. For example, here's what an internal link looks like in the JSS JSON:

<img width="443" alt="Screen Shot 2020-05-21 at 11 44 39 AM" src="https://user-images.githubusercontent.com/3664510/82577268-b982b600-9b58-11ea-9516-33c98e40c65b.png">

... so when this happens, the existing logic will wipe out the contents of your CSS class attribute, and replace it with the contents of the class property in the screenshot above.

To reproduce this in `styleguide-field-usage-link.component.ts`, add a `class` key to the `data/routes/styleguide/en.yml` file:

<img width="1148" alt="Screen Shot 2020-05-21 at 11 48 41 AM" src="https://user-images.githubusercontent.com/3664510/82577516-12eae500-9b59-11ea-86bc-ffd430628813.png">

... after the above change you'll only see `foo` (instead of `foo super-puper-external-link`) on your link:

```
<a class="foo" *scLink="rendering.fields.internalLink"></a>
```

**Comment by sc-illiakovalenko** [comment]
@callmeaponte Thank you, I'll try

**Comment by sc-illiakovalenko** [comment]
@callmeaponte I just checked it, and in another sample apps it's also working in same way.
Class that you set in styleguide/en.yml for internalLink, externalLink -> will override class that you set inside the component. Can you just set your `foo` with `class2` in en.yml? Or in sitecore (if connected mode)

**Comment by callmeaponte** [comment]
@sc-illiakovalenko thanks for checking. When working in connected mode, here is what the JSS JSON looks like for an external link:

<img width="353" alt="Screen Shot 2020-05-22 at 11 28 43 AM" src="https://user-images.githubusercontent.com/3664510/82683829-a686e900-9c1f-11ea-8a22-54e7ef727887.png">

... Notice that there is no `class` property in the JSON, so whatever CSS class you have in your component HTML remains intact. The moment a content author changes the same link to be internal - a (empty) `class` property is added to the JSON - and subsequently your CSS classes get wiped out. So it's inconsistent at the moment.

Additionally, it's arguably an anti-pattern to have all of your CSS classes in your HTML, _except_ for link classes. What if we have thousands of links in Sitecore, and need to update the CSS class for all of them? What if we only need to update some of them based on certain conditions? Sure, it _might_ be possible to PowerShell our way out of this problem but it could all be avoided by not wiping out the HTML classes to begin with.

Ideally, IMO the CSS classes that are present in Sitecore and the CSS classes that are present in the HTML should be **merged** together.

If for some reason that is not possible due to it causing some side effect I'm not aware of - then at the very least - the CSS classes in the HTML should _only_ be wiped out if CSS classes are added in Sitecore.

Currently, even if the `class` property is empty - our HTML classes are still being wiped out for no reason.

**Comment by sc-illiakovalenko** [comment]
@callmeaponte Thank you, I realized a problem. I merged proposed PR. #379. But it will be released later.
