### ISSUE TITLE
[JSS][Forms][React] Implement file upload to jss 13

### ISSUE THREAD

**Issue by mlukasz7** [Sitecore/jss#387]
## Is your feature request related to a problem? Please describe.
Current implementation JSS doesn't support file upload and this component is implemented in Sitecore 9.3.

## Describe the solution you'd like
I found that file upload component was created and merged to `release/14.0.0` ([PR](https://github.com/Sitecore/jss/pull/383)). It would be great also to merge it to JSS 13 version.

## Your Environment
Sitecore Version: 9.3
JSS Version: 13.0.5
Browser Name and version: All browsers
Operating System and version (desktop or mobile): All operating systems

**Comment by sc-illiakovalenko** [comment]
@mlukasz7 Added in JSS 13.2.0, in #392
