### ISSUE TITLE
Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by Alex-Dinu** [Sitecore/jss#397]
## Description
I'm getting the following error. Not sure if this is related to JSS or npm:

$ jss create jssdemo react
JSS CLI is running in global mode because it was not installed in the local node_modules folder.
**Error: self signed certificate in certificate chain**

## Steps To Reproduce
Just execuring the jss create cli command

## Your Environment
node: 12.16.1
npm: 6.14.5
jss:13.2.0
OS: Windows 10

Thanks
Alex

**Comment by sc-illiakovalenko** [comment]
@Alex-Dinu Can you look at https://stackoverflow.com/questions/45088006/nodejs-error-self-signed-certificate-in-certificate-chain
and try again?

**Comment by Alex-Dinu** [comment]
Thanks. Yes, I did set strict-ssl=false and it still did not resolve the issue.

**Comment by sc-illiakovalenko** [comment]
@Alex-Dinu  Can you try to run in command line: `set NODE_TLS_REJECT_UNAUTHORIZED=0 ` ?
And after that uninstall sitecore-jss-cli, and install again. And run: jss create

**Comment by Alex-Dinu** [comment]
Tried that as well:
$ NODE_TLS_REJECT_UNAUTHORIZED=0 jss create cfpoc react
JSS CLI is running in global mode because it was not installed in the local node_modules folder.
(node:20248) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
Error: read ECONNRESET

**Comment by Alex-Dinu** [comment]
We found the issue. It is not a JSS issue but rather our company blocked access to npm etc.
