### ISSUE TITLE
Prevent the Angular scLink directive from adding an href attribute, when href is equal to `http://` or `https://`

### ISSUE THREAD

**Issue by sc-illiakovalenko** [Sitecore/jss#408]
Related to #380. Need to extend #406 in order to prevent adding of `href` attribute when `href` is equal to `http://` or `https://`

**Comment by sc-illiakovalenko** [comment]
Fixed in #409 
@callmeaponte As I promised 😉

**Comment by callmeaponte** [comment]
@sc-illiakovalenko thank you! It's much appreciated.
