### ISSUE TITLE
Add the ability to remove the "missing Angular component implementation" placeholder

### ISSUE THREAD

**Issue by callmeaponte** [Sitecore/jss#418]
## Is your feature request related to a problem? Please describe.
We have a rendering that we need to add to the presentation details, but it does not have (or need) an Angular component. However it still "appears" on the page since `<sc-placeholder>` renders the following UI when this situation is encountered:

![Placeholder Image](https://i.imgur.com/Urwv39W.png)

## Describe the solution you'd like
Assuming there isn't an option for this already, it'd be useful if there was a way to turn this behavior off.

## Describe alternatives you've considered
Hiding these placeholders components via CSS.

**Comment by kamsar** [comment]
You can do that by overriding this injection token:

https://github.com/Sitecore/jss/blob/35588ce0152f8b3cc3e6921ad134b5ac1852785f/packages/sitecore-jss-angular/src/lib.module.ts#L120

**Comment by callmeaponte** [comment]
@kamsar thanks for the quick response but... how can we override that?

The code you referenced is located inside of your `@sitecore-jss/sitecore-jss-angular` package, and the `withComponents` method doesn't accept an argument to override those providers.
