### ISSUE TITLE
Custom manifest globs not registered by ManifestManager

### ISSUE THREAD

**Issue by virenratan** [Sitecore/jss#42]
- Tech preview 4
- Disconnected mode
- React sample

I am creating a codebase to drive a Sitecore multi-tenancy instance using a combination of shared and bespoke components for each tenant. When I try to use custom locations for my manifest files that do not conform to the pattern `['./sitecore/definitions/**/*.sitecore.js', './sitecore/definitions/**/*.sitecore.ts']` they are not picked up by the `ManifestManager`.

After investigating the ManifestManager code I've traced the problem down to a line missing from `@sitecore-jss/sitecore-jss-dev-tools/dist/disconnected-server/create-default-disconnected-server.js` where if I add `sourceFiles: options.sourceFiles,` to line 25 it is able to register my custom glob configuration:

```javascript
    var manifestManager = new manifest_manager_1.ManifestManager({
        appName: options.appName,
        rootPath: options.appRoot,
        sourceFiles: options.sourceFiles,
        watchOnlySourceFiles: options.watchPaths,
        requireArg: options.requireArg,
    });
```

This allows me to add sourceFiles as watchPaths into `./scripts/disconnected-mode-proxy.js` as below:

```javascript
const watchPaths = [
  // custom glob strings.
]

const proxyOptions = {
  appRoot: __dirname,
  appName: config.appName,
  sourceFiles: watchPaths,
  watchPaths,
  language: config.language,
  ...
}
```

Based on the ManifestManager compiled code it seems as though it has mistakenly been left out.

Is this a defect, or am I supposed to achieve this some other way?

**Comment by kamsar** [comment]
This looks like a bug to me. I've registered it in our internal backlog, and will investigate.

**Comment by kamsar** [comment]
The intent of `createDefaultDisconnectedServer` is that it's a boilerplate - for 'default' applications, saving duplicated code, and serving as a basis for more advanced applications to take the default code and replace it with a modified version.

This particular use-case shouldn't be 'advanced enough' to necessitate replacing the whole defaults structure. As such, when JSS is in final release the code you outlined above will be implemented (we've added the `sourceFiles` param).

In the meantime, consider copying the `createDefaultDisconnectedServer` function and keeping it in your app as a modified copy.
