### ISSUE TITLE
jss deploy doesn't support custom config file

### ISSUE THREAD

**Issue by thany** [Sitecore/jss#420]
## Description
We need a way to tell `jss deploy` which config file to pick up. This is for the purpose of deploying to different environments, e.g. content delivery, content management, and local SSR. We deploy to these environments in parallel, so in order to support `jss deploy` as it is, we *have to* deploy in serial, because the current `jss deploy` [hardcoded requires a static file called `scjssconfig.json` in the project root](https://github.com/Sitecore/jss/blob/938305ee66fc9937b18a6de9e6b68c3f6feda18b/packages/sitecore-jss-dev-tools/src/resolve-scjssconfig.ts#L19). We can prepare one for each environment, but then we couldn't ever deploy in parallel.

It also makes sense for other purposes, like when you want config files to reside in their own directory.

## Expected behavior
Add a CLI argument like `--config` and the path to the config file.

## Steps To Reproduce
(Not applicable)

## Possible Fix
See *expected behaviour*

## Your Environment
* Sitecore Version: 9.2
* JSS Version: 12.0.0
* Browser Name and version: Not applicable
* Operating System and version (desktop or mobile): Windows 10 (desktop)
* Link to your project (if available): Not available (private repo)

**Comment by sc-illiakovalenko** [comment]
@thany Implemented in #485
