### ISSUE TITLE
[Bug] [JSS 13/14] Warning messages starting local proxy server

### ISSUE THREAD

**Issue by bouncehead13** [Sitecore/jss#424]
## Description
Starting the proxy server now throws warning messages upon starting. I used the sample Angular app to confirm, but I initially noticed it in our own application upgrading from 13.0.0 to 13.2.0.

The sample Angular app outputs the following
```
Media field value {"resolvedFromItemId":"styleguide-item-link-field-shared-1","displayName":"Styleguide Item Link Item 1 (Shared)","template":"Styleguide-ItemLink-Item-Template","fields":[{"name":"textField","value":"ItemLink Demo (Shared) Item 1 Text Field"}],"name":"Item1"} did not have an expected 'src' property. Its media item will not be deployed.
```

## Expected behavior
There should be no warning messages

## Steps To Reproduce
1. Install the packages
2. Run `npm run start:proxy`

## Possible Fix
The bug seems to be introduced by commit https://github.com/Sitecore/jss/commit/4385791240447ad3cbf8582ca7ace76e7dfcb241#diff-2b4effeabec8751073221c37a6b05636 and tied to PR https://github.com/Sitecore/jss/pull/285

The commit referenced above seems to assume if the field is a single value, it should be added.
```
if (!Array.isArray(field.value)) {
  return [getMediaFieldValue(field)];
}
```
However, it should follow the adjacent reduce function and reprocess the found field.

## Your Environment
* Sitecore Version: 9.3
* JSS Version: 13.2.0

## Request
It would be great is this could be patched into 13.X.X in addition to 14.X.X. We are not ready to upgrade to Release 14.

**Comment by sc-illiakovalenko** [comment]
@bouncehead13 Fixed in #483 . Will release JSS 15.0.1. For now it's under consideration about providing this fix to JSS 13/14.
