### ISSUE TITLE
[Question] How to update SSR to use renderToNodeStream?

### ISSUE THREAD

**Issue by alex-kisimov** [Sitecore/jss#425]
Newer versions of react provide a new rendering method for SSR: `renderToNodeStream` which can improve TTFB. 

We're looking to replace the `renderToStringWithData` method in `server.js` with one that still completes GrahpQL queries but outputs a node stream rather than `renderToString` which it's currently doing. 

Creating a custom function that uses Apollo's `getMarkupFromTree` and the new `renderToNodeStream` method was unsuccessful. 

We're using the headless app provided by samples/node-headless-ssr-proxy and are currently unsure of what changes need to be done in it.

Is there a way to achieve this currently?

**Comment by aweber1** [comment]
This is a limitation of React (and somewhat Apollo). While React has `renderToNodeStream`, it does not have async rendering during SSR. Therefore, components that rely on Apollo (or any other fetched data) can't "wait" for data _during_ the rendering process. Data must be fetched _before_ SSR begins. Apollo does this by making two passes through your app: the first pass is to identify GraphQL queries and then execute those queries to populate the data cache; the second pass renders the app (with cached data) to HTML string.

React `Suspense` promises to deliver async rendering, but it is still experimental and does not currently support SSR (as far as I know). And I have to imagine that async rendering _and_ rendering to a stream is quite complicated, so it will be interesting to see if that is a supported scenario whenever `Suspense` is finalized.

There are two libraries (potentially more) that might be worth investigating : 

* https://formidable.com/open-source/react-ssr-prepass/
This library claims to function with `renderToNodeStream` and Apollo, but still requires a two-pass approach. It is also considered experimental and there are likely limitations.

* https://github.com/overlookmotel/react-async-ssr
This library claims to enable a single-pass approach to rendering on the server. However, it does not support streaming rendering and may require application code changes to function properly.

**Comment by alex-kisimov** [comment]
Thanks a lot for the info, this was helpful.
