### ISSUE TITLE
sitecoreContext is not hydrated during server side rendering in integrated mode

### ISSUE THREAD

**Issue by seanpeters-alinta** [Sitecore/jss#426]
## Description
We are in the process of updating our sitecore solution to version 9.3 with JSS v13.

When running in Integrated mode on our servers, we find that the sitecoreContext object is not being hydrated.

This appears to happen only during server side rendering and in integrated mode.  E.g. We do not see this issue when client side rending is used, or in connected developer mode.

We also don’t see this issue when the same code is running with sitecore 9.1.1 with JSS v11.

## Expected behavior
We expect the sitecoreContext to be hydrated similar to the behavior we see during client side rendering or when using sitecore 9.1.1 with JSS 11.

## Steps To Reproduce
1. Install Sitecore 9.3 (vanilla installation) with JSS 13.
2. Download, build and deploy the sample react app (https://github.com/Sitecore/jss/tree/dev/samples/react)
3. Run the app in integrated mode and add any existing component that uses sitecoreContext props to the start page.
4. Load the page by using server side rendering (refresh the URL)
5. The component has a sitecoreContext with only one prop (pageEditing: false) all other expected props are not hydrated.

## Possible Fix
No known fix

## Description
We are in the process of updating our sitecore solution to version 9.3 with JSS v13.

When running in Integrated mode on our servers, we find that the sitecoreContext object is not being hydrated.

This appears to happen only during server side rendering and in integrated mode.  E.g. We do not see this issue when client side rending is used, or in connected developer mode.

We also don’t see this issue when the same code is running with sitecore 9.1.1 with JSS v11.

## Expected behavior
We expect the sitecoreContext to be hydrated similar to the behavior we see during client side rendering or when using sitecore 9.1.1 with JSS 11.

## Steps To Reproduce
1. Install Sitecore 9.3 (vanilla installation) with JSS 13.
2. Download, build and deploy the sample react app (https://github.com/Sitecore/jss/tree/dev/samples/react)
3. Run the app in integrated mode and add any existing component that uses sitecoreContext props to the start page.
4. Load the page by using server side rendering (refresh the URL)
5. The component has a sitecoreContext with only one prop (pageEditing: false) all other expected props are not hydrated.

## Possible Fix
No known fix

## Your Environment
* Sitecore Version: Sitecore 9.3
* JSS Version: JSS 13.2
* Browser Name and version: Chrome - Version 84.0.4147.105
* Operating System and version (desktop or mobile): Windows 10
* Link to your project (if available): https://github.com/Sitecore/jss/tree/dev/samples/react

## Screenshots

serverSideRendering.png - shows sitecoreContext in an error state, it has not been hydrated and thus causes a crash in the code.

![serverSideRendering](https://user-images.githubusercontent.com/59859717/89003923-5ffeea80-d344-11ea-809d-d244795d6505.png)

clientSideRendering.png - shows sitecoreContext behaving as expected, it has all its props.
![clientSideRendering](https://user-images.githubusercontent.com/59859717/89003928-61c8ae00-d344-11ea-9387-17b27be529f4.png)

**Comment by sc-illiakovalenko** [comment]
@seanpeters-alinta It will be fixed in JSS 15.
But for now you can apply next fix:

Try to apply next changes to files:

**------ RouteHandler.js:**
Add function:
```
export function getServerSideRenderingState() {
  return ssrInitialState;
}
```
Remove piece of code from constructor of **RouteHandler** class:
```
    if (ssrInitialState && ssrInitialState.sitecore && ssrInitialState.sitecore.route) {
      // set the initial sitecore context data if we got SSR initial state
      SitecoreContextFactory.setSitecoreContext({
        route: ssrInitialState.sitecore.route,
        itemId: ssrInitialState.sitecore.route.itemId,
        ...ssrInitialState.sitecore.context,
      });
    }
```
**------ AppRoot.js**

Somewhere on top:

```
import RouteHandler, {getServerSideRenderingState} from './RouteHandler';
```

Add lines before return keyword in **AppRoot** function:
```
  const ssrInitialState = getServerSideRenderingState();

  if (ssrInitialState && ssrInitialState.sitecore && ssrInitialState.sitecore.route) {
    // set the initial sitecore context data if we got SSR initial state
    SitecoreContextFactory.setSitecoreContext({
      route: ssrInitialState.sitecore.route,
      itemId: ssrInitialState.sitecore.route.itemId,
      ...ssrInitialState.sitecore.context,
    });
  }
```
So you will setup correct sitecoreContext right before render of RouteHandler and another nested components.
Feel free to reopen issue, if it will not help you
