### ISSUE TITLE
imageParams on Image react component don't play nice with allowedMediaParams

### ISSUE THREAD

**Issue by ssartell** [Sitecore/jss#428]
## Description
The adding the same values to imageParams in an Image component and allowedMediaParams in a patch config does not result in an image getting sized correct. The original media URL coming from the layout service includes original h/w/iar/hash parameters that aren't getting cleared when mediaApi.updateImageUrl gets called. This appears to have changed as part of issue #172 and PR #275 .

## Expected behavior
Passing in the exact same parameters to imageParams and allowedMediaParams should result in an image getting sized correctly.

## Steps To Reproduce
1. Create an Image instance with imageParams.
2. Add the exact same imageParams to the allowedMediaParams patch config.
3. Look at the rendered image to see if it's sized correctly based on the params.

## Possible Fix
Revert the change to the mediaApi.

**Comment by sc-illiakovalenko** [comment]
@ssartell Fixed in #449. Will be released in JSS 15
