### ISSUE TITLE
Bad YAML formatting error is not shown in console output

### ISSUE THREAD

**Issue by alexshyba** [Sitecore/jss#43]
Using TP4, working disconnected.

When running `jss start` with a badly formatted YAML, the CLI shows the error as expected.
However, when messing up your YAML while the disconnected LS service watch is active, the error isn't thrown and the route comes back as 404, which could cause some head scratching.
`[LAYOUT] Layout for route '/my-page' was not defined. Returning 404.`

**Comment by kamsar** [comment]
Chatted about this on Slack and it was not reproducible. Added an extra validity check to catch some other indent errors though.
