### ISSUE TITLE
Guides RFC - #1 Thinking in JSS

### ISSUE THREAD

**Issue by anastasiya29** [Sitecore/jss#432]
### RFC background
We have published the 1st version of [JSS Guides & Recommended Practices](https://jss-docs-preview3.herokuapp.com/guides/). This content will ultimately be merged into the JSS Documentation site, and we'd love for the community to be a part of this milestone. We welcome your feedback, questions, change suggestions, and additional content.

### Category - Thinking in JSS
We’ve create GitHub issues for the 7 topic categories to facilitate group discussion - this issue is for discussing the **Thinking in JSS** category.

Topics in this category:

- [JS apps vs JSS apps](https://jss-docs-preview3.herokuapp.com/guides/thinking-in-jss/js-vs-jss/)
- [Sitecore Terminology & Concepts](https://jss-docs-preview3.herokuapp.com/guides/thinking-in-jss/terminology/)
- [Project Structure](https://jss-docs-preview3.herokuapp.com/guides/thinking-in-jss/project-structure/)
- [Developer Workflows](https://jss-docs-preview3.herokuapp.com/guides/thinking-in-jss/developer-workflows/)

### How to contribute

- Post your comments here, or
- [Use this link](https://github.com/Sitecore/jss/pull/431/files?file-filters%5B%5D=.md&w=1) to leave inline comments in the markdown files, or
- Use the `Edit this on GitHub` link at the bottom of each guide page to submit edits for specific pages, or
- Submit pull requests to the [`guides` branch](https://github.com/Sitecore/jss/tree/guides)

---
[Go to next category :arrow_right:](https://github.com/Sitecore/jss/issues/433)

**Comment by nickwesselman** [comment]
From AF on Twitter:
> This section includes content for ✨front-end developers✨ who are working with #SitecoreJSS without previous #Sitecore experience, based directly on dev feedback from real projects.

Perhaps we need to make the audience for each guide section explicit?

**Comment by jst-cyr** [comment]
On the "[Thinking in JSS -> JSS vs JSS]( https://jss-docs-preview3.herokuapp.com/guides/thinking-in-jss/js-vs-jss/)" page the "Edit this page on GitHub" link goes to the wrong page.

Instead of going to the js-vs-jss it goes to the terminology page.

**Comment by jst-cyr** [comment]
Regarding the [JSS vs JS page](https://github.com/Sitecore/jss/blob/guides/docs/data/routes/guides/thinking-in-jss/js-vs-jss/en.md), from [Matt Fletcher on LinkedIn](https://www.linkedin.com/feed/update/urn:li:activity:6704757818714673152?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6704757818714673152%2C6704877018149855232%29):

> Saw a “todo” in the hybrid section, not sure if its intentional for further additions or not:

**Comment by ThomPuiman** [comment]
Some comments with regards to Thinking in JSS:

- Developer Workflow has a typo: 'Reducing risk in log-term Code-First development' and 'Sitecore devs are free to reogranize templates'
- Sitecore Terminology typo: 'Presentations Details' with s
- Should the concept of Dictionary be included in Sitecore Terminology?
- I'm not entirely sure whether this should be the responsibility of a frontend dev, but considering they'll be the ones initially defining the components and templates, should there be some best practices about insert options/placeholder settings (allowed controls). Or would this be a task that generally the Sitecore/backend dev does ones the project is Sitecore First?
- I think it should also be mentioned that naming of components and templates should be done with the Content Author/Business User in mind, considering the JSS devs will determine the component names.

**Comment by sc-CalvinWilliams** [comment]
I found what seems like malformed bullet points [https://www.screencast.com/t/GeljsjM8](https://www.screencast.com/t/GeljsjM8) in the "js vs jss" section


Found a small typo [https://jss-docs-preview3.herokuapp.com/guides/thinking-in-jss/developer-workflows/#reducing-risk-in-log-term-code-first-development:~:text=needs.-,Reducing%20risk%20in%20log%2Dterm%20Code%2DFirst%20development](https://jss-docs-preview3.herokuapp.com/guides/thinking-in-jss/developer-workflows/#reducing-risk-in-log-term-code-first-development:~:text=needs.-,Reducing%20risk%20in%20log%2Dterm%20Code%2DFirst%20development)
		log-term -> long-term

Also a weird character(emoji?) does not render [https://www.screencast.com/t/hVCLWHbrNv8](https://www.screencast.com/t/hVCLWHbrNv8) 
both in the "Developer Workflows" section
