### ISSUE TITLE
Guides RFC - #6 GraphQL

### ISSUE THREAD

**Issue by anastasiya29** [Sitecore/jss#437]
### RFC background
We have published the 1st version of [JSS Guides & Recommended Practices](https://jss-docs-preview3.herokuapp.com/guides/). This content will ultimately be merged into the JSS Documentation site, and we'd love for the community to be a part of this milestone. We welcome your feedback, questions, change suggestions, and additional content.

### Category - GraphQL
We’ve create GitHub issues for the 7 topic categories to facilitate group discussion - this issue is for discussing the **GraphQL** category.

Topics in this category:

- [Guide to Extending GraphQL](https://jss-docs-preview3.herokuapp.com/guides/graphql/extending-graphql/)
- [GraphQL Security Guide](https://jss-docs-preview3.herokuapp.com/guides/graphql/graphql-security/)
- [Query Recipes](https://jss-docs-preview3.herokuapp.com/guides/graphql/query-recipes/)
- [More resources](https://jss-docs-preview3.herokuapp.com/guides/graphql/)

### How to contribute

- Post your comments here, or
- [Use this link](https://github.com/Sitecore/jss/pull/431/files?file-filters%5B%5D=.md&w=1) to leave inline comments in the markdown files, or
- Use the `Edit this on GitHub` link at the bottom of each guide page to submit edits for specific pages, or
- Submit pull requests to the [`guides` branch](https://github.com/Sitecore/jss/tree/guides)

---

[:arrow_left: Go to previous category](https://github.com/Sitecore/jss/issues/436) -----  [Go to next category :arrow_right:](https://github.com/Sitecore/jss/issues/438)

**Comment by AlexKasaku** [comment]
These are all under the section of disabling GraphiQL in Production:

```
<graphiql role:require=“ContentDelivery”>false</graphiql>
<enableSchemaExport role:require=“ContentDelivery”>false</enableSchemaExport>
<enableStats role:require=“ContentDelivery”>false</enableStats>
<enableCacheStats role:require=“ContentDelivery”>false</enableCacheStats>
<disableIntrospection role:require=“ContentDelivery”>true</disableIntrospection>
```

But are they all related to graphiql, or just the first line? If the others aren't, perhaps separate them with additional note on what is being disabled and why?

**Comment by AlexKasaku** [comment]
As GraphQL relates to the LayoutService and can be consumed outside of JSS - e.g. the aspnetcore rendering host - is it worth considering if this documentation belongs to JSS or sits outside of it? If it is part of JSS docs, an immediate question would be - _does this only apply to JSS, or does it equally apply to aspnet core?_

I've picked GraphQL as an example there but this likely applies to other areas too. Anything that sits under JSS docs may be missed when it equally applies elsewhere and would be helpful. This seems like a good opportunity to avoid confusion going forward - as it wouldn't be great to have to sift through JSS docs for aspnet core and working out what does apply and what doesn't.
