### ISSUE TITLE
Guides RFC - #7 WIP

### ISSUE THREAD

**Issue by anastasiya29** [Sitecore/jss#438]
### RFC background
We have published the 1st version of [JSS Guides & Recommended Practices](https://jss-docs-preview3.herokuapp.com/guides/). This content will ultimately be merged into the JSS Documentation site, and we'd love for the community to be a part of this milestone. We welcome your feedback, questions, change suggestions, and additional content.

### Docs vs Guides
During this project we realized that although it seems beneficial to separate `docs` and `guides`, the current `docs` already contain some guide-style content. So we're not sure if this is a good idea. What do you think? Do you like the separation? Would you be ok with some pages from `docs` moving to `guides`, thereby breaking some existing URLs?

If you like the idea of keeping them separate, **how do you differentiate docs and guides in your mind**? Help us come up with a clear definition that will help us organize the content better for you.

### Category - Work in Progress... and beyond
We’ve create GitHub issues for the 7 topic categories to facilitate group discussion - this issue is for discussing the **Work in Progress** category. **This is a special issue because this is where we want to hear about additional topics** that you think should be in guides. What did we miss? What needs more content? (Ordering by priority would be appreciated)

**Topics in this category**:

- [Deployment Topologies](https://jss-docs-preview3.herokuapp.com/guides/wip/deployment-topologies/)
- [Migration Guide](https://jss-docs-preview3.herokuapp.com/guides/wip/migration-guide/)

### How to contribute

- Post your comments here, or
- [Use this link](https://github.com/Sitecore/jss/pull/431/files?file-filters%5B%5D=.md&w=1) to leave inline comments in the markdown files, or
- Use the `Edit this on GitHub` link at the bottom of each guide page to submit edits for specific pages, or
- Submit pull requests to the [`guides` branch](https://github.com/Sitecore/jss/tree/guides)

---

[:arrow_left: Go to previous category](https://github.com/Sitecore/jss/issues/437)

**Comment by joostmeijles** [comment]
> _tant to you_) - Federated Authentication with JSS

I would love to see an example (preferably including a reference example using Sitecore Identity) that explains how Federated Authentication and JSS in headless mode works. 

The current documentation (https://jss.sitecore.com/docs/techniques/authentication/federated-auth) only describes integrated mode and almost suggests that this mode is preferred when using Federated Authentication.

**Comment by 8or15** [comment]
Not completely sure if this belongs in a migration guide: a step by step guide for a couple of standard scenarios more tailord to React/Angular/Vue developers would be nice, for example:
1. A guid to Use Sitecore JSS with your existing app to get your labels and content managed (item access via GraphQL)

1. Add placeholders & content to your existing NextJS  or NuxtJS project.
