### ISSUE TITLE
JSS Placeholder Sequence

### ISSUE THREAD

**Issue by jitendra-ps** [Sitecore/jss#443]
## Description
I have two Placeholders in my code 
1) jss-main - To render components
2) yi-static - For static things (like set data in browser's localstorage)

```js
<ConditionalStaticPlaceholder name="yi-static" rendering={data}  />
<Placeholder name="jss-main" rendering={data} />
```

Problem: How can I call Placeholders in sequence and synchronous. So my localstorage data should be set in the browser first and then components should be rendered. But in the current scenario "yi-static" is called after "jss-main" means localstorage data set after components render.

## Expected behavior
"yi-static" Placeholder should be called first
"jss-main" Placeholder should be called second after first complete his job (set data in localstorage)

**Comment by nickwesselman** [comment]
This seems like a React state management issue vs a JSS issue, right? Feel free to reopen if there is a specific change in JSS that you think is needed to support this.
