### ISSUE TITLE
Documentation for Content Translation has unfinished sentence

### ISSUE THREAD

**Issue by chorpo** [Sitecore/jss#445]
## Description
At the very end of this documentation article https://github.com/Sitecore/jss/blob/dev/docs/data/routes/docs/techniques/content-translation/en.md right before "Headless Mode / Layout Service Proxying" section there is sentence which is not finished.

## Expected behavior
Documentation is full :-)

## Steps To Reproduce
1. Go to https://github.com/Sitecore/jss/blob/dev/docs/data/routes/docs/techniques/content-translation/en.md 
2. Scroll down to 'Headless Mode / Layout Service Proxying' section
3. See this unfinished sentence "Note: jss deploy items does not deploy files. To deploy files as well,"

**Comment by sc-illiakovalenko** [comment]
@chorpo Added doc update in #480
