### ISSUE TITLE
Can't get the right Insert Options to import in code-first

### ISSUE THREAD

**Issue by alexshyba** [Sitecore/jss#45]
TP4.
Have two templates:
```
export default function(manifest) {
  manifest.addTemplate({
    name: "news",
  });
}
```
and 
```
export default function(manifest) {
  manifest.addTemplate({
    name: "news-folder",
    insertOptions: ["news"]
  });
}
```

Based on the configuration above, I expect the all items created from `news-folder` to have insert options containing the `news` template.

While the manifest appears to resolve this correctly:
```
 {
      "name": "news-folder",
      "insertOptions": [
        "news"
      ],
      "route": false,
      "defaultRoute": false
    },
```

This is what gets generated during import. As you can see, the `News Folder` item has `news-folder` template instead of `news` assigned in insert options:
![image](https://user-images.githubusercontent.com/900910/44560188-3b834800-a703-11e8-8d45-e0d96ff82ec0.png)

It's important to note that the import sets expected template on `__Standard Values`:
![image](https://user-images.githubusercontent.com/900910/44560291-df6cf380-a703-11e8-93f4-d1c12e920b77.png)

So it seems like the assignment of the Insert Options on the item level shouldn't be happening during import.

**Comment by kamsar** [comment]
This will be fixed in GA. Insert options control will be entirely in the control of the manifest author, both for items like this as well as route items.

As a temporary workaround, resetting the insert options field on the manifest-spawned item will return it to the correct standard values value.
