### ISSUE TITLE
Vulnerability in yargs-parser used by sitecore-jss-rendering-host

### ISSUE THREAD

**Issue by girlcheese** [Sitecore/jss#458]
## Description
Security review of our project with a client shows vulnerabilities in yargs-parser, inherited from webpack-dev-server@3.8.2 in sitecore-jss-rendering-host@14.

## Expected behavior
yargs-parser version in use should be the same peer-dependency as other packages in the jss solution (15.0.1 or other version including the fix), not one of the vulnerable versions.

## Steps To Reproduce
https://snyk.io/vuln/SNYK-JS-YARGSPARSER-560381

## Possible Fix
Package sitecore-jss-rendering-host needs to be updated to 3.11.X which doesn't use the vulnerable dependency.

## Your Environment

* Sitecore Version: 9.3
* JSS Version: 14
* Browser Name and version: All
* Operating System and version : n/a
* Link to your project : private

## Screenshots
![Screenshot 2020-09-25 at 10 21 46](https://user-images.githubusercontent.com/1913270/94250343-01578680-ff19-11ea-9844-88028cf4fd37.png)

**Comment by sc-illiakovalenko** [comment]
@girlcheese Fixed in #464 [here](https://github.com/Sitecore/jss/pull/464/files#diff-953e7de87237a78b16658fa1f1269c4cd339baeeb513842e7b965bfde71f959d). Will be released in JSS 15
