### ISSUE TITLE
FR: ability to specify item template definitions for ContentList fields "inline"

### ISSUE THREAD

**Issue by alexshyba** [Sitecore/jss#46]
Currently the linkage between ContentList field and referenced items is established via a naming convention, which is user error prone. It would be great to have a way of specifying item template for the ContentList field "inline", for example:

```
manifest.addComponent({
    name: 'Pricing',
    fields: [
      {
        name: 'items',
        displayName: 'Items',
        type: CommonFieldTypes.ContentList,
		itemTemplate: {
			name: 'Pricing-items-Item',
			icons: SitecoreIcon.InvoiceDollar,
			fields: [
			  {
				name: 'status',
				displayName: 'Status',
				type: CommonFieldTypes.SingleLineText
			  },
			  {
				name: 'active',
				displayName: 'Actice',
				type: CommonFieldTypes.Checkbox
			  },
			  {
				name: 'title',
				displayName: 'Title',
				type: CommonFieldTypes.SingleLineText
			  },
			  {
				name: 'price',
				displayName: 'Price',
				type: CommonFieldTypes.SingleLineText
			  },
			  {
				name: 'link',
				displayName: 'Link',
				type: CommonFieldTypes.GeneralLink
			  }
			]
		  };
      }
    ]
  });
```

**Comment by kamsar** [comment]
The linkage can default to using the naming convention but the examples are all explicitly specifying the template name for each item, which is less prone to error:

https://github.com/Sitecore/jss/blob/a137e11f39982adb7f0ad9284e16a171c337d990/samples/react/data/routes/styleguide/en.yml#L152

With explicit template specification, the fact that a default naming convention even exists is somewhat undocumented. There's also nothing forcing a user to have a singular template for all linked items, which template spec'ing makes clear.
