### ISSUE TITLE
FR: quantify field ContentList field type

### ISSUE THREAD

**Issue by alexshyba** [Sitecore/jss#47]
Not 💯 certain if it's possible now. ContentList fields are created as Treelist fields. It would be great to have a way to specify the "flavor", so developers can pick `Multilist` field instead.

**Comment by kamsar** [comment]
It Just Works (source: tried it with react just now)

See note here: https://jss.sitecore.net/docs/techniques/working-disconnected/manifest-api#commonfieldtypes simply use the field type string literal.
