### ISSUE TITLE
Doc: manifest.setDefaultRouteType vs. manifest.addRouteType

### ISSUE THREAD

**Issue by alexshyba** [Sitecore/jss#49]
`manifest.setDefaultRouteType` appears to be undocumented. Would be great to add a note on the diff between two methods.

**Comment by kamsar** [comment]
This has been fixed. JSDoc existed, but was in the wrong place to have Code pick it up.

FWIW, `setDefaultRouteType()` directly modifies the app route template that import generates; all other route types inherit from the default route type.
