### ISSUE TITLE
Missing null-check in RouteHandler.js

### ISSUE THREAD

**Issue by overtune** [Sitecore/jss#492]
Hi!

I stumbled upon an error (possible a consequential error of another issue).
The error I got was "Cannot read property 'sitecore' of null" and it was triggered on line 114 on `jss/samples/react/src/RouteHandler.js`.

If you check the code there the logic seems incorrect. Because it checks `routeData !== null && routeData.sitecore && routeData.sitecore.route` and if that is false it goes ahead and still use `routeData.sitecore.context` on the else block.

https://github.com/Sitecore/jss/blob/2a2b87e31825b583cf27ea210731decf22715c75/samples/react/src/RouteHandler.js#L114

**Comment by sc-illiakovalenko** [comment]
@overtune Fixed in #506
