### ISSUE TITLE
Typescript implementation

### ISSUE THREAD

**Issue by edouardr** [Sitecore/jss#5]
Hi Team,

This is an enhancement request more than an issue.

I was wondering if we could look into using Typescript as the main language for this project.

I believe, the first aim with JSS is to get FrontEnd devs to work with Sitecore. For this, plain ES6 Javascript is great and I have nothing against it. However, Sitecore developers are by nature .NET / Backend devs.

With Typescript the transition to JSS would, IMO, be simpler. It is also becoming a standard: React supports it, Angular was written with it and Vue is getting support for it.

This would required to have a @typings definition for @sitecore-jss/sitecore-jss-dev-tools.

I would be happy to help with this.

**Comment by aweber1** [comment]
Hi @edouardr, 

It's doubtful that we'll transition the JSS packages to Typescript. And there's nothing preventing devs from using Typescript in their projects and still leveraging / importing the JSS packages.

That said, we do recognize the benefits that Typescript aims to provide and understand why some devs would gravitate towards it. With that in mind, we have tasks in the backlog to provide Typescript typings (and likely Flow definitions also) for the various JSS packages. The overall goal of these tasks is to improve tooling support for JSS and enhance the dev experience.

Thanks for the feedback and we appreciate the offer to help! And hopefully if our open-sourcing plans come to fruition we can take you up on the offer :)

**Comment by sitecorian** [comment]
Hello, @edouardr, thanks for the input! Feel free to +1 the feature request here:
https://feathub.com/Sitecore/jss/+3
