### ISSUE TITLE
FR: add case sensitivity to manifest check for field definition presence 

### ISSUE THREAD

**Issue by alexshyba** [Sitecore/jss#50]
Related to the user error in #48. Would be fantastic to have `jss manifest` fail if the field name (for ex: `itemLink`) doesn't match name in field definition (for ex: `itemlink`) the same as it currently righteously fails when adding a field that doesn't exist on the component/template:
```
Error generating manifest home-jss-main-ContentBlock-1 route datasource defined data for 'logo' on component ContentBlock. This field is not defined on this component. It may be a typo, or the field may need to be added to the component definition.
```

This will help catch the user errors during manifest gen and therefore before import process starts.

**Comment by kamsar** [comment]
Took this internally as a nice to have.
