### ISSUE TITLE
jss deploy job does not exit on success

### ISSUE THREAD

**Issue by trolleyyy** [Sitecore/jss#502]
Hello,
in my local Sitecore instance when the deploy job is finished - unfortunately process does not exit.

It is definetely related to locale language 'da'. Output from command line:
```
Reloaded all GraphQL schemas.
Job afsluttet: JSSImport-my-app- (enheder behandlet:)
```

I guess it is related to: https://github.com/Sitecore/jss/blob/master/packages/sitecore-jss-dev-tools/src/package-deploy.ts line `130`
The text: `Job ended:` seems to be unmatched with locale string `Job afsluttet:`.

**Comment by sc-illiakovalenko** [comment]
Created backlog item for it. Need to add a separate key (boolean value) in order to not depend on languages.
