### ISSUE TITLE
Cannot create react-native app

### ISSUE THREAD

**Issue by RobsonAutomator** [Sitecore/jss#504]
## Description
I just run
>jss create mobileapp react-native
After downloading the project from GitHub the following error is displayed.
![image](https://user-images.githubusercontent.com/831971/101018175-69ef5f00-356b-11eb-8ed5-ee2bf9ae3c23.png)

I can for example create a react application without any issue
jss create react-app react

## Expected behavior
react-native application should be created properly.

**Comment by sc-illiakovalenko** [comment]
@RobsonAutomator I did `jss create name react-native` and it finished successfully. Can you try to do it again? If you have same issue, please provide more information about your OS, etc...

**Comment by RobsonAutomator** [comment]
I tested on the following system : Windows 10 Enterprise 2004, OS build 19041.630, Node v15.3.0, npm 7.0.14 

When I install Node v14.15.1 I was able to create a react-native app. Now I'm trying to run the app in the emulator.

**Comment by sc-illiakovalenko** [comment]
@RobsonAutomator Please, use Node.js LTS version. It's a problem of peer dependencies in `sitecore-jss-react-native` package and `react-native` sample. Fixed in #507
