### ISSUE TITLE
@sitecore-jss/sitecore-jss optimization bailout

### ISSUE THREAD

**Issue by EvtK** [Sitecore/jss#519]
## Description
Apparently, the Sitecore-JSS-Angular module, cannot resolve the Sitecore-Jss module as an esm module:

Warning: /angular/node_modules/@sitecore-jss/sitecore-jss-angular/__ivy_ngcc__/dist/esm2015/public_api.js depends on '@sitecore-jss/sitecore-jss'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

## Expected behavior
Angular should not throw warnings on this (of course they can be suppressed), but instead should be able to load the sitecore-jss module as esm. 

## Steps To Reproduce
This can be easily reproduced when loading the sample app.

**Comment by ambrauer** [comment]
@EvtK I've added a backlog item to address this. As you mention, you can suppress (and in fact [is in the latest version](https://github.com/Sitecore/jss/commit/67722ea01b9edcfa063a3255702f490612e30258#diff-5eafa5ceceb0af4b3cc7e1cb840bdbe89f24ffa1ee5713e53476e93f7a3cbd28R29)), but we should ideally compile and publish both CommonJS and ESM versions of the `sitecore-jss` package to allow optimization.

**Comment by EvtK** [comment]
Hi @ambrauer thanks for the quick response and putting it on the backlog. Yes I can see it is fixed in the sample app, but ofcourse for our corporate angular projects we have to manually supress these (running NX with 40+ apps :) ). 

Looking forward to the fix!

**Comment by EvtK** [comment]
Hi @ambrauer is there any progress on this issue? Hope to hear, thanks.

**Comment by ambrauer** [comment]
Hi @EvtK we're aiming to fit this in for JSS v19, which is slated for release later this year.
