### ISSUE TITLE
Create custom App template on initial import

### ISSUE THREAD

**Issue by coreyasmith** [Sitecore/jss#54]
When you import an application, the root `App` item is based off of the `/sitecore/templates/JavaScriptServices/App` template. It'd be nice if a custom `App` template that derives from the base `/sitecore/templates/JavaScriptServices/App` template were created for you on initial import, similar to the custom `App Route` template.

It'd also be nice to be able to customize this item for the initial import--specify base templates you want it to inherit, item name, icon, etc.

**Comment by coreyasmith** [comment]
I've got a couple of base templates that I'm adding to the `App` template, like `_Error Handling` for a `Page Not Found Link` field, to handle server-side errors and other things. It'd be cool if I could create a `not-found` route while I'm working in disconnected mode, and tell JSS that my `App` item should add `_Error Handling` as a base template and use that `not-found` route for the `Page Not Found Link` field on initial import. 

Maybe an `app.yml` item could be defined under the `/data/content` folder? You could define `template` (is it possible to define multiple?), `icon` (🍄), and `fields`.

I know I can do all of this by creating a custom `App` template before the initial import and define that template as the `appTemplate` on my `<app />` in config, but that feels a bit too connected.

**Comment by kamsar** [comment]
tbh this sounds like pipeline customizations to the import process. The goal of import out of the box is to enable comping up a site, as opposed to complete serialization of final items - ergo, [extend import](https://jss.sitecore.net/docs/techniques/working-disconnected/extending-import) or serialize the items.
