### ISSUE TITLE
Custom React PropType for Fields

### ISSUE THREAD

**Issue by coreyasmith** [Sitecore/jss#56]
It'd be awesome for JSS to have a custom prop type for fields (and any other types that JSS commonly passes around, e.g., `sitecoreContext`).

Typing the following gets tedious for components that require a field prop:
```javascript
MyComponent.propTypes = {
  field: PropTypes.object.shape({
    value: PropTypes.any,
    editable: PropTypes.bool
  }).isRequired
}
```

This would be nice:
```javascript
import { PropTypes as JssPropTypes } from "@sitecore-jss/sitecore-jss-react";
...
MyComponent.propTypes = {
  field: JssPropTypes.field.isRequired
}
```

**Comment by kamsar** [comment]
While this is a good idea, I don't think we will ship it because it will increase the bundle size and not everyone uses proptypes (i.e. typescript + react users would use types for the same thing most likely).

A good module if you're looking for something to release yourself though.

**Comment by louis-pvs** [comment]
When speaking of bundle size, what bundle size are we talking about? was it bundle after build? if that's the case I think there is [a way to omit](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types) the 700b of size.

It would be really good to have a module/util to do this job, react-styleguidist able to extract propTypes from component as description.
![localhost_6060_ (1)](https://user-images.githubusercontent.com/7659194/66800054-54257180-ef46-11e9-835e-f237958c340e.png)
