### ISSUE TITLE
Package Deploy breaking

### ISSUE THREAD

**Issue by atulgarg22** [Sitecore/jss#608]
## Description

While deploying the app to Sitecore it breaks on status call.

Unexpected error processing reply from import status service: TypeError: Cannot read property 'forEach' of undefined
Response: Job started: JSSImport-MemberPortal-4:42:16 AM,[INFO] [JSS] - Importing MemberPortal as sitecore\JssImport,[INFO] [JSS] - Import database is master,[INFO] [JSS]

TypeError: Cannot read property 'forEach' of undefined
    at C:\Project\node_modules\@sitecore-jss\sitecore-jss-dev-tools\dist\package-deploy.js:235:42
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

## Expected behavior

Package should get deployed.

## Steps To Reproduce

1. Go to Command prompt
2. run the command "jss deploy app -c -d"
3. See error

## Your Environment

* Sitecore Version: 10.0.1
* JSS Version: 16.0.0
* Browser Name and version: NA
* Operating System and version (desktop or mobile): Windows
* Link to your project (if available):

**Comment by ambrauer** [comment]
Hi @atulgarg22 - 

JSS Version 16.0 is only compatible with Sitecore Version 10.1. For Sitecore Version 10.0.1, you'll need to use JSS Version 14 or 15. 
Please refer to [Sitecore modules compatibility table](https://kb.sitecore.net/articles/541788) for details.

Thanks
