### ISSUE TITLE
IncludeServerInMediaUrls Incompatible with Headless SSR Proxy

### ISSUE THREAD

**Issue by coreyasmith** [Sitecore/jss#62]
By default, the `jss` Layout Service configuration has `IncludeServerUrlInMediaUrls` set to `true`. It appears that this is required for media to get served while working in connected mode (I got proxy errors with it set to `false`). Indeed, [the docs state that it must be set to `true` when working in any mode other than Integrated][1]:

> _Include Server URL in Media URLs_ - This should always be checked, unless you are running your app in Integrated mode exclusively.

However, this setting causes issues when working with the SSR proxy. URLs for media items get generated with the CD hostname, so media requests bypass the SSR proxy and go straight to the CD.

Either the docs for the SSR proxy should be updated to reflect this requirement, or (ideally) the SSR proxy will automatically rewrite media URLs to remove the CD hostname.

[1]: https://jss.sitecore.net/docs/techniques/extending-layout-service/layoutservice-rendering-contents#choose-or-configure-a-builtin-rendering-contents-resolver

**Comment by coreyasmith** [comment]
Digging through the GraphQL (and other JSS) code, it looks like this is something the SSR proxy _should_ handle. For example, the `JssExtender` explicitly sets `Media.AlwaysIncludeServerUrl` to `true` when serializing fields:

```csharp
protected virtual string SerializeField(Field field, IGetFieldSerializerPipeline getFieldSerializerPipeline)
{
  using (new SettingsSwitcher("Media.AlwaysIncludeServerUrl", bool.TrueString))
    ...
  }
}
```

It'll be a bit painful if we have to discover all of these overrides and reimplement these classes ourselves for the headless proxy.

**Comment by kamsar** [comment]
Based on some discussion, here is the patch that will resolve this issue (note: breaks connected mode, so this is for prod only):

```
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/">
  <sitecore>
    <layoutService>
      <configurations>
        <config name="jss">
          <rendering>
            <renderingContentsResolver>
              <IncludeServerUrlInMediaUrls>false</IncludeServerUrlInMediaUrls>
            </renderingContentsResolver>
          </rendering>
        </config>
      </configurations>
    </layoutService>
  </sitecore>
</configuration>```
