### ISSUE TITLE
Next.js - use "next/image" Image Component within Sitecore JSS Image component

### ISSUE THREAD

**Issue by jln-dk** [Sitecore/jss#626]
## Describe the solution you'd like
Now that JSS supports Next.js, is it (or would it) be possible to use the `next/image` Image component within the Sitecore JSS Image component?

Since Next.js v10 the `next/image` Image component has built-in image optimizations for resizing, optimizing, and serving images in modern formats like WebP when the browser supports it. Having this within Sitecore JSS would be a major improvement. 

Link: https://nextjs.org/docs/basic-features/image-optimization

## Additional information
I already did some exploration with the ["JSS Next.js boilerplate"](https://github.com/Sitecore/jss/tree/master/samples/nextjs) code and found that the `next/image` Image component is not being used. No image optimizations was found. So this is more a question/feature request than an issue.

**Comment by adoprog** [comment]
Is there a plan on implementing it? This is essential for achieving high scores in Google Lighthouse.

**Comment by nickwesselman** [comment]
We have yet to implement this given some of the complexity of marrying Sitecore's built-in resizing capabilities with Next's. It's on our roadmap though, likely in v20 release, and we are open to input on what the implementation might look like.

**Comment by ambrauer** [comment]
Completed with #909
