### ISSUE TITLE
Headless SSR Proxy Doesn't Rewrite Cookie Domain

### ISSUE THREAD

**Issue by coreyasmith** [Sitecore/jss#63]
The SSR proxy doesn't rewrite cookie domains served up from CDs. Steps to reproduce:

1. Add `<httpCookies domain="domainofapihost.tld" />` to the `<system.web />` section of `Web.config` on the API host for the SSR proxy.
2. Browse to the site and note that no cookies get served to the end user.

In this case I'd expect the SSR proxy to rewrite the domain on the cookies so that they do get served.

**Comment by kamsar** [comment]
If you're going to pass cookies through a proxy, you should not be setting an explicit domain on them in the first place - same-origin cookies, without explicit domains or with higher level explicit domains (i.e. `foo.com` for `api.foo.com` and `www.foo.com`) should work fine.

If you totally must rewrite cookie domains, then something like this:

https://gist.github.com/kvetis/720643949e389a47f9b6443126fdb872#file-node-cookie-rewrite-proxy-js-L19

...in your `config.onProxyReq` function should enable you to transform the cookie data.

**Comment by jbreuer** [comment]
This might not be the correct place to ask this question, but it might be related.

I'm using federated authentication in Sitecore by writing my own identity provider based on this blog: http://blog.baslijten.com/enable-federated-authentication-and-configure-auth0-as-an-identity-provider-in-sitecore-9-0/. It connects to Azure B2C with OpenId Connect.

When a user tries to visit a protected page they are redirect to Azure B2C where they can login. This works on CM and CD and it creates a cookie named ".AspNet.Cookies".

Unfortunately I can't get this to work with the SSR Proxy. I can login on Azure B2C, but when I get redirected to the SSR Proxy I'm not logged in and I don't have the ".AspNet.Cookies" cookie. I tried to use the config.onProxyReq function to rewrite the domain, but I can't find the cookie in there.

Any idea how to solve this?

**Comment by NijasHameed** [comment]
> I can't get this to work with the SSR Proxy. I can login on Azure B2C, but when I get redirected to the SSR Proxy I'm not logged in and I don't have the ".AspNet.Cookies" cookie. I tried to use the config.onProxyReq function to rewrite the domain, but I can't find the cookie in there.

@jbreuer did you get any solution?
