### ISSUE TITLE
Question: can we pass full rendering data to factory?

### ISSUE THREAD

**Issue by shakyShane** [Sitecore/jss#650]
Hi 👋🏻 

Would there be any objections to passing the entire rendering data here (to the factory)? I have a situation where having the full layout data would help me decide which component to return.

https://github.com/Sitecore/jss/blob/c33b1f52281bb42f316ff720dcfe48e9c1936ce2/packages/sitecore-jss-react/src/components/PlaceholderCommon.tsx#L192

**Comment by nickwesselman** [comment]
Hi @shakyShane 👋

Can you elaborate more on the use case for this?
