### ISSUE TITLE
Unexpected error processing reply from import status service: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by M4tZheng** [Sitecore/jss#652]
### Environments
1. Fresh new Sitecore 9.3 locally installed
2. Sitecore Javascript Service 13.0 installed
3. JSS SDK 13.0.5 installed
4. Scaffolding using [jss create jssvue vue]
### Issues
**1. JSS import encounters javascript errors**
2. But the sitecore templates and content items are generated
**3. @sitecore-jss/sitecore-jss-dev-tools is ^16.0.0 not compatible with my local 13.0.5, the scaffolding scripts always pick up the latest version**

### Expected behavior
1. No sitecore error either JSS javascript error when [jss deploy]
2. sitecore-jss versions should be ^13.0 not ^16.0 in package.json

## Screenshots

![image](https://user-images.githubusercontent.com/29937678/114827595-76c66e00-9dfb-11eb-9297-61d219f01c8a.png)
![image](https://user-images.githubusercontent.com/29937678/114827536-631b0780-9dfb-11eb-929a-13dac1a234cb.png)
![image](https://user-images.githubusercontent.com/29937678/114827699-9c537780-9dfb-11eb-983f-ec3d44a08422.png)

**Comment by nickwesselman** [comment]
Hi @M4tZheng -- Please use the `-b` or `--branch` argument to target the `release/13.0.0` branch, e.g.

```
jss create myproject vue --branch release/13.0.0
```
