### ISSUE TITLE
how to avoid generating <div> tag when using <placeholder>

### ISSUE THREAD

**Issue by M4tZheng** [Sitecore/jss#657]
Using Sitecore JSS **placeholder** tag will generate a **div**, which is different from developing with Sitecore MVC. Is there a way to avoid generating these **div** tags?
I followed Sitecore documentation: [JSS placeholder documentation][1]

Here is the code used and html generated:

## Promo Container
![image](https://user-images.githubusercontent.com/29937678/115515297-935d1d00-a2b7-11eb-8a0a-8ea985edc9c3.png)
`
<Placeholder name='app-promos' :rendering="rendering"/>
`
## Promo Card
[![enter image description here][2]][2]

## Page Layout YAML
    > placeholders:
          app-promos:
            - componentName: PromoCard
              fields:
                heading: PromoCard1
                image: 
                  src: /data/media/img/promo-card-1.jpg
                  alt: card1
                text: Card 1 desc...
                headline: Card 1
            - componentName: PromoCard
              fields:
                heading: PromoCard1
                image: 
                  src: /data/media/img/promo-card-2.jpg
                  alt: card2
                text: Card 2 desc...
                headline: Card 2
            - componentName: PromoCard
              fields:
                heading: PromoCard1
                image: 
                  src: /data/media/img/promo-card-3.jpg
                  alt: card3
                text: Card 3 desc...
                headline: Card 3

## Generated HTML
![image](https://user-images.githubusercontent.com/29937678/115512465-9c98ba80-a2b4-11eb-8eaa-4cc49f5f3c61.png)

# Even the JSS sample code has the non-sense **div** generated.

  [1]: https://jss.sitecore.com/docs/fundamentals/understanding-layout
  [2]: https://i.stack.imgur.com/V4leS.png

**Comment by nickwesselman** [comment]
@M4tZheng Can you let us know which JavaScript framework you are using?

**Comment by M4tZheng** [comment]
> @M4tZheng Can you let us know which JavaScript framework you are using?

vue js - release 13.0.0.
no issue there with react js 13.

**Comment by nickwesselman** [comment]
@M4tZheng In React we are able to use [Fragments](https://reactjs.org/docs/fragments.html) to avoid a wrapping div. [This capability was not added to Vue until Vue 3.x](https://v3.vuejs.org/guide/migration/fragments.html). We are planning to upgrade but do not have a committed release/date for this yet.

A workaround is to use the `SitecoreJssPlaceholderPlugin` as documented [here](https://jss.sitecore.com/docs/client-frameworks/vue/vue-placeholders).

**Comment by nickwesselman** [comment]
Fragment support will be introduced with Vue 3.x in the JSS 19.0 release. See #742.
