### ISSUE TITLE
Add targetId Field to Link and Reference Fields in GraphQL

### ISSUE THREAD

**Issue by coreyasmith** [Sitecore/jss#66]
The `MultilistFieldGraphType` has a nice `targetIds` field you can use to get just the IDs of the selected items in the field; however, for the `LookupFieldGraphType` and `ReferenceFieldGraphType`, you have to get the ID through the `targetItem`. It'd be nice if these two fields exposed a `targetId` field similar to the `MultilistFieldGraphType`.

**Comment by kamsar** [comment]
This will be in GM
