### ISSUE TITLE
Global Allowed Origins Required for Connected Mode POST Requests

### ISSUE THREAD

**Issue by coreyasmith** [Sitecore/jss#67]
It may be worth noting in the JSS docs that when working in connected mode, POST requests require that you have `http://localhost:3000` added to the global `<allowedOrigins />` configuration as follows:

```xml
<configuration>
  <sitecore>
    <api>
      <services>
        <configuration>
          <allowedOrigins>
            <origin>http://localhost:3000</origin>
          </allowedOrigins>
        </configuration>
      </services>
    </api>
  </sitecore>
</configuration>
```

Since CORS won't allow you to send data through headers (e.g., `sc_apikey`) for the `OPTIONS` pre-flight check, and you can't pass `sc_apikey` through the query string the above global exception is required.

Of course this should be patched out in production environments.

**Comment by kamsar** [comment]
you can pass a query string in a POST request in addition to the body data. That should obviate the need for this (i.e. `POST /foo/bar?sc_apikey=0xDEADBEEF`)

For example, the GM tracking API is using this technique and is all POST requests, and does not require changing global allowed origins.
