### ISSUE TITLE
FR: GetMultilistFieldSerializer - make item attributes configurable

### ISSUE THREAD

**Issue by alexshyba** [Sitecore/jss#69]
## Is your feature request related to a problem? Please describe.
The problem is that I need to render a NavLink to an item that comes back from the `MultilistFieldSerializer`, which is currently serializing `id` and `fields` props only.

## Describe the solution you'd like
Would be great to have ability to extend what's coming back on the item via configuration:
```
<processor type="Sitecore.LayoutService.Serialization.Pipelines.GetFieldSerializer.GetMultilistFieldSerializer, Sitecore.LayoutService" resolve="true">
      <Fields hint="list">
           <field id="1">name</fieldType>
           <field id="2">url</fieldType>
     </FieldTypes>
</processor>
```
Getting direct item properties like name, templateid, etc. is easier, but fields like `url` need to be computed, maybe it makes sense to keep a separate list of supported item field resolvers?

## Describe alternatives you've considered
Currently using item guid to build a link, which is not pretty :)

**Comment by aweber1** [comment]
Given the "unknown" nature of the fields/properties a dev might want from a given item in the multilist, I'm inclined to not make serializable field selection part of configuration. I can easily see the next feature request being: "I only want these fields for Y item template under Z item in the content tree".

That said, I think the MultilistFieldSerializer could be refactored a bit to make it easier to extend _only_ the code that serializes item properties/fields.

For example, currently the `MultilistFieldSerializer.Serialize` method has:
```
foreach (var item in items)
{
	writer.WriteStartObject();

	writer.WritePropertyName("id");
	writer.WriteValue(item.ID.Guid.ToString());

	writer.WritePropertyName("fields");
	writer.WriteRawValue(ItemSerializer.Serialize(item));
	writer.WriteEndObject();
}
```

Perhaps we refactor to:
```
foreach (var item in items)
{
  SerializeItem(item, writer);
}

...

protected virtual void Serializeitem(Item item, JsonTextWriter writer) {
 // override this method as needed
} 
```

A developer is likely also going to want to implement a custom `GetMultilistFieldSerializer` processor to return a specific multilist field serializer based on the "type" of item that the field is on. Echoing my earlier comment: "I only want these fields for Y item template under Z item in the content tree".

**Comment by aweber1** [comment]
In the forthcoming Sitecore 9.2 release, the multilist field serializer (and other field serializers) have been refactored to allow for more granular extension.
