### ISSUE TITLE
FormValues Template, Rendering data are missing in generated sitecore-import.json for client-side embedding

### ISSUE THREAD

**Issue by supadhyay01** [Sitecore/jss#698]
## Description

The sitecore-import.json generated for client-side embedding at "jss/samples/sitecore-embedded-jss-app/sitecore/", is missing templates, rendering and content related to FormValues. As such when I try to open Step-3 in Experience Editor, it throws error.

## Expected behavior

Step-3 should show the submitted FormValues but the related Sitecore data itself is missing leading to errors

## Steps To Reproduce

1. Configure Client-side embedding on a vanilla Sitecore instance as per https://jss.sitecore.com/docs/techniques/mvc-integration/client-side-embedding
2. Open Step-3 in Experience Editor
3. See error

## Possible Fix

Renaming placeholder from jss-main to jss-main1 for FormValues Rendering, disables the rendering and thus Step-3 can be loaded but this is just a workaround and not a fix

## Your Environment

* Sitecore Version: 10.1
* JSS Version: 16
* Browser Name and version: Chrome 90.0.4430.212
* Operating System and version (desktop or mobile): Windows 10 20H2
* Link to your project (if available):

## Screenshots

![JSSError2](https://user-images.githubusercontent.com/77049738/118892131-b9023400-b900-11eb-93cf-b92567e65dc4.png)

**Comment by sc-addypathania** [comment]
The Embedded app sample has been moved out to [here](https://github.com/Sitecore/headless-examples).
Feel free to open an issue there.
