### ISSUE TITLE
Insert Option missing on component folder after first deploy

### ISSUE THREAD

**Issue by jeppeskovsen** [Sitecore/jss#70]
## Description
If I create a new component and deploy the app, it creates a components folder: `sitecore/content/<site>/Content/<ComponentName>`. This folder is missing insert option for that component template. The second time I deploy the app, insert option is added correct.

## Expected behavior
Should add the options at first deployment.

## Steps To Reproduce
1. Scaffold new component
2. Run `jss deploy app`
3. Check insert options on component folder (only has folder)
4. Run deploy again
5. Insert options are correct

## Your Environment
* Sitecore Version: 9.0.2
* JSS Version: TP 4

## Screenshots
**After first deploy**
![after-first-deploy](https://user-images.githubusercontent.com/25830173/48249979-04b4f800-e3fd-11e8-9a3f-042994ad849b.png)

**After second deploy**
![after-second-deploy](https://user-images.githubusercontent.com/25830173/48249980-054d8e80-e3fd-11e8-8d70-fd1ecf91fc83.png)

**Comment by kamsar** [comment]
This bug has been previously found and fixed for the final release (re-validated just now). Thanks for the issue! :)
