### ISSUE TITLE
FR: The possibility to add inheritance with setDefaultRouteType

### ISSUE THREAD

**Issue by jeppeskovsen** [Sitecore/jss#71]
## Is your feature request related to a problem? Please describe.
I want to have the default route template to inherit from more than just `/sitecore/templates/JavaScriptServices/Route`

I don't want to change any templates under `JavaScriptServices`.

## Describe the solution you'd like
Make the `inherits` property work like this:
`inherits: [ "{B36BA9FD-0DC0-49C8-BEA2-E55D70E6AF28}" ]`

**Comment by jeppeskovsen** [comment]
Then it’s a bug :) It doesn’t add my templates I set as inherits when using setDefaultRouteType.. it works on templates and components.

**Comment by kamsar** [comment]
You're correct the base template is manually set in the import process so setting `inherits` will not work. However, two things:

1) This is the _default_ route type. Other route types will inherit from it so it is intended to be the base of the hierarchy. What's the purpose of separating a secondary inherited template from something that is designed to be at the root? In most cases, it seems like it might be unnecessary complexity.
2) You can specify what the app's inherited base template is already on the JSS app configuration in the app's config patch, essentially giving you what you want as long as this base template itself inherits the JSS system Route template:

```
<app name="MyApp"
             ...
             routeBaseTemplate="/sitecore/templates/My/Custom/Base/That/Inherits/JSS/Base/Route"
        />
```

**Comment by kamsar** [comment]
Never mind - I retested it again using `inherits` and this _does_ work in GA - just not for TP4.
