### ISSUE TITLE
Titles in documentation is not ordered correctly.

### ISSUE THREAD

**Issue by Myoxocephalus** [Sitecore/jss#72]
## Description

In this page:
https://jss.sitecore.net/docs/techniques/azure-deployment
Step 3 is missing.

## Expected behavior

Step 4 should change to Step 3.
Step 5 should change to Step 4.

## Steps To Reproduce

1. Go to https://jss.sitecore.net/docs/techniques/azure-deployment
2. Scroll down to see step 2 and 4.
3. See error

## Possible Fix
Step 4 should change to Step 3.
Step 5 should change to Step 4.

**Comment by kamsar** [comment]
Thanks for noticing that. I've corrected it in the documentation that will ship with JSS general availability :)
