### ISSUE TITLE
FR: Allow to use ContentSecurityPolicy without 'unsafe-inline'

### ISSUE THREAD

**Issue by jantimon** [Sitecore/jss#76]
Hey

this proposal is a little bit ambitious but it comes with a lot of advantages.

## Summary

Right now the `jss` boilerplate uses a script tag (`<script>__JSS_STATE__=...</script>`) to communicate between backend and frontend.

I would propose to change this a little bit to the following structure:

```
<script data-name="JSS_STATE" type="text/json">
{...}
</script>
```

This technique is described in different blog articles - this one is quite nice to read:
https://quipblog.com/efficiently-loading-inlined-json-data-911960b0ac0a

### Disadvantages

- According to [serialize-javascript json](https://www.npmjs.com/package/serialize-javascript#optionsisjson) `state` must not function or regexps values.

### Advantages

- Faster state generation. According to [serialize-javascript json](https://www.npmjs.com/package/serialize-javascript#optionsisjson) serialization is 3 times faster on the node js side
- According to [https://quipblog.com](https://quipblog.com/efficiently-loading-inlined-json-data-911960b0ac0a) even faster in frontend - (however I am not sure if this is still true)
![image](https://user-images.githubusercontent.com/4113649/48705115-a3f59e80-ebf8-11e8-9d16-ae73e904dd8e.png)

- Removes one security vector as the `<script type="text/json">` is not able to execute javascript ([the script tag is ignored](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-type))
- Adds the ability for additional security hardening by using the [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src) without `'unsafe-inline'`.
- Adds more flexibility as it would allow to have multiple react widgets on one page (E.g. one for a complex navigation and one for the body) 

## How would that work on the frontend side?

Lets assume that the backend would generate the following markup

```html
<script data-name="JSS_STATE" type="text/json">
{...}
</script>
<div data-name="jss-root" data-app="Navigation">server side rendered markup</div>
```

The frontend code could be for the `Navigation` (maybe that part could also be reusable):

```js
const jssRoots = document.querySelectorAll('[data-name="jss-root"][data-app="Navigation"]');
for (let i = 0; i < jssRoots.length; ++i) {
  const jssRoot = jssRoots[i];
  const jssConfigScript = jssRoot.previousElementSibling;
  const jssInitialState = JSON.parse(jssConfigScript.innerHTML);
  // Hydrate the app e.g. with react:
  ReactDOM.hydrate(React.createElement(Navigation, jssInitialState), jssRoot);
}
```

**Comment by kamsar** [comment]
This looks _great_. Won't be able to do it for GA, but the idea of not needing `unsafe-inline` in a CSP is 💯

**Comment by kamsar** [comment]
#95 is open to fix this. To keep things simple I did not make it run with multiple apps on the same page out of the box, but the pattern will certainly extend to allow that for people that need that functionality.
