### ISSUE TITLE
React Scaffold Hint could be improved

### ISSUE THREAD

**Issue by jantimon** [Sitecore/jss#77]
## Description

This is really a tiny tiny issue - so feel free to ignore it.

If you run the jss command without any arguments it tells you

```
Usage: jss scaffold <componentName>
```

If you now try that 

```
jss scaffold componentName
```

It will tell you `Component name should start with an uppercase letter and contain only letters and numbers`

## Expected behavior

Maybe you could use PascalCase here in the documentation (`componentName` -> `ComponentName`) if this is the required format:

```
Usage: jss scaffold <ComponentName>
```

**Comment by kamsar** [comment]
Resolved for release.
