### ISSUE TITLE
FR: Allow us to type the PlaceholdersData name

### ISSUE THREAD

**Issue by jantimon** [Sitecore/jss#78]
Right now the `PlaceholdersData` interface from `@sitecore-jss/sitecore-jss/types/dataModels.d.ts` is defined as:

```ts
export interface PlaceholdersData {
    [name: string]: Array<ComponentRendering | HtmlElementRendering>;
}
```

So any `name` is a valid placeholder name.  
This is already quite nice however it could be improved so we can keep placeholder names maintainable even for large projects.

The main advantage is that it would allow typescript to check if a name can be used for this component and the user gets faster access to the information about which placeholder name is usable in the current context.

In the following example it allows only to use the name "jss-reuse-example":

<img width="380" alt="placeholder" src="https://user-images.githubusercontent.com/4113649/48783289-505e8000-ece0-11e8-967e-166f44910821.png">

Hovering will even tell you that "unknown-placeholder-name" is not supported for this component.

<img width="619" alt="placeholder2" src="https://user-images.githubusercontent.com/4113649/48783491-cc58c800-ece0-11e8-9ab1-2f2e0b18a8a3.png">

## Describe the solution you'd like

Changing the type just a little bit will allow it to be used as a generic:

```ts
export type PlaceholdersData<K extends string = string> = {
  [P in K]: Array<ComponentRendering | HtmlElementRendering>;
}
```

`K extends string = string` means that you can provide all allowed names (but it's optional and if you don't provide anything it will fallback to the current behaviour - so this would be backwards compatible)

Usage of that type:

```ts
// Allow only jss-placeholder-one or jss-placeholder-two
type DemoRestrictedPlaceholdersData = PlaceholdersData<'jss-placeholder-one' | 'jss-placeholder-two'>;
```

## Additional information

A full example including a very basic example for the `PlaceholderProps` can be seen here: https://codesandbox.io/s/0100y49vn

**Comment by kamsar** [comment]
#92 is open to fix this
