### ISSUE TITLE
createDefaultDisconnectedServer uses hardcoded sourceFiles, pipelinePatchFiles and outputPath

### ISSUE THREAD

**Issue by jantimon** [Sitecore/jss#79]
## Description

Right now `createDefaultDisconnectedServer` is not passing important options like the `sourceFiles` option to the `ManifestManager` constructor.  
Instead it is using hard coded relative file paths which are always resolved relative to `process.cwd()`.

From `@sitecore-jss/sitecore-jss-dev-tools/dist/manifest-manager.js` line 44, 45

```js
'./sitecore/definitions/**/*.sitecore.js',
'./sitecore/definitions/**/*.sitecore.ts',
```

This causes serious problems if the `process.cwd()` can't be set to the folder where the `sitecore` folder or if the `sitecore` folder is placed inside a folder.

## Possible Fix

Version @sitecore-jss/sitecore-jss-dev-tools - **9.0.6**

Imho there are two good options which would improve the current situation.  

### use `rootPath`

Right now the `@sitecore-jss/sitecore-jss-dev-tools/dist/manifest-manager.js` line 44, 45
is using relative paths although it might use the `rootPath` variable instead.

```
       [
            './sitecore/definitions/**/*.sitecore.js',
            './sitecore/definitions/**/*.sitecore.ts',
        ]
```

A quite easy way would be to use the `rootPath` instead of the `.`.
However this would require that rootPath would really be the root of the project (see #80).

Another option would be to add a variable called `sitecore` path which would be set to `./sitecore/` by default.

E.g.:

```
[
  path.resolve(rootPath, 'sitecore/definitions/**/*.sitecore.js'),
  path.resolve(rootPath, 'sitecore/definitions/**/*.sitecore.ts'),
]
```

or maybe even better

```
[
  path.resolve(sitecorePath, 'definitions/**/*.sitecore.js'),
  path.resolve(sitecorePath, 'definitions/**/*.sitecore.ts'),
]
```

### Allow to configure all options 

Another way which might be implemented in combination with the proposed rootPath change would be to allow passing all values from the disconnected-server to the manifest manager

`@sitecore-jss/sitecore-jss-dev-tools/dist/disconnected-server/create-default-disconnected-server.js` line 24+

```
var manifestManager = new manifest_manager_1.ManifestManager({
        appName: options.appName,
        rootPath: options.appRoot,
        watchOnlySourceFiles: options.watchPaths,
        requireArg: options.requireArg,
    });
```

could be changed to:

```
var manifestManager = new manifest_manager_1.ManifestManager(Object.assign({
        appName: options.appName,
        rootPath: options.appRoot,
        watchOnlySourceFiles: options.watchPaths,
        requireArg: options.requireArg,
    }, options.manifestManagerOptions));
```

That way the `manifestManagerOptions` would be an optional parameter which could carry every current and future parameter to the manifestManager.

## Your Environment

* JSS Version: **9.0.6**

**Comment by kamsar** [comment]
`createDefaultDisconnectedServer` is intended to be a boilerplate for relatively simple scenarios to reduce new developer confusion. The intent is that if you need to deeply customize app conventions, that you'd take the contents of `createDefaultDisconnectedServer()` and place it in your app to customize away. This is _currently_ harder than it needs to be because only the compiled function is on npm but post-release when the npm packages are open source the source will be available to copy.

**Comment by jantimon** [comment]
Basically all I tried was to add a monorepository structure for our project which required a different script working directory was not possible.
 
If I understood you correctly you won’t support folder customizations and users of JSS have to fork the disconnectedServer and to maintain the entire stack to move a folder?

**Comment by jantimon** [comment]
Okay thank you I wasn’t aware that the disconnectedServer was just a small helper.

JSS already consists out of a lot of code and conventions.

For me who did not write the JSS library it is hard to find out which parts can be removed without breaking either the connected, disconnected or integrated mode.

And it is even harder to guess the developers intend e.g. for allowing to configure some parts and forbid to configure other parts.

My greatest concern of copying over JSS library code into my codebase is that I don’t know what change would cause cause upgrade problems in future.

Do you plan a boilerplate with a custom disconnected server?

**Comment by kamsar** [comment]
Documented in #93
