### ISSUE TITLE
createDefaultDisconnectedServer expects appRoot to be set to the script folder

### ISSUE THREAD

**Issue by jantimon** [Sitecore/jss#80]
## Description

Right now the createDefaultDisconnectedServer is expecting the "root" not to be set to the root of the project but to the scripts directory:

https://github.com/Sitecore/jss/blob/0292a05077c4ef21b668eb9c30412f57620c3779/samples/react/scripts/disconnected-mode-proxy.js#L18-L19

This is also hard coded inside the `createDefaultDisconnectedServer` (Version 9.0.6) code:

`@sitecore-jss/sitecore-jss-dev-tools/dist/disconnected-server/create-default-disconnected-server.js` line 52, 53:

```
app.use('/assets', express_1.default.static(path_1.join(options.appRoot, '../assets')));
app.use('/data/media', express_1.default.static(path_1.join(options.appRoot, '../data/media')));
```

As you can see it has to add `..` to get rid of the scripts folder.

**Comment by kamsar** [comment]
As mentioned in https://github.com/Sitecore/jss/issues/79#issuecomment-441726735 these are default conventions of a JSS app. If you want to override those conventions, expand `createDefaultDisconnectedServer()` and tweak away. The use of `appRoot` is a confusing name here, yes.

**Comment by jantimon** [comment]
Is there any reason why you chose to use the script folder over the actually root directory as appRoot?

I guess this is very unintuitive for new developers but probably easy to work around.

**Comment by kamsar** [comment]
It was a bad naming choice. Originally `createDefaultDisconnectedServer` was expanded in every sample app, and when it was extracted so it could be shared for maintainability that happened.

It may be worth investigating fixing this up after release to be less confusing, assuming we can do it in a non-breaking way.

**Comment by jantimon** [comment]
Cool thanks for explaining the history 👍

**Comment by kamsar** [comment]
This has been clarified and made to work by default using the _actual_ appRoot in #94
