### ISSUE TITLE
Lazy loading multiple components from one module (Angular)

### ISSUE THREAD

**Issue by agalbulev** [Sitecore/jss#82]
Hi JSS team, I am Aleksandar and I work in Virtual Affairs. I saw that you now have a feature for lazy loading of component which is great. I try to made lazy loading module with multiple components which will be great feature for us but it not possible with current implementation. I made research in your code and found that this is possible with little change which can be make on JssModule.forChild function.

That is my fork with pull request: https://github.com/Sitecore/jss/pull/83/commits/91fe9b02be0d48b4389929a155b64084859761a2

    JssModule.forChild = function (components) {
        var providers = [
            { provide: ROUTES, useValue: [], multi: true }
        ];
        components.forEach(function (component) {
            providers.push({ provide: ANALYZE_FOR_ENTRY_COMPONENTS, useValue: component, multi: true });
            providers.push({ provide: DYNAMIC_COMPONENT, useValue: component });
        })

        return {
            ngModule: JssModule,
            providers: providers,
        };
    };

And also need to put different path like 'StyleguideAngularLazyLoading' and 'ContentBlockLazyLoading' with same loadChildren value in JssModule.withComponents argument.

    { path: 'StyleguideAngularLazyLoading', loadChildren: './styleguide-angular-lazy-loading/styleguide-angular-lazy-loading.module#StyleguideAngularLazyLoadingModule'},
    { path: 'ContentBlockLazyLoading', loadChildren: './styleguide-angular-lazy-loading/styleguide-angular-lazy-loading.module#StyleguideAngularLazyLoadingModule'}

**Comment by kamsar** [comment]
Closing this as it has #83 open as a PR
