### ISSUE TITLE
[Vue] - RouteLinkedRichText

### ISSUE THREAD

**Issue by markgibbons25** [Sitecore/jss#856]
Please consider implementing this in the vue sample app or in the vue package itself?

https://markgibbons25.medium.com/using-the-vue-router-on-sitecore-rich-text-fields-d0c678934227

**Comment by CobyPear** [comment]
Hello @markgibbons25. This is a great idea and your proposed solution looks good at first glance. Would you like to open a PR for this? Check the contributing guide as it has had recent updates and we'll be happy to merge it in.

https://github.com/Sitecore/jss/blob/dev/CONTRIBUTING.md

**Comment by illiakovalenko** [comment]
@markgibbons25 Implemented in #1037
