### ISSUE TITLE
VisitorIdentification only works on homepage due to missing VirtualFolder meta

### ISSUE THREAD

**Issue by markgibbons25** [Sitecore/jss#886]
## Description
I have checked all the samples, and none are emitting the required `VirtualFolder` meta which the VisitorIdentification.js uses to build the correct path for layouts/system/VIChecker.aspx and layouts/system/VisitorIdentificationCSS.aspx

## Expected behavior
`VirtualFolder` meta tag is emitted, using the correct site virtual folder set on the site config, which makes the VisitorIdentification.js work correctly on child pages (not site root)

## Steps To Reproduce
1. Go to a child page of the site root
2. Clear all cookies
3. Refresh the page
4. Check console errors for failure to render layouts/system/VisitorIdentificationCSS.aspx due to path name

JSS 18 (have also checked JSS 19 code)

**Comment by CobyPear** [comment]
Thank you @markgibbons25, we'll look into it!

**Comment by illiakovalenko** [comment]
@markgibbons25 Issue is not reproducible using latest version. I used Sitecore 10.2 and JSS 19.
VisitorIdentification.js contains code:

```
  function getVirtualFolder() {
    var virtualFolder = getMetatagContent("VirtualFolder");
    if (virtualFolder === "") {
      virtualFolder = "/";
    }

    return virtualFolder;
  }
```

so, in any case we will have `/`, and it fetch required files starting from the hostname, not from the current page

**Comment by markgibbons25** [comment]
@illiakovalenko good to know it is resolved in Sitecore 10.2, but it is still an issue on Sitecore 10.1

**Comment by illiakovalenko** [comment]
@markgibbons25 Another question, did you have some additional setup? For example in Sitecore site config, related to virtual folder?

**Comment by markgibbons25** [comment]
In this case, no, but I would presume it needs to work whether there is a virtual folder on the site or not
