### ISSUE TITLE
[Vue] There are no available renderings to select in "Select rendering" dialog (vue sample)

### ISSUE THREAD

**Issue by Dastonix** [Sitecore/jss#892]
## Description
I have created new vue sample with `jss create vue-sample vue` and "Select rendering" dialog in Expirience Editor looks like broken. The same dialog in react sample (`jss create react-sample react`) works correctly.

## Steps To Reproduce

1. Create new samples from vue and react templates
2. Go to Experience editor and edit the page
2. Try to add rendering to the page
3. See the difference beetween "Select rendering" dialogs

## Your Environment

* Sitecore Version: 10.2
* JSS Version: 19.0.0
* Browser Name and version: Chrome
* Node JS: 16.13.1 LTS

**Comment by CobyPear** [comment]
Thank you for the report @Dastonix! This bug was found and should be fixed by #859.
