### ISSUE TITLE
Angular Scaffolding is broken

### ISSUE THREAD

**Issue by kamsar** [Sitecore/jss#90]
## Description
Scaffolding with `jss scaffold` in Angular project is currently non-operational.

Refer to this SO question https://sitecore.stackexchange.com/questions/15464/error-when-trying-to-scaffold-an-angular-component

## Steps To Reproduce

1. `jss create foo angular`
1. `jss scaffold Foo`

## Feedback Wanted

The scaffolding system seems to be broken due to major breaking changes in the Angular Schematics module. JSS Angular scaffolding is based on the `ng generate component` schematic, which is unfortunately not particularly extensible and there's more code copying than I'd like.

There are a couple ways we could go about fixing this, and I'd like to hear from those who care with input on it:

### Stop using schematics

This is not the first time Angular breaking changes have caused problems for JSS. Given the simple nature of JSS scaffolding (and aim to allow users to customize it), we could dump schematics and use pure JS like the React and Vue samples do. This would lose the extra parameters that come with the component scaffold. It would also improve our ability to support multiple Angular versions as we would not be tied to breaking changes in the schematics module.

### Scaffold only the disconnected definition

We could make `jss scaffold` for Angular scaffold only the disconnected definition file. You'd use `ng generate component` directly for the rest of it.

### Some combination of the above

We could look into making `jss scaffold` scaffold the disconnected file and then invoke `ng generate`, noting that there wouldn't be any JSS-specific tweaks to the generated components.

**Comment by JonK723** [comment]
I think the third option of scaffolding the disconnected definition and invoking `ng generate` aligns better with what it looks like the React and Vue scaffold commands do. I personally don't mind doing a little more manual work to connect my component to the rest of my application as long as I'm not tied to a feature that has the possibility of breaking everything.

**Comment by kamsar** [comment]
#106 fixes the scaffolding itself without any semantic changes

**Comment by x1c0** [comment]
Hello,

Not sure if I should be writing on this close issue, but I just fresh install everything following the guide [https://jss.sitecore.com/docs/getting-started/first-component](url) and I have the following error:

![image](https://user-images.githubusercontent.com/2421483/50761443-affdf400-126a-11e9-877b-802ca0ba4ab5.png)

Is this related? should I open a new issue?

**Comment by x1c0** [comment]
ah this fix was only merged to Dev, when are you releasing master to npm?

Thanks in advance!

**Comment by x1c0** [comment]
Hi @kamsar thanks for your reply, when you mean "should be as simple as bump the version" you mean go through all the packages/* package.json files and bump all of them to let's say 12.0.0 and then `npm run build` and publish the dist folder

**Comment by kamsar** [comment]
@x1c0 if you want to publish only the angular schematics, then only do it for the angular schematics package. If you want to publish your own totally private version, then pointing to your private registry in `.npmrc` and then running `npm run reset` at the root and then `npx lerna publish` will automatically bump all the versions, publish all the packages, tag it in your fork repo, etc

**Comment by x1c0** [comment]
Hi @kamsar I followed your steps to bump automatically the version with lerna after running `npm run reset` <- I could see the new changed files.

but then when trying to run `npm lerna publish` I got the following error, what am I doing wrong?
![image](https://user-images.githubusercontent.com/2421483/51310806-bac53f80-1a47-11e9-92c9-d01ba09713bf.png)

**Comment by kamsar** [comment]
@x1c0 it looks like your node version (9.0.0) may need to be upgraded. Node 9 was a fast preview build that is no longer supported by Node; Node 8.x or Node 10.x are the supported LTS
