### ISSUE TITLE
Next.js RichText component not forwarding query params when clicking on internal links

### ISSUE THREAD

**Issue by thaiphan** [Sitecore/jss#990]
## Description

I have the following rich text field...

```tsx
<p>We are the <a href="/why-choose-us?overview=performance">fastest provider</a> available.</p>
```

If I click on the internal link, I am currently redirected to `/why-choose-us`. However, the `?overview=performance` bit does not seem to get added to the URL.

## Expected behavior
I would like for the search query parameter, i.e. `?overview=performance`, to be appended to the URL whenever I click on a rich text internal link. We're using search query params a lot to control things like which tab on the page is currently open, etc.

## Possible Fix
Maybe pass the value of `link.search` through to `router.push` somehow here: https://github.com/Sitecore/jss/blob/v21.0.0-canary.37/packages/sitecore-jss-nextjs/src/components/RichText.tsx#L42

## Your Environment
* Sitecore Version: 10
* JSS Version: 19.0.2
* Browser Name and version: Chrome 100
* Operating System and version (desktop or mobile): OS X

**Comment by ambrauer** [comment]
@thaiphan thanks for the information, I've added this to our backlog to investigate / fix in a future release.

We also gladly accept pull requests if you'd like to take a stab at it. Check the [contributing guide](https://github.com/Sitecore/jss/blob/dev/CONTRIBUTING.md) and we'll be happy to merge it in.

**Comment by thaiphan** [comment]
Do you think this is something that you can add as a patch?
